const english = [
  [`try out`, `სცადო`],
  [`head over to`, `სადმე წასვლა`],
  [`work off`, `მოშორება`],
  [`catch up on`, `უახლესი ამბების გაგება`],
  [`get around`, `გადაადგილება`],
  [`hit the books`, `სწავლა`],
  [`hand in`, `დავალების, სამუშაოს ჩაბარება`],
  [`fall behind`, `ჩამორჩენა`],
  [`get caught up`, `დაეწიო მასალას, კლასს`],
  [`expel`, `გარიცხვა`],
  [`tuition fee`, `სწავლის საფასური`],
  [`bursary`, `სტიპენდია`],
  [`repetitive`, `განმეორებადი`],
  [`rewarding`, `სასიამოვნო, დასაფასებელი`],
  [`glamorous`, `მომხიბლავი, წარმტაცი`],
  [`gruelling`, `სასტიკი, დამქანცველი`],
  [`tedious`, `შრომატევადი, მოსაწყენი`],
  [`fascinating`, `მომაჯადოებელი`],
  [`hazardous`, `საშიში, სარისკო`],
  [`stimulating`, `შემაგულიანებელი`],
  [`sincerely`, `პატივისცემა`],
  [`faithfully`, `კეთილსინდისიერება`],
  [`efficient`, `კვალიფიციური, მარჯვე, ქმედითი`],
  [`effective`, `ეფექტური, სასარგებლო`],
  [`affect`, `ზეგავლენა`],
  [`effect`, `შედეგი, გავლენა`],
  [`rise`, `აღმასვლა, ზრდა, ამაღლება`],
  [`raise`, `გაზრდა, მატება`],
  [`convenient`, `ხელსაყრელი, მოსახერხებელი`],
  [`indispensable`, `აუცილებელი, შეუცვლელი`],
  [`cutting-edge`, `თანამედროვე, მოწინავე`],
  [`invaluable`, `ფასდაუდებელი, შეუფასებელი`],
  [`state-of-the-art`, `თანამედროვე`],
  [`handy`, `მარჯვე, მოსახერხებელი`],
  [`obsolete`, `ხმარებიდან გადასული, მოძველებული`],
  [`impractical`, `არაპრაქტიკული`],
  [`outdated`, `დაძველებული`],
  [`worthless`, `გამოუსადეგარი, გაუფასურებული`],
  [`enhance`, `გაუმჯობესება, გაძლიერება`],
  [`glance`, `თვალის გადავლება, გადათვალიერება`],
  [`pilot scheme`, `სატესტო მოდელი`],
  [`transcribe`, `გადაწერა, განმარტება, გადათარგმნა`],
  [`seamlessly`, `შეუფერხებლად`],
  [`astonishing`, `საკვირველი, გასაოცარი`],
  [`self-conscious`, `მორცხვი, გაუბედავი`],
  [`put someone's buttons`, `რეაქციის პროვოცირება`],
  [`malfunction`, `გაუმართავობა`],
  [`deterrent`, `შემაკავებელი ფაქტორი`],
  [`keep track of`, `თვალყურის დევნება`],
  [`surveillance`, `ზედამხედველობა`],
  [`an invasion of privacy`, `კონფიდენციალურობის დარღვევა`],
  [`consent`, `თანხმობა`],
  [`abuse`, `ბოროტგანზრახვა`],
  [`mandatory`, `აუცილებელი, სავალდებულო`],
  [`intrusive`, `მაბეზარი, დაუპატიჟებლად მისული`],
  [`violate`, `დარღვევა, შებღალვა`],
  [`disclose`, `გამხელა, გამოაშკარავება`],
  [`obliged`, `ვალდებული, იძულებული`],
  [`suspicion`, `ეჭვი`],
  [`suspicious`, `საეჭვო`],
  [`drawback`, `შეცდომა, ნაკლი, ხარვეზი`],
  [`loathe`, `ზიზღი, სიძულვილი`],
  [`concise`, `მოკლე, ლაკონური`],
  [`evaluation`, `შეფასება, განსაზღვრა, დადგენა`],
  [`conduct`, `ჩატარება, წაყვანა`],
  [`objective`, `ამოცანა, მიზანი`],
  [`carry out`, `შესრულება, ბოლომდე მიყვანა`],
  [`vast`, `ვრცელი, დიდი`],
  [`identify`, `სინამდვილის დადგენა, განსაზღვრა`],
  [`state`, `განცხადება`],
  [`pedestrian`, `ქვეითი, ფეხით მოსიარულე`],
  [`promote`, `წახალისება, მხარდაჭერა, ხელშეწყობა, დაწინაურება`],
  [`vary`, `განსხვავება, გამოცვლა`],
  [`ensure`, `უზრუნველყოფა, დაზღვევა`],
  [`utmost`, `ზღვარი, ყველაზე დიდი, პიკი`],
  [`estimate`, `შეფასება, აღრიცხვა, დათვლა`],
  [`carefree`, `ქარაფშუტა, უდარდელი`],
  [`consumption`, `მოხმარება, ხარჯვა`],
  [`fatty`, `ცხიმიანი, მსუქანი`],
  [`gradually`, `თანდათან, ნელ-ნელა`],
  [`obese`, `სიმსუქნით დაავადებული`],
  [`offender`, `დამნაშავე, ზიანისმომტანი`],
  [`devastating`, `დამანგრეველი, შიშისმომგვრელი`],
  [`subside`, `დავარდნა, ცვენა, კლება, ჩაწყნარება`],
  [`concern`, `დამოკიდებულება, კავშირი, შეშფოთება`],
  [`tumour`, `სიმსივნე`],
  [`consume`, `მოხმარება, შთანთქმა`],
  [`humble`, `თავმდაბალი, დამცირება, შერცხვენა`],
  [`induction`, `თანამდებობაზე დანიშვნა, შესვლა`],
  [`trail`, `კვალი, ბილიკი`],
  [`treat`, `სიტკბოება, გამასპინძლება, მკურნალობა`],
  [`sleigh`, `მარხილი, ციგა`],
  [`belly`, `მუცელი, ღიპი`],
  [`hilarious`, `მხიარული, ხალისიანი, სასაცილო`],
  [`boiling`, `მდუღარე, დუღილი`],
  [`scorching`, `მცხუნვარე, მწველი, ძალიან ცხელი`],
  [`deafening`, `გამაყრუებელი, ზედმეტად ხმაურიანი`],
  [`packed`, `ძალიან გადაჭედილი, გადავსებული`],
  [`astounding`, `გასაოცარი, განსაცვიფრებელი`],
  [`knackered`, `დაღლილი, გადაღლილი`],
  [`spotless`, `უმწიკვლო, სუფთა`],
  [`filthy`, `ჭუჭყიანი, ბინძური`],
  [`utterly`, `უკიდურესად, მეტისმეტად, უნაკლოდ`],
  [`tend to`, `მიდრეკილება`],
  [`help out`, `დახმარება`],
  [`toast`, `შეწვა, სადღეგრძელოს თქმა`],
  [`festive`, `სადღესასწაულო`],
  [`despise`, `ზიზღი`],
  [`detest`, `სიძულვილი, შეჯავრება`],
  [`stall`, `დახლი, ჯიხური`],
  [`liven up`, `გამოცოცხლება, გამხიარულება`],
  [`windmill`, `ქარის წისქვილი`],
  [`blade`, `პირი (დანის, ჩოგნის), ფრთა`],
  [`drought`, `გვალვა, გახმობა`],
  [`famine`, `შიმშილობა`],
  [`irrigate`, `მორწყვა`],
  [`pump`, `ტუმბო, ამოტუმბვა`],
  [`harness`, `აკაზმულობა, ღვედები`],
  [`invincible`, `უძლეველი, დაუმარცხებელი`],
  [`breath taking`, `გასაოცარი, სულისშემკვრელი`],
  [`remarkable`, `შესანიშნავი, გამორჩეული`],
  [`petrified`, `გაქვავებული, გაშეშებული`],
  [`furious`, `გაცოფებული, მრისხანე, გაშმაგებული`],
  [`excruciating`, `მტანჯველი, აუტანელი`],
  [`soaking`, `დასველება, გაჟღენთვა`],
  [`astonished`, `თავზარდაცემული, გაოცებული`],
  [`delighted`, `კმაყოფილი, მოხარული`],
  [`elated`, `გამხნევება, ხალისიანი, აღტაცებული`],
  [`exorbitant`, `ზედმეტი, უზომო`],
  [`pedestrian precinct`, `ქვეითთა სავალი გზა`],
  [`exhaust fumes`, `მავნე ნივთიერებების გამოყოფა`],
  [`atrium`, `დერეფანი, მოლი, წიაღი`],
  [`electricity socket`, `შტეფცელი`],
  [`emphasize`, `გამახვილება, ხაზგასმა`],
  [`social interaction`, `სოციალური ურთიერთქმედება`],
  [`vocational`, `პროფესიონალური`],
  [`blended`, `ნარევი, შერეული`],
  [`peer`, `თანატოლი, თანაბარი, თანასწორი`],
  [`deduct`, `გამოქვითვა, გამოკლება`],
  [`pave`, `საფარი, ზედაპირი, დაგება/დაფენა`],
  [`scheme`, `სქემა, გეგმა, სისტემა, სტრუქტურა`],
  [`honeybee`, `ფუტკარი`],
  [`in brief`, `მოკლედ`],
  [`with a view to`, `იმ მიზნით, რომ`],
  [`with the intention of`, `იმ განზრახვით`],
  [`so as to`, `რათა`],
  [`in order to`, `იმისთვის, რომ`],
  [`so that`, `ასე რომ`],
  [`due to`, `იქიდან გამომდინარე, შედეგად`],
  [`be tempted to do something`, `რაღაცის გაკეთების ცდუნება`],
  [`find out about something`, `რაიმეს შესახებ გარკვევა`],
  [`do the right thing`, `გააკეთო ის, რაც სწორია`],
  [`earn a good salary`, `გამოიმუშავო კარგი ხელფასი`],
  [`have an impact on something`, `რაიმეზე მოახდინო ზეგავლენა`],
  [`tell the truth`, `სიმართლის თქმა`],
  [`get away with it`, `თავი დააღწიე, მოშორდი მას`],
  [`have chance to do something`, `რაიმეს გაკეთების შანსის ქონა`],
  [`do overtime`, `ზეგანაკვეთზე მუშაობა`],
  [`apply for a job`, `სამუშაოზე განაცხადის შეტანა`],
  [`in charge of`, `პასუხისმგებელი`],
  [`take someone on part time`, `ნახევარ განაკვეთზე აყვანა`],
  [`receive fringe benefits`, `დამატებითი სარგებლის მიღება`],
  [
    `make someone redundant`,
    `სამსახურში შემცირების დაწყება, ვინმეს გათავისუფლება`,
  ],
  [`that sounds like a great job`, `შესანიშნავი სამსახური ჩანს`],
  [`I'd love to do that`, `ძალიან მომეწონებოდა ამის გაკეთება`],
  [
    `that could be quite fun I'd have thought`,
    `ვფიქრობ, ძალიან სახალისო იქნებოდა`,
  ],
  [`that gives you the chance to`, `ის გაძლევს შანსს, რომ`],
  [
    `that must be a definite plus of the job`,
    `ეს აშკარად ამ სამუშაოს პლიუსი უნდა იყოს`,
  ],
  [
    `it's not nearly as bad as it sounds`,
    `მთლად ისეთი ცუდიც არაა, როგორიც ჩანს`,
  ],
  [`the benefits outweigh the drawbacks`, `სარგებლობა აღემატება ნაკლოვანებას`],
  [`you have the option of`, `ამის საშუალება გაქვს`],
  [`there are lots of advantages`, `ბევრი უპირატესობა აქვს`],
  [`the problem with the job is that`, `ამ სამუშაოს პრობლემა ისაა, რომ`],
  [
    `I couldn't stand it if I had to do it`,
    `ვერ ავიტანდი ამის კეთება რომ მიწევდეს`,
  ],
  [`I wouldn't be able to do that job`, `იმ სამუშაოს შესრულებას ვერ შევძლებდი`],
  [`I'd prefer to eat normal food`, `მირჩევნია ნორმალური საკვები ვჭამო`],
  [`I'd loathe that sort of work`, `იმ სახის სამუშაო შემზიზღდებოდა`],
  [
    `I think that must be one of the most awful jobs because`,
    `ვფიქრობ, ეს ყველაზე საშინელი სამსახურია, რადგან`,
  ],
  [`the biggest disadvantage is`, `ყველაზე დიდი მინუსი ისაა`],
  [`it's a dead-end job`, `ეს უპერსპექტივო სამსახურია`],
  [`it just pays the bills`, `უბრალოდ გადასახადებს იხდის`],
  [`I couldn't agree more`, `უფრო მეტად ვერც კი დაგეთანხმები`],
  [`I know exactly what you mean`, `ზუსტად ვიცი რასაც გულისხმობ`],
  [`we're seeing eye to eye`, `ერთმანეთს ვეთანხმებით`],
  [`I'm with you here`, `გეთანხმები ამაში`],
  [`I'll go along with that`, `ამ აზრს მხარს ვუჭერ`],
  [`You've made a good point`, `კარგი აზრი დააფიქსირე`],
  [`I hold the same opinion`, `იგივე აზრზე ვარ`],
  [`I'm not sure about that`, `ამაში დარწმუნებული არ ვარ`],
  [`I beg to differ`, `არ გეთანხმები (ზრდილობიანად)`],
  [`That's not always the case`, `ეს ყოველთვის ასე არ არის`],
  [`I don't think you're right`, `არ ვფიქრობ, რომ მართალი ხარ`],
  [`I think otherwise`, `სხვაგვარად ვფიქრობ`],
  [`I agree up to a point, but`, `რაღაც მომენტამდე გეთანხმები, მაგრამ`],
  [`I see your point, but`, `ვხედავ შენს აზრს, მაგრამ`],
  [`I know what you mean, but`, `ვიცი რასაც გულისხმობ, მაგრამ`],
  [`That's partly true, but`, `ეს ნაწილობრივ სიმართლეა, მაგრამ`],
  [`if I can give you an example`, `თუ მაქვს საშუალება მაგალითი მოვიყვანო`],
  [`Take this for example`, `აიღე ეს მაგალითად`],
  [`research suggests that`, `კვლევა ვარაუდობს, რომ`],
  [
    `if I can finish what I was saying`,
    `თუ შეიძლება დავასრულო, რასაც ვამბობდი`,
  ],
  [`if you'll let me finish`, `თუ მაცდი დასრულებას`],
  [
    `excuse me, but could I say something here`,
    `უკაცრავად, მაგრამ შეიძლება აქ რაღაც ვთქვა`,
  ],
  [`could I just come in here, please`, `შემიძლია საუბარში ჩაგერთოთ, გთხოვთ`],
  [`don't interrupt, please`, `არ შეაწყვეტინოთ, გთხოვთ`],
  [`just calm down, please`, `უბრალოდ დამშვიდდით, გთხოვთ`],
  [`where do you stand on this`, `ამაზე რა აზრის ხართ`],
  [`what's your response to that`, `ამაზე რა არის თქვენი პასუხი`],
  [`do you agree with that`, `ეთანხმებით ამას`],
  [`without them, we wouldn't be able to`, `მათ გარეშე, ჩვენ ვერ შევძლებდით`],
  [`we couldn't manage without it`, `მის გარეშე ვერ გავუმკლავდებოდით`],
  [`I think we can get by without it`, `ვფიქრობ, ამის გარეშეც გავძლებთ`],
  [
    `they're no longer considered to be`,
    `ისინი აღარ არიან მიჩნეულნი, რომ არიან`,
  ],
  [`concerns were raised about`, `შეშფოთება გამოითქვა`],
  [`it would seem like`, `როგორც ჩანს`],
  [`throw out the lawsuit`, `სარჩელის არ მიღება`],
  [`to say the least`, `რბილად რომ ვთქვათ`],
  [`have a soft spot for`, `ძალიან მოწონება`],
  [`have a penchant for`, `რამეს კეთების ჩვევა, მოწონება`],
  [`put somebody off`, `არ მოაწონო, შეაზიზღო`],
  [`be less keen on`, `ნაკლებად დაინტერესება`],
  [`we favour the opinion of`, `ჩვენ მხარს ვუჭერთ აზრს`],
  [`build a relationship`, `ურთიერთობის დამყარება`],
  [`keep someone's word`, `დანაპირების შესრულება`],
  [`the take-home message`, `მთავარი/დასამახსოვრებელი მესიჯი`],
  [`let me turn to the next point`, `ნება მომეცით გადავიდე შემდეგ პუნქტზე`],
  [`on the same wavelength`, `რაიმეზე ერთნაირი აზრის ქონა`],
  [`It's not rocket science`, `არ არის რთული გასაგებად`],
  [`we got our wires crossed`, `ერთმანეთის ვერ გაგება`],
  [`light years ahead`, `მოწინავე, ძალიან განვითარებული`],
  [`re-invent the wheel`, `დროის დახარჯვა რაიმე უკვე გაკეთებულზე`],
  [`up and running`, `მზადაა გამოსაყენებლად`],
];
