const english_graph = [
  ["rise", "მატება, ზრდა"],
  ["increase", "გაზრდა, მომატება"],
  ["grow", "ზრდა"],
  ["climb", "ტემპერატურის/მაჩვენებლის აწევა"],
  ["surge", "მკვეთრი მოზღვავება"],
  ["soar", "მკვეთრად აწევა, ზეაფრენა"],
  ["rocket", "სწრაფად აწევა (რაკეტასავით)"],
  ["jump", "ნახტომისებური ზრდა"],
  ["escalate", "თანდათანობითი ესკალაცია"],
  ["shoot up", "მკვეთრად აწევა"],
  ["spike", "მოკლევადიანი მკვეთრი მატება"],
  ["fall", "დაცემა, შემცირება"],
  ["decrease", "შემცირება"],
  ["decline", "კლება"],
  ["drop", "ვარდნა"],
  ["plunge", "მკვეთრი ვარდნა"],
  ["plummet", "თავზარდამცემი ვარდნა"],
  ["dip", "მცირე, მოკლევადიანი ვარდნა"],
  ["slump", "მკვეთრი ვარდნა (ეკონომიკური)"],
  ["tumble", "სწრაფი ვარდნა"],
  ["sink", "ჩაძირვა, დაცემა"],
  ["slide", "თანდათანობითი ვარდნა"],
  ["stabilize", "სტაბილიზაცია"],
  ["level off", "გასწორება, სტაბილურ დონეზე გამოსვლა"],
  ["plateau", "პლატო, უცვლელი დონე"],
  ["remain steady", "თანაბრად დარჩენა"],
  ["remain constant", "მუდმივად დარჩენა"],
  ["stagnate", "სტაგნაცია, გაჩერება"],
  ["flatten out", "გასწორება, გათანაბრება"],
  ["fluctuate", "რყევა, მერყეობა"],
  ["vary", "ცვალებადობა"],
  ["oscillate", "ბაგირისებური რყევა"],
  ["see-saw", "ზევით-ქვევით რყევა"],
  ["peak", "მწვერვალი, პიკი"],
  ["hit a high of", "მაქსიმუმს მიღწევა"],
  ["reach a low of", "მინიმუმს მიღწევა"],
  ["bottom out", "ფსკერზე დაბრუნება, ყველაზე დაბალ წერტილს მიღწევა"],
  ["level out at", "გასწორება გარკვეულ დონეზე"],
  ["sharply", "მკვეთრად"],
  ["dramatically", "დრამატულად, მკვეთრად"],
  ["rapidly", "სწრაფად"],
  ["steeply", "ციცაბოდ, მკვეთრად"],
  ["suddenly", "მოულოდნელად"],
  ["significantly", "მნიშვნელოვნად"],
  ["considerably", "საგრძნობლად"],
  ["markedly", "შესამჩნევად"],
  ["steadily", "თანდათანობით, სტაბილურად"],
  ["gradually", "ეტაპობრივად"],
  ["slightly", "ოდნავ"],
  ["slowly", "ნელა"],
  ["moderately", "ზომიერად"],
  ["marginally", "უმნიშვნელოდ"],
  ["initially", "საწყისად"],
  ["subsequently", "შემდგომში"],
  ["thereafter", "შემდეგომ"],
  ["throughout", "მთელი პერიოდის განმავლობაში"],
  ["over the period", "პერიოდის განმავლობაში"],
  ["by the end of", "-ის ბოლოსთვის"],
  ["from X to Y", "X-დან Y-მდე"],
  ["exceed", "გადააჭარბება"],
  ["surpass", "აღემატება"],
  ["outnumber", "რაოდენობით აღემატება"],
  ["outperform", "აღემატება (მაჩვენებლით)"],
  ["overtake", "გასწრება"],
  ["lag behind", "ჩამორჩენა, უფრო ნელა"],
  ["fall behind", "ჩამორჩენა"],
  ["dominate", "დომინირება"],
  ["highest", "ყველაზე მაღალი"],
  ["lowest", "ყველაზე დაბალი"],
  ["largest", "ყველაზე დიდი"],
  ["smallest", "ყველაზე პატარა"],
  ["second-highest", "მეორე ყველაზე მაღალი"],
  ["top", "საუკეთესო, ყველაზე მაღალი"],
  ["leading", "წამყვანი"],
  ["minimal", "მინიმალური"],
  ["negligible", "უმნიშვნელო"],
  ["gap", "სხვაობა, უფსკრული"],
  ["margin", "სხვაობის ზღვარი"],
  ["difference", "განსხვავება"],
  ["disparity", "დისბალანსი, უთანასწორობა"],
  ["the majority", "უმეტესობა"],
  ["the minority", "უმცირესობა"],
  ["a small fraction", "მცირე ნაწილი"],
  ["a significant proportion", "მნიშვნელოვანი წილი"],
  ["roughly equal", "დაახლოებით თანაბარი"],
  ["comparable", "შესადარებელი"],
  ["substantially", "არსებითად"],
  ["by far", "დიდი მანძილით"],
  ["by a small margin", "მცირე სხვაობით"],
  ["category", "კატეგორია"],
  ["figure", "მაჩვენებელი, ციფრი"],
  ["value", "მნიშვნელობა, ღირებულება"],
  ["proportion", "წილი, პროპორცია"],
  ["share", "წილი"],
  ["far exceed", "მნიშვნელოვნად აჭარბებს"],
  ["well above", "მნიშვნელოვნად მაღლა"],
  ["well below", "მნიშვნელოვნად დაბლა"],
  ["on par with", "თანაბარ დონეზე"],
  ["roughly the same as", "დაახლოებით იგივეა, რაც"],
  ["greatest", "ყველაზე დიდი, დიდებული"],
  ["equivalent", "ეკვივალენტური"],
  ["identical", "იდენტური"],
  ["unchanged", "უცვლელი"],
  ["remain stable", "სტაბილურად დარჩენა"],
  ["double", "გაორმაგება"],
  ["triple", "გასამმაგება"],
  ["halve", "განახევრება"],
  ["statistic", "სტატისტიკა"],
  ["rate", "მაჩვენებელი, კოეფიციენტი"],
  ["ratio", "თანაფარდობა"],
  ["total", "ჯამი, სულ"],
  ["sum", "ჯამი"],
  ["average", "საშუალო"],
  ["mean", "საშუალო არითმეტიკული"],
  ["exactly", "ზუსტად"],
  ["precisely", "ზედმიწევნით"],
  ["respectively", "სათანადო თანმიმდევრობით"],
  ["no data is available for", "მონაცემები არ არის ხელმისაწვდომი -სთვის"],
  ["figures were not recorded for", "მაჩვენებლები არ დაფიქსირდა -სთვის"],
  ["whereas", "მაშინ როცა"],
  ["while", "მაშინ როცა, ხოლო"],
  ["in contrast", "განსხვავებით, საპირისპიროდ"],
  ["on the other hand", "მეორე მხრივ"],
  ["conversely", "პირიქით"],
  ["unlike", "განსხვავებით"],
  ["similarly", "ანალოგიურად"],
  ["likewise", "ასევე, იმავე გზით"],
  ["in the same way", "იმავე გზით"],
  ["both...and...", "როგორც... ისე..."],
  ["correspondingly", "შესაბამისად"],
  ["than", "ვიდრე"],
  ["as...as", "ისეთივე... როგორც"],
  ["twice as high as", "ორჯერ მაღალი, ვიდრე"],
  ["three times the amount of", "სამჯერ მეტი, ვიდრე"],
  ["half as much as", "ნახევარი, რაც"],
  ["correlate with", "კორელაციაშია"],
  ["mirror", "იმეორებს, ასახავს"],
  ["coincide with", "ემთხვევა"],
  ["diverge", "განსხვავდება, დაცილება"],
  ["converge", "ერთმანეთს უახლოვდება"],
  ["intersect", "იკვეთება"],
  ["cross over", "გადაკვეთა"],
  ["proportionally", "პროპორციულად"],
  ["relatively", "შედარებით, მეტ-ნაკლებად"],
  ["comparatively", "შედარებით"],
  ["contrast with", "საპირისპიროა, კონტრასტშია"],
  ["differ from", "განსხვავდება"],
  ["correspond to", "შეესაბამება"],
  ["be transformed into", "გარდაიქმნა -ად"],
  ["be converted into", "გადაკეთდა -ად"],
  ["be replaced by", "შეიცვალა -ით"],
  ["be demolished", "დაინგრა, დაანგრიეს"],
  ["be knocked down", "დაანგრიეს"],
  ["be constructed", "აიგო"],
  ["be built", "აშენდა"],
  ["be established", "დაარსდა"],
  ["be expanded", "გაფართოვდა"],
  ["be extended", "გაგრძელდა"],
  ["be widened", "გაფართოვდა (გზა)"],
  ["be relocated", "გადაადგილდა"],
  ["be redeveloped", "ხელახლა განვითარდა"],
  ["be renovated", "განახლდა"],
  ["be modernized", "მოდერნიზდა"],
  ["be removed", "მოიხსნა, ამოიღეს"],
  ["disappear", "გაქრა"],
  ["newly built", "ახლადაშენებული"],
  ["no longer exists", "აღარ არსებობს"],
  ["north", "ჩრდილოეთი"],
  ["south", "სამხრეთი"],
  ["east", "აღმოსავლეთი"],
  ["west", "დასავლეთი"],
  ["adjacent to", "მიმდებარედ"],
  ["next to", "გვერდით"],
  ["opposite", "საპირისპიროდ"],
  ["bordering", "საზღვართან"],
  ["in the vicinity of", "-ის სიახლოვეს"],
  ["on the outskirts of", "-ის გარეუბანში"],
  ["in the centre of", "-ის ცენტრში"],
  ["surrounding", "მიმდებარე"],
  ["situated", "მდებარეობს"],
  ["residential", "საცხოვრებელი"],
  ["commercial", "კომერციული"],
  ["agricultural", "სასოფლო-სამეურნეო"],
  ["industrial area", "სამრეწველო ზონა"],
  ["previously", "წინათ"],
  ["formerly", "ადრე"],
  ["originally", "თავდაპირველად, ორიგინალში"],
  ["currently", "ამჟამად"],
  ["now", "ახლა"],
  ["by [year]", "[წლისთვის]"],
  ["firstly", "პირველ რიგში"],
  ["at the outset", "დასაწყისში"],
  ["to begin with", "დასაწყისისთვის"],
  ["next", "შემდეგი"],
  ["then", "შემდეგ"],
  ["after that", "ამის შემდეგ"],
  ["following this", "ამას მოჰყვება"],
  ["meanwhile", "ამასობაში"],
  ["simultaneously", "ერთდროულად"],
  ["at the same time", "იმავდროულად"],
  ["finally", "საბოლოოდ"],
  ["lastly", "და ბოლოს"],
  ["at the final stage", "საბოლოო ეტაპზე"],
  ["be heated", "თბება"],
  ["be cooled", "გაცივდება"],
  ["be mixed", "ირევა"],
  ["be combined", "ერწყმის"],
  ["be added", "ემატება"],
  ["be poured", "ისხმება"],
  ["be filtered", "იფილტრება"],
  ["be extracted", "მოიპოვება"],
  ["be processed", "მუშავდება, პროცესს გადის"],
  ["be transported", "გადაიტანება"],
  ["be transferred", "გადადის"],
  ["be packaged", "იფუთება"],
  ["be stored", "ინახება"],
  ["be released", "გამოიყოფა"],
  ["be produced", "იწარმოება"],
  ["undergoes", "განიცდის"],
  ["be sorted", "სორტირდება"],
  ["be treated", "მუშავდება"],
  ["be dried", "შრება"],
  ["be crushed", "ილექება, იმტვრევა"],
  ["be refined", "იხვეწება"],
  ["the cycle repeats", "ციკლი მეორდება"],
  ["the process starts again", "პროცესი ხელახლა იწყება"],
  ["be recycled", "გადამუშავდება"],
  ["returns to", "უბრუნდება"],
  ["as a result", "შედეგად"],
  ["once this is done", "ამის დასრულების შემდეგ"],
  ["after which", "რის შემდეგაც"],
  ["before", "მანამდე"],
  ["prior to", "-მდე"],
  ["upon completion", "დასრულების შემდეგ"],
  ["output", "საბოლოო შედეგი"],
  ["by-product", "ქვეპროდუქტი"],
  ["end product", "საბოლოო პროდუქტი"],
  ["raw material", "ნედლეული"],
  ["make up", "შეადგენენ"],
  ["account for", "აღრიცხვაზე არიან"],
  ["constitute", "წარმოადგენენ"],
  ["comprise", "მოიცავს"],
];
