const task_1 = [
  ["rise", "მატება, ზრდა"],
  ["increase", "გაზრდა, მომატება"],
  ["grow", "ზრდა"],
  ["climb", "ტემპერატურის/მაჩვენებლის აწევა"],
  ["surge", "მკვეთრი მოზღვავება"],
  ["soar", "მკვეთრად აწევა, ზეაფრენა"],
  ["rocket", "სწრაფად აწევა (რაკეტასავით)"],
  ["jump", "ნახტომისებური ზრდა"],
  ["escalate", "თანდათანობითი ესკალაცია"],
  ["shoot up", "მკვეთრად აწევა"],
  ["spike", "მოკლევადიანი მკვეთრი მატება"],
  ["fall", "დაცემა, შემცირება"],
  ["decrease", "შემცირება"],
  ["decline", "კლება"],
  ["drop", "ვარდნა"],
  ["plunge", "მკვეთრი ვარდნა"],
  ["plummet", "თავზარდამცემი ვარდნა"],
  ["dip", "მცირე, მოკლევადიანი ვარდნა"],
  ["slump", "მკვეთრი ვარდნა (ეკონომიკური)"],
  ["tumble", "სწრაფი ვარდნა"],
  ["sink", "ჩაძირვა, დაცემა"],
  ["slide", "თანდათანობითი ვარდნა"],
  ["stabilize", "სტაბილიზაცია"],
  ["level off", "გასწორება, სტაბილურ დონეზე გამოსვლა"],
  ["plateau", "პლატო, უცვლელი დონე"],
  ["remain steady", "თანაბრად დარჩენა"],
  ["remain constant", "მუდმივად დარჩენა"],
  ["stagnate", "სტაგნაცია, გაჩერება"],
  ["flatten out", "გასწორება, გათანაბრება"],
  ["fluctuate", "რყევა, მერყეობა"],
  ["vary", "ცვალებადობა"],
  ["oscillate", "ბაგირისებური რყევა"],
  ["see-saw", "ზევით-ქვევით რყევა"],
  ["peak", "მწვერვალი, პიკი"],
  ["hit a high of", "მაქსიმუმს მიღწევა"],
  ["reach a low of", "მინიმუმს მიღწევა"],
  ["bottom out", "ფსკერზე დაბრუნება, ყველაზე დაბალ წერტილს მიღწევა"],
  ["level out at", "გასწორება გარკვეულ დონეზე"],
  ["sharply", "მკვეთრად"],
  ["dramatically", "დრამატულად, მკვეთრად"],
  ["rapidly", "სწრაფად"],
  ["steeply", "ციცაბოდ, მკვეთრად"],
  ["suddenly", "მოულოდნელად"],
  ["significantly", "მნიშვნელოვნად"],
  ["considerably", "საგრძნობლად"],
  ["markedly", "შესამჩნევად"],
  ["steadily", "თანდათანობით, სტაბილურად"],
  ["gradually", "ეტაპობრივად"],
  ["slightly", "ოდნავ"],
  ["slowly", "ნელა"],
  ["moderately", "ზომიერად"],
  ["marginally", "უმნიშვნელოდ"],
  ["initially", "საწყისად"],
  ["subsequently", "შემდგომში"],
  ["thereafter", "შემდეგომ"],
  ["throughout", "მთელი პერიოდის განმავლობაში"],
  ["over the period", "პერიოდის განმავლობაში"],
  ["by the end of", "-ის ბოლოსთვის"],
  ["from X to Y", "X-დან Y-მდე"],
  ["exceed", "გადააჭარბება"],
  ["surpass", "აღემატება"],
  ["outnumber", "რაოდენობით აღემატება"],
  ["outperform", "აღემატება (მაჩვენებლით)"],
  ["overtake", "გასწრება"],
  ["lag behind", "ჩამორჩენა, უფრო ნელა"],
  ["fall behind", "ჩამორჩენა"],
  ["dominate", "დომინირება"],
  ["highest", "ყველაზე მაღალი"],
  ["lowest", "ყველაზე დაბალი"],
  ["largest", "ყველაზე დიდი"],
  ["smallest", "ყველაზე პატარა"],
  ["second-highest", "მეორე ყველაზე მაღალი"],
  ["top", "საუკეთესო, ყველაზე მაღალი"],
  ["leading", "წამყვანი"],
  ["minimal", "მინიმალური"],
  ["negligible", "უმნიშვნელო"],
  ["gap", "სხვაობა, უფსკრული"],
  ["margin", "სხვაობის ზღვარი"],
  ["difference", "განსხვავება"],
  ["disparity", "დისბალანსი, უთანასწორობა"],
  ["the majority", "უმეტესობა"],
  ["the minority", "უმცირესობა"],
  ["a small fraction", "მცირე ნაწილი"],
  ["a significant proportion", "მნიშვნელოვანი წილი"],
  ["roughly equal", "დაახლოებით თანაბარი"],
  ["comparable", "შესადარებელი"],
  ["substantially", "არსებითად"],
  ["by far", "დიდი მანძილით"],
  ["by a small margin", "მცირე სხვაობით"],
  ["category", "კატეგორია"],
  ["figure", "მაჩვენებელი, ციფრი"],
  ["value", "მნიშვნელობა, ღირებულება"],
  ["proportion", "წილი, პროპორცია"],
  ["share", "წილი"],
  ["far exceed", "მნიშვნელოვნად აჭარბებს"],
  ["well above", "მნიშვნელოვნად მაღლა"],
  ["well below", "მნიშვნელოვნად დაბლა"],
  ["on par with", "თანაბარ დონეზე"],
  ["roughly the same as", "დაახლოებით იგივეა, რაც"],
  ["greatest", "ყველაზე დიდი, დიდებული"],
  ["equivalent", "ეკვივალენტური"],
  ["identical", "იდენტური"],
  ["unchanged", "უცვლელი"],
  ["remain stable", "სტაბილურად დარჩენა"],
  ["double", "გაორმაგება"],
  ["triple", "გასამმაგება"],
  ["halve", "განახევრება"],
  ["statistic", "სტატისტიკა"],
  ["rate", "მაჩვენებელი, კოეფიციენტი"],
  ["ratio", "თანაფარდობა"],
  ["total", "ჯამი, სულ"],
  ["sum", "ჯამი"],
  ["average", "საშუალო"],
  ["mean", "საშუალო არითმეტიკული"],
  ["exactly", "ზუსტად"],
  ["precisely", "ზედმიწევნით"],
  ["respectively", "სათანადო თანმიმდევრობით"],
  ["no data is available for", "მონაცემები არ არის ხელმისაწვდომი -სთვის"],
  ["figures were not recorded for", "მაჩვენებლები არ დაფიქსირდა -სთვის"],
  ["whereas", "მაშინ როცა"],
  ["while", "მაშინ როცა, ხოლო"],
  ["in contrast", "განსხვავებით, საპირისპიროდ"],
  ["on the other hand", "მეორე მხრივ"],
  ["conversely", "პირიქით"],
  ["unlike", "განსხვავებით"],
  ["similarly", "ანალოგიურად"],
  ["likewise", "ასევე, იმავე გზით"],
  ["in the same way", "იმავე გზით"],
  ["both...and...", "როგორც... ისე..."],
  ["correspondingly", "შესაბამისად"],
  ["than", "ვიდრე"],
  ["as...as", "ისეთივე... როგორც"],
  ["twice as high as", "ორჯერ მაღალი, ვიდრე"],
  ["three times the amount of", "სამჯერ მეტი, ვიდრე"],
  ["half as much as", "ნახევარი, რაც"],
  ["correlate with", "კორელაციაშია"],
  ["mirror", "იმეორებს, ასახავს"],
  ["coincide with", "ემთხვევა"],
  ["diverge", "განსხვავდება, დაცილება"],
  ["converge", "ერთმანეთს უახლოვდება"],
  ["intersect", "იკვეთება"],
  ["cross over", "გადაკვეთა"],
  ["proportionally", "პროპორციულად"],
  ["relatively", "შედარებით, მეტ-ნაკლებად"],
  ["comparatively", "შედარებით"],
  ["contrast with", "საპირისპიროა, კონტრასტშია"],
  ["differ from", "განსხვავდება"],
  ["correspond to", "შეესაბამება"],
  ["be transformed into", "გარდაიქმნა -ად"],
  ["be converted into", "გადაკეთდა -ად"],
  ["be replaced by", "შეიცვალა -ით"],
  ["be demolished", "დაინგრა, დაანგრიეს"],
  ["be knocked down", "დაანგრიეს"],
  ["be constructed", "აიგო"],
  ["be built", "აშენდა"],
  ["be established", "დაარსდა"],
  ["be expanded", "გაფართოვდა"],
  ["be extended", "გაგრძელდა"],
  ["be widened", "გაფართოვდა (გზა)"],
  ["be relocated", "გადაადგილდა"],
  ["be redeveloped", "ხელახლა განვითარდა"],
  ["be renovated", "განახლდა"],
  ["be modernized", "მოდერნიზდა"],
  ["be removed", "მოიხსნა, ამოიღეს"],
  ["disappear", "გაქრა"],
  ["newly built", "ახლადაშენებული"],
  ["no longer exists", "აღარ არსებობს"],
  ["north", "ჩრდილოეთი"],
  ["south", "სამხრეთი"],
  ["east", "აღმოსავლეთი"],
  ["west", "დასავლეთი"],
  ["adjacent to", "მიმდებარედ"],
  ["next to", "გვერდით"],
  ["opposite", "საპირისპიროდ"],
  ["bordering", "საზღვართან"],
  ["in the vicinity of", "-ის სიახლოვეს"],
  ["on the outskirts of", "-ის გარეუბანში"],
  ["in the centre of", "-ის ცენტრში"],
  ["surrounding", "მიმდებარე"],
  ["situated", "მდებარეობს"],
  ["residential", "საცხოვრებელი"],
  ["commercial", "კომერციული"],
  ["agricultural", "სასოფლო-სამეურნეო"],
  ["industrial area", "სამრეწველო ზონა"],
  ["previously", "წინათ"],
  ["formerly", "ადრე"],
  ["originally", "თავდაპირველად, ორიგინალში"],
  ["currently", "ამჟამად"],
  ["now", "ახლა"],
  ["by [year]", "[წლისთვის]"],
  ["firstly", "პირველ რიგში"],
  ["at the outset", "დასაწყისში"],
  ["to begin with", "დასაწყისისთვის"],
  ["next", "შემდეგი"],
  ["then", "შემდეგ"],
  ["after that", "ამის შემდეგ"],
  ["following this", "ამას მოჰყვება"],
  ["meanwhile", "ამასობაში"],
  ["simultaneously", "ერთდროულად"],
  ["at the same time", "იმავდროულად"],
  ["finally", "საბოლოოდ"],
  ["lastly", "და ბოლოს"],
  ["at the final stage", "საბოლოო ეტაპზე"],
  ["be heated", "თბება"],
  ["be cooled", "გაცივდება"],
  ["be mixed", "ირევა"],
  ["be combined", "ერწყმის"],
  ["be added", "ემატება"],
  ["be poured", "ისხმება"],
  ["be filtered", "იფილტრება"],
  ["be extracted", "მოიპოვება"],
  ["be processed", "მუშავდება, პროცესს გადის"],
  ["be transported", "გადაიტანება"],
  ["be transferred", "გადადის"],
  ["be packaged", "იფუთება"],
  ["be stored", "ინახება"],
  ["be released", "გამოიყოფა"],
  ["be produced", "იწარმოება"],
  ["undergoes", "განიცდის"],
  ["be sorted", "სორტირდება"],
  ["be treated", "მუშავდება"],
  ["be dried", "შრება"],
  ["be crushed", "ილექება, იმტვრევა"],
  ["be refined", "იხვეწება"],
  ["the cycle repeats", "ციკლი მეორდება"],
  ["the process starts again", "პროცესი ხელახლა იწყება"],
  ["be recycled", "გადამუშავდება"],
  ["returns to", "უბრუნდება"],
  ["as a result", "შედეგად"],
  ["once this is done", "ამის დასრულების შემდეგ"],
  ["after which", "რის შემდეგაც"],
  ["before", "მანამდე"],
  ["prior to", "-მდე"],
  ["upon completion", "დასრულების შემდეგ"],
  ["output", "საბოლოო შედეგი"],
  ["by-product", "ქვეპროდუქტი"],
  ["end product", "საბოლოო პროდუქტი"],
  ["raw material", "ნედლეული"],
  ["make up", "შეადგენენ"],
  ["account for", "აღრიცხვაზე არიან"],
  ["constitute", "წარმოადგენენ"],
  ["comprise", "მოიცავს"],
  ["modest", "მოკრძალებული"],
  ["considerable", "მნიშვნელოვანი"],
  ["variation", "ცვალებადობა"],
  ["growth", "ზრდა"],
  ["fluctuation", "მერყეობა"],
  ["go down/up", "დაწევა/აწევა"],
  ["nearly three quarters", "73%"],
  ["just over a half", "51%"],
  ["just under a half", "49%"],
  ["nearly a third", "32%"],
  ["a tiny fraction", "3%"],
  ["exactly a half", "50%"],
  ["roughly one quarter", "26%"],
  ["almost a quarter", "24%"],
  ["approximately three quarters", "77%"],
  ["a large proportion", "70% p"],
  ["a significant majority", "71% p"],
  ["a small minority", "15% p"],
  ["an insignificant minority", "3% p"],
  ["edge up", "მცირედით გაზრდა"],
  ["edge down", "მცირედით შემცირება"],
];

const task_2 = [
  ["It is often argued that...", "ხშირად ამტკიცებენ, რომ..."],
  [
    "In recent years, ... has become a controversial/widely discussed issue.",
    "ბოლო წლებში, ... საკამათო/ფართოდ განსახილველ საკითხად იქცა.",
  ],
  ["There is no doubt that...", "უდავოა, რომ..."],
  [
    "This essay will discuss both views and give my own opinion.",
    "წინამდებარე ესსეში განვიხილავ ორივე მოსაზრებას და წარმოვადგენ საკუთარ თვალსაზრისს.",
  ],
  [
    "This essay will examine both sides of the argument before reaching a conclusion.",
    "ეს ესსე განიხილავს დისკუსიის ორივე მხარეს, სანამ დასკვნას გამოვიტანთ.",
  ],
  [
    "While some people believe..., others argue that...",
    "მიუხედავად იმისა, რომ ზოგიერთი თვლის, რომ..., სხვები ამტკიცებენ, რომ...",
  ],
  ["In my opinion, ...", "ჩემი აზრით, ..."],
  ["I strongly believe that...", "მტკიცედ მჯერა, რომ..."],
  ["From my point of view, ...", "ჩემი თვალსაზრისით, ..."],
  ["As far as I am concerned, ...", "რაც შემეხება მე, ..."],
  ["I am inclined to agree that...", "მიდრეკილი ვარ დავეთანხმო, რომ..."],
  ["It seems to me that...", "მე მგონია, რომ..."],
  [
    "This is mainly due to the fact that...",
    "ეს ძირითადად გამოწვეულია იმით, რომ...",
  ],
  ["As a result, ...", "შედეგად, ..."],
  ["This leads to...", "ეს იწვევს..."],
  ["Consequently, ...", "შესაბამისად, ..."],
  ["This can be attributed to...", "ეს შეიძლება მიეწეროს..."],
  [
    "One of the main reasons for this is...",
    "ამის ერთ-ერთი მთავარი მიზეზი არის...",
  ],
  ["Therefore, ...", "ამიტომ, ..."],
  ["Furthermore, ...", "გარდა ამისა, ..."],
  ["In addition, ...", "დამატებით, ..."],
  ["Moreover, ...", "უფრო მეტიც, ..."],
  ["Not only..., but also...", "არა მხოლოდ..., არამედ ასევე..."],
  ["Besides, ...", "გარდა ამისა, ..."],
  [
    "Another point worth noting is that...",
    "კიდევ ერთი მნიშვნელოვანი საკითხია ის, რომ...",
  ],
  ["On the other hand, ...", "მეორე მხრივ, ..."],
  ["However, ...", "თუმცა, ..."],
  ["Despite this, ...", "ამის მიუხედავად, ..."],
  ["Although/Even though...", "მიუხედავად იმისა, რომ.../თუმცა..."],
  ["Nevertheless, ...", "მიუხედავად ამისა, ..."],
  [
    "While it is true that..., it is also important to consider...",
    "მართალია, რომ..., მაგრამ ასევე მნიშვნელოვანია გავითვალისწინოთ...",
  ],
  ["In contrast, ...", "საპირისპიროდ, ..."],
  ["Whereas...", "მაშინ როცა..."],
  ["For example, / For instance, ...", "მაგალითად, ..."],
  ["A good example of this is...", "ამის კარგი მაგალითია..."],
  ["This is evident/illustrated in...", "ეს კარგად ჩანს/ილუსტრირებულია..."],
  ["To illustrate this point, ...", "ამ საკითხის საილუსტრაციოდ, ..."],
  ["Such as / like...", "როგორიცაა..."],
  ["Compared to..., ...", "შედარებით ..., ..."],
  ["Similarly, ...", "ანალოგიურად, ..."],
  ["In the same way, ...", "იმავე გზით, ..."],
  ["Unlike..., ...", "განსხვავებით ...-ისგან, ..."],
  [
    "One major advantage of this is...",
    "ამის ერთ-ერთი მთავარი უპირატესობა არის...",
  ],
  ["The main benefit of... is...", "...ის ძირითადი სარგებელი არის..."],
  [
    "A drawback/disadvantage of this is that...",
    "ამის ნაკლი/მინუსი არის ის, რომ...",
  ],
  [
    "This has both positive and negative effects.",
    "ამას აქვს როგორც დადებითი, ისე უარყოფითი შედეგები.",
  ],
  [
    "The benefits of ... far outweigh the drawbacks.",
    "...-ის სარგებელი მნიშვნელოვნად აღემატება მის ნაკლოვანებებს.",
  ],
  ["The downside of this is...", "ამის უარყოფითი მხარეა..."],
  ["It could be argued that...", "შეიძლება ითქვას, რომ..."],
  ["It is likely that...", "სავარაუდოა, რომ..."],
  ["To some extent, ...", "გარკვეულწილად, ..."],
  ["This may/might lead to...", "ამან შესაძლოა გამოიწვიოს..."],
  ["Arguably, ...", "შესაძლოა ითქვას, რომ..."],
  ["It is crucial/essential that...", "გადამწყვეტი/აუცილებელია, რომ..."],
  ["What is more important is...", "რაც უფრო მნიშვნელოვანია, არის ის, რომ..."],
  ["It cannot be denied that...", "არ შეიძლება უარვყოთ, რომ..."],
  ["Above all, ...", "უპირველეს ყოვლისა, ..."],
  [
    "One possible/effective solution would be to...",
    "ერთ-ერთი შესაძლო/ეფექტური გამოსავალი იქნება...",
  ],
  [
    "This problem could be addressed/solved by...",
    "ეს პრობლემა შეიძლება მოგვარდეს...",
  ],
  [
    "Governments/Individuals should take steps to...",
    "მთავრობებმა/ინდივიდებმა უნდა გადადგან ნაბიჯები, რათა...",
  ],
  [
    "A possible way to tackle this issue is to...",
    "ამ პრობლემის მოგვარების ერთ-ერთი გზა არის...",
  ],
  ["In conclusion, ...", "დასკვნის სახით, ..."],
  ["To sum up, ...", "შეჯამებისთვის, ..."],
  ["Overall, ...", "საერთო ჯამში, ..."],
  ["Taking everything into account, ...", "ყველაფრის გათვალისწინებით, ..."],
  ["In light of the above, ...", "ზემოთქმულის გათვალისწინებით, ..."],
];

const english_graph = [
  ...task_1,
  // ...task_2
];
