const spanish_a2_1 = [
  [`morado`, `purple (masc.)`],
  [`fantástico`, `great, fantastic (masc.)`],
  [`odiar`, `to hate, to loathe`],
  [`acostarse`, `to go to bed, go to bed, lie down`],
  [`allí`, `there`],
  [`me acuesto`, `(I) go to bed`],
  [`nos acostamos`, `(we) go to bed, (we) went to bed`],
  [`gustaron`, `liked them`],
  [`cuando`, `when (not question)`],
  [`preferimos`, `(we) preferred`],
  [`el gimnasio`, `the gym`],
  [`de vez en cuando`, `every once in a while, once in a while, now and then`],
  [`generalmente`, `generally, usually`],
  [`el golf`, `the golf`],
  [`el ajedrez`, `the chess`],
  [`frecuentemente`, `frequently, often`],
  [`dificilísimo`, `really difficult (masc.)`],
  [`facilísimo`, `really easy (masc.)`],
  [`grandísimo`, `really big, very big, really large (masc.)`],
  [`encantó`, `loved it`],
  [`encantaron`, `loved them`],
  [`cansadísimo`, `really tired (masc.)`],
  [`el proyecto`, `the project`],
  [`jamás`, `never, ever`],
  [`espera`, `(tú) wait! hopes`],
  [`tampoco`, `neither, either`],
  [`el colega`, `the pal, the colleague`],
  [`disponible`, `available`],
  [`escuche`, `(usted) listen!`],
  [`ayude`, `(usted) help!`],
  [`use`, `(usted) use!`],
  [`la reunión`, `the meeting`],
  [`pones`, `(you) put / place`],
  [`ve`, `(he/she/it) sees, (tú) see!, (tú) go!`],
  [`haz`, `(tú) make!, (tú) do!`],
  [`vas`, `(you) go`],
  [`haces`, `(you) do`],
  [`pon`, `(you) put!`],
  [`la empresa`, `the business, company`],
  [`ponga`, `(usted) put!`],
  [`haga`, `(usted) make/do!`],
  [`vaya`, `(usted) go!`],
  [`de niño`, `as a child (masc.)`],
  [`el vóleibol`, `the volleyball`],
  [`jugaba`, `(I / she) used to play / were playing`],
  [`de niña`, `as a child, when I was a girl, as a little girl (fem.)`],
  [`jugabas`, `(you) used to play / were playing`],
  [`montaba`, `(I / he) used to ride / was riding`],
  [`montabas`, `(you) used to ride / were riding`],
  [`el cereal`, `the cereal, the grain`],
  [`los bosques`, `the woods, woodland, forests`],
  [`la galleta`, `the cracker, biscuit, cookie`],
  [`vivías`, `(you) used to live, (?) did you use to live`],
  [`vivía`, `(she) lived, (I) used to live, live`],
  [`comía`, `(I/he/she/it) used to eat / was eating`],
  [`comías`, `(you) used to eat / were eating`],
  [`amable`, `kind, softer, nice`],
  [`el alumno`, `the student, the pupil`],
  [`tranquilo`, `calm, peaceful, quiet (masc.)`],
  [`nadaba`, `(I) used to swim, (I) was swimming, use to swim`],
  [`nadabas`, `(you) were swimming / used to swim`],
  [`era`, `(I/he/she/it) used to be / was`],
  [`eras`, `(you) used to be / were`],
  [`la patineta`, `the skateboard`],
  [`leías`, `(you) were reading, reading, (?) did you use to read`],
  [`tenías`, `(you) had, (you) used to have`],
  [`estudiabas`, `(you) were studying / used to study`],
  [`leía`, `(I) used to read, (she) was reading, (she) read`],
  [`tenía`, `(he) had, (he) used to have, have`],
  [`estudiaba`, `(I) was studying, trained, (I) used to study`],
  [`asado`, `baked, grilled, barbecue`],
  [`el champán`, `the champagne`],
  [`el chef`, `the chef`],
  [`pedir`, `to order, order, to ask for`],
  [`el alcohol`, `the alcohol`],
  [`servir`, `serving, to serve, serve`],
  [`estupendo`, `wonderful, great, beautiful (masc.)`],
  [`vegetariano`, `vegetarian (masc.)`],
  [`lleno`, `full, crowded, filled (masc.)`],
  [`saludable`, `healthy`],
  [`buen provecho`, `bon appétit, enjoy your meal`],
  [`el extra`, `the extra`],
  [`el hielo`, `the ice`],
  [`algo más`, `something more`],
  [`el especial del día`, `special of the day`],
  [`me puede traer`, `can you bring me`],
  [`pedimos`, `(we) order, asked, (we) ask (pl.)`],
  [`servimos`, `(we) serve, (we) served`],
  [`excelente`, `excellent, fine, great`],
  [`el aceite`, `the oil`],
  [`traer`, `to bring, to fetch`],
  [`los panes`, `the breads`],
  [`la excursión`, `the hiking, hike, outing`],
  [`qué hacemos`, `what do we do, what are we doing`],
  [`el cómic`, `the comic`],
  [`el teatro`, `the drama, the theater`],
  [`el descanso`, `the rest, the break`],
  [`el hip-hop`, `the hip-hop`],
  [`el lago`, `the lake`],
  [`el espectáculo`, `the show, performance`],
  [`la obra de teatro`, `the play`],
  [`el jazz`, `the jazz`],
  [`a lo mejor`, `maybe, at most`],
  [`qué tal si`, `how about, what if`],
  [`la motocicleta`, `the motorcycle`],
  [`el hobby`, `the hobby`],
  [`desafortunadamente`, `unfortunately, sadly`],
  [`la tradición`, `the tradition`],
  [`visitaba`, `(he) used to visit, (she) used to visit, (he) visited`],
  [`durante`, `during, for`],
  [`jugaban`, `(they) used to play / were playing`],
  [`visitaban`, `(they) used to visit / were visiting`],
  [`el día de acción de gracias`, `the Thanksgiving Day`],
  [`tenían`, `(they) used to have / had`],
  [`la nochevieja`, `the New Year's Eve`],
  [`vivían`, `(they) used to live / were living`],
  [`comían`, `(they) used to eat / were eating`],
  [`la tarjeta`, `the card, business card`],
  [`especial`, `special`],
  [`el juguete`, `the toy`],
  [`la navidad`, `the Christmas, Yule, Xmas`],
  [`eran`, `(they) were / used to be`],
  [`la nochebuena`, `the Christmas Eve`],
  [`la iglesia`, `the church`],
  [`jugábamos`, `(we) used to play / were playing`],
  [`éramos`, `(we) were / used to be`],
  [`el año nuevo`, `the New Year`],
  [`teníamos`, `(we) had, (we) used to have`],
  [`comíamos`, `(we) used to eat / were eating`],
  [`vivíamos`, `(we) used to live / were living`],
  [`la invitación`, `the invitation, invite`],
  [`qué te parece`, `What do you think, (?) How does it sound`],
  [`mira`, `(you) look!`],
  [`cómo te va`, `how's it going`],
  [`donde`, `where (not question)`],
  [`oye`, `(you) hear!, hey`],
  [`el centro`, `the center, focus`],
  [`la sorpresa`, `the surprise`],
  [`el patio`, `the backyard, yard`],
  [`genial`, `brilliant, cool, Great!`],
  [`qué le parece`, `(?) what does he think`],
  [`acompañar`, `go with, to go with, accompany`],
  [`cómo le va`, `how is it going (to him)`],
  [`el bar`, `the bar`],
  [`quiénes`, `who (pl.)`],
  [`ven`, `(they) are seeing / see`],
  [`parece`, `(?) does it seem, appears, look`],
  [`la pena`, `the shame, pity`],
  [`conversar`, `to converse, chat, converse`],
  [`la parrilla`, `the grill, grate, barbecue`],
  [`llegue`, `(usted) arrive!`],
  [`la medianoche`, `the midnight`],
  [`el mediodía`, `the noon, midday`],
  [`baila`, `(he) dances, dancing, dance`],
  [`llega`, `(he/she/it) arrives / reaches`],
  [`el primo`, `the cousin`],
  [`el compañero de cuarto`, `the roommate`],
  [`hace`, `(he/she/it) makes / does`],
  [`dije`, `said, (I) said, (I) told`],
  [`tuve`, `(I) had, got, have`],
  [`el traje`, `the suit, the costume`],
  [`la aventura`, `the adventure, affair`],
  [`el campamento`, `the campground, camping, camp`],
  [`cuento`, `(I) tell, (I) count, tale/story`],
  [`el momento`, `the moment, time, timing`],
  [`tuviste`, `(you) had, had, (?) did you have`],
  [`dijiste`, `(you) said`],
  [`trajiste`, `(you) brought`],
  [`el compañero de clase`, `the classmate`],
  [`el álbum`, `the album`],
  [`tuvo`, `(he) had`],
  [`el abuelito`, `the grandpa`],
  [`trajo`, `(he / she) brought`],
  [`recibir`, `receive, get, to get`],
  [`dijo`, `(he) said, (he) told, said`],
  [`el premio`, `the prize, award`],
  [`el diploma`, `the diploma, certificate, degree`],
  [`me acordé`, `(I) remembered`],
  [`el juego de mesa`, `the board game`],
  [`la luz`, `the light`],
  [`el portátil`, `the laptop, portable`],
  [`la lámpara`, `the lamp`],
  [`la cafetera`, `the coffee maker, coffee machine`],
  [`los muebles`, `the furnitures`],
  [`apagar`, `to turn off, turn off, switch off`],
  [`el televisor`, `the television, TV set`],
  [`apagado`, `off, turned off (masc.)`],
  [`el pintado`, `the painting`],
  [`la alfombra`, `the carpet, rug`],
  [`la estufa`, `the stove, heater`],
  [`el sillón`, `the armchair, chair`],
  [`la lavadora`, `the washing machine`],
  [`el espejo`, `the mirror`],
  [`encender`, `to turn on, turn on, switch on`],
  [`creo que deberías`, `I think you should`],
  [`el sofá`, `the sofa, couch, sofas`],
  [`perdido`, `lost, missing (masc.)`],
  [`dormido`, `fallen asleep, asleep, slept (masc.)`],
  [`encendido`, `turned on, on (masc.)`],
  [`creo que debería`, `I think I should`],
  [`encendemos`, `(we) turn on (pl.)`],
  [`el estómago`, `the stomach`],
  [`la espalda`, `the back, backs`],
  [`la cita`, `the appointment, date`],
  [`el cuello`, `the neck`],
  [`el dedo`, `the finger`],
  [`doler`, `to hurt, hurt, to be in pain`],
  [`mover`, `to move`],
  [`el enfermero`, `the male nurse`],
  [`me cepillé`, `(I) brushed`],
  [`el jabón`, `the soap`],
  [`descansar`, `rest, to rest`],
  [`el dolor`, `the pain, ache, grief`],
  [`hay que`, `one must, we've got to`],
  [`pálido`, `pale (masc.)`],
  [`el ejercicio`, `the exercise`],
  [`la salud`, `the health`],
  [`duele`, `(it) hurts`],
  [`cuidar`, `to care for, to take care`],
  [`deberías`, `(you) should`],
  [`el cigarrillo`, `the cigarette, cigarettes`],
  [`el accidente`, `the accident, crash`],
  [`el dentista`, `the dentist`],
  [`la actividad`, `the activity`],
  [`duelen`, `(they) hurt`],
  [`debería`, `(I/he) should`],
  [`semanal`, `weekly`],
  [`la noticia`, `the news`],
  [`el canal`, `the channel`],
  [`el internet`, `the Internet, online, web`],
  [`la verdad`, `the truth`],
  [`la información`, `the information, data`],
  [`el documento`, `the document, paper`],
  [`el archivo`, `attachment, file`],
  [`correcto`, `well-mannered, right, correct (masc.)`],
  [`tuvimos`, `(we) had`],
  [`trajimos`, `(we) brought (pl.)`],
  [`dijimos`, `(we) told, said, tell (pl.)`],
  [`la revista`, `the magazine, journal`],
  [`leí`, `(I) read`],
  [`dijeron`, `(they) said`],
  [`tuvieron`, `(they) had`],
  [`trajeron`, `(they) brought`],
  [`enviar`, `send, forward`],
  [`entiendes`, `(you) understand`],
  [`el ingeniero`, `the engineer, an engineer`],
  [`la máquina`, `the machine`],
  [`las fábricas`, `the factories, plants, mills`],
  [`el elefante`, `the elephant`],
  [`el conejo`, `the rabbit`],
  [`fuerte`, `strong, loud`],
  [`peligroso`, `dangerous (masc.)`],
  [`los perros`, `the dogs`],
  [`los gatos`, `the cats`],
  [`la verdura`, `the vegetable, verdure, green`],
  [`útil`, `useful, helpful`],
  [`los lunes`, `the mondays`],
  [`las frutas`, `the fruits`],
  [`los padres`, `the parents, fathers`],
  [`los médicos`, `the doctors`],
  [`pesado`, `heavy, annoying (masc.)`],
  [`el baloncesto`, `the basketball`],
  [`la gramática`, `the grammar`],
  [`el ciclismo`, `the cycling, bike racing, bicycle racing`],
  [`el fútbol`, `the soccer`],
  [`los deportes`, `the sports`],
  [`el dinosaurio`, `the dinosaur`],
  [`el oso`, `the bear`],
  [`el agricultor`, `the farmer`],
  [`el insecto`, `the insect`],
  [`los maestros`, `the teachers`],
  [`el español`, `the Spanish`],
  [`el inglés`, `the English, the English language, Englishman`],
  [`la copa`, `the glass, cup`],
  [`el tazón`, `the bowl, mug`],
  [`aprobar`, `to pass, approve, pass`],
  [`varios`, `several, some (masc. pl.)`],
  [`leíste`, `(you) read (past)`],
  [`leyeron`, `(they) read (past)`],
  [`leímos`, `(we) read (past)`],
  [`leyó`, `(he/she/it) read (past)`],
  [`el cuaderno`, `the notebook`],
  [`el libro de texto`, `the textbook`],
  [`la química`, `the chemistry`],
  [`la historia`, `the history, story`],
  [`ganar`, `to win, to beat, to gain`],
  [`tomé`, `(I) took, (I) drank`],
  [`el corredor`, `the runner, hallway`],
  [`el kilómetro`, `the kilometer`],
  [`la carrera`, `the degree, career, race`],
  [`el equipo`, `the gear, team, outfit`],
  [`el balonmano`, `the handball`],
  [`la geografía`, `the geography`],
  [`el mecánico`, `the mechanic`],
  [`ibas`, `(you) were going, used to go`],
  [`el refresco`, `the soda, pop`],
  [`el dibujo animado`, `the cartoon`],
  [`los dulces`, `the candies, sweet, sweets`],
  [`íbamos`, `(we) were going, (we) went out, we'd go (pl.)`],
  [`iban`, `(they) went, (they) used to go, going (pl.)`],
  [`el patio de juego`, `the playground`],
  [`el rey`, `the king`],
  [`el salón`, `the hall`],
  [`el castillo`, `the castle`],
  [`había una vez`, `once upon a time`],
  [`el violín`, `the violin`],
  [`el mar`, `the sea`],
  [`la montaña`, `the mountain, mountains, ranges`],
  [`la oveja`, `the sheep`],
  [`intentar`, `to try`],
  [`rezar`, `to pray`],
  [`la sortija`, `the ring`],
  [`el artista`, `the artist`],
  [`el campo`, `the field, country, countryside`],
  [`lentamente`, `slowly`],
  [`llorar`, `crying, to cry, cry`],
  [`la guerra`, `the wartime, war`],
  [`el bailarín`, `the dancer`],
  [`hasta`, `until, to, up until`],
  [`el turista`, `the tourist`],
  [`la isla`, `the island`],
  [`la idea`, `the idea, thought, clue`],
  [`bienvenido`, `welcome (masc.)`],
  [`la catedral`, `the cathedral`],
  [`planear`, `to plan`],
  [`reservar`, `to reserve, to book`],
  [`el pasajero`, `the passenger, temporary`],
  [`el estadio`, `the stadium`],
  [`el equipaje`, `the luggage, baggage`],
  [`la ópera`, `the opera house, opera`],
  [`la identificación`, `the ID, identification, id.`],
  [`el coche`, `the car, automobile`],
  [`el vuelo`, `the flight`],
  [`confortable`, `comfortable`],
  [`el tranvía`, `the tram`],
  [`el asiento`, `the chair, seat, seats`],
  [`internacional`, `international, internationally`],
  [`regresar`, `to return, to give back, to go/come back`],
  [`agradable`, `pleasant, nice, likable`],
  [`el helicóptero`, `the helicopter`],
  [`la capital`, `the capital city, capital`],
  [`los servicios`, `the restrooms`],
  [`en todas partes`, `everywhere, all over the place`],
  [`el nieto`, `the grandson, grandchild`],
  [`enfadado`, `angry, mad, annoyed (masc.)`],
  [`loco`, `crazy (masc.)`],
  [`interesado`, `interested, concerned (masc.)`],
  [`estábamos`, `(we) used to be / were`],
  [`sin duda`, `without doubt, certainly`],
  [`el invitado`, `the invited, guest`],
  [`el vecino`, `the neighbor, neighboring`],
  [`satisfecho`, `satisfied, pleased (masc.)`],
  [`casar`, `to marry`],
  [`excepto`, `except`],
  [`probablemente`, `probably, likely`],
  [`seco`, `dry (masc.), (I) dry`],
  [`el traje de baño`, `the swimsuit, swimsuits, bathing suit`],
  [`soleado`, `sunny, bright (masc.)`],
  [`mojado`, `wet (masc.)`],
  [`el paraguas`, `the umbrella, umbrellas, brolly`],
  [`romper`, `to break`],
  [`las gafas de sol`, `the sunglasses`],
  [`el cajón`, `the case, drawer`],
  [`el mango`, `the mango`],
  [`vacío`, `empty, vacuum (masc.)`],
  [`el motor`, `the engine`],
  [`fresco`, `cool, fresh (masc.)`],
  [`el tambor`, `the drum`],
  [`el océano`, `the ocean`],
  [`el mercado`, `the market`],
  [`entrar`, `to go in, to come in, to enter`],
  [`pescar`, `to fish`],
  [`el video`, `the video`],
  [`la limonada`, `the lemonade`],
  [`reparar`, `to fix, to repair, to fix`],
  [`la rata`, `the rat`],
  [`la cafetería`, `the cafeteria, coffee shop, cafe`],
  [`el tío`, `the uncle, guy/dude`],
  [`las ciencias`, `the sciences`],
  [`el mono`, `the monkey, cute`],
  [`la tía`, `the aunt`],
  [`asar`, `to roast, to grill`],
  [`el rugby`, `the rugby`],
  [`el gerente`, `the manager`],
  [`el horario`, `the schedule, timetable, hour`],
  [`la carpeta`, `the folder, binder`],
  [`adentro`, `inside, in, indoors`],
  [`diciendo`, `saying, telling`],
  [`pidiendo`, `asking, asking for`],
  [`el pintor`, `the painter, artist`],
  [`el trabajador`, `the worker, hardworking`],
  [`trayendo`, `getting, bringing`],
  [`oyendo`, `listening to, getting, hearing`],
  [`muriendo`, `dying`],
  [`yendo`, `going, leaving`],
  [`durmiendo`, `falling asleep, sleeping`],
  [`increíble`, `incredible, amazing`],
  [`el empresario`, `the businessman, entrepreneur`],
  [`el presidente`, `the president`],
  [`la compañía`, `the company`],
  [`el programa`, `the program`],
  [`completar`, `to complete, complete, to finish`],
  [`repetir`, `to repeat`],
  [`el cocinero`, `the cook`],
  [`el edificio`, `the building`],
  [`el director`, `the principal`],
  [`la llamada`, `the call, phone call`],
  [`afuera`, `outside, out, outdoors`],
  [`repitiendo`, `repeating`],
  [`la serpiente`, `the snake`],
  [`interesarse`, `to be interested, to take an interest, to concern oneself`],
  [`me llamaba`, `(he/she/it/you) was calling / used to call (me)`],
  [`la naturaleza`, `the nature`],
  [`creer`, `to believe, to think`],
  [`el corazón`, `the heart`],
  [`el desierto`, `the desert, deserted (masc.)`],
  [`el león`, `the lion`],
  [`el visitante`, `the visitor`],
  [`la miel`, `the honey`],
  [`propio`, `own`],
  [`el collar`, `the necklace`],
  [`la vista`, `the view, sight`],
  [`el oro`, `the gold`],
  [`simple`, `simple, simpleton, simple-minded`],
  [`el pato`, `the duck`],
  [`silvestre`, `wild (plant)`],
  [`la magia`, `the magic`],
  [`el puente`, `the bridge`],
  [`estar de acuerdo`, `be agreed`],
  [`el siglo`, `the century`],
  [`la razón`, `the reason, cause`],
  [`la vez`, `the time`],
  [`ocurrir`, `to occur, to happen`],
  [`supe`, `(I) knew, (I) found out`],
  [`pude`, `(I) was able to / could`],
  [`puse`, `(I) put, (I) placed`],
  [`la charla`, `the chat`],
  [`pudiste`, `(you) were able to / could`],
  [`supiste`, `(you) knew / found out`],
  [`pusiste`, `(you) put (past)`],
  [`el área`, `the area, region`],
  [`supo`, `know, (she) knew`],
  [`por fin`, `finally`],
  [`preparar`, `to prepare, to make`],
  [`pudo`, `(he) could, (she) was able to, could`],
  [`decidir`, `to decide`],
  [`puso`, `(he/she/it) put, placed`],
  [`prepararse`, `to get ready, to prepare oneself`],
  [`la colina`, `the hill`],
  [`el nacimiento`, `the birth`],
  [`el principio`, `the beginning, start`],
  [`miles`, `thousands (pl.)`],
  [`de acuerdo`, `agree`],
  [`me duché`, `(I) showered, (I) took a shower`],
  [`la mermelada`, `the jam, jelly`],
  [`la tostada`, `the toast, toasted`],
  [`me desperté`, `(I) woke up`],
  [`me lavé`, `(I) washed`],
  [`la pasta`, `the pasta`],
  [`almorcé`, `(I) ate lunch, (I) had lunch, eat lunch`],
  [`me preocupé`, `I worried, I became worried, I got worried`],
  [`el calcetín`, `the sock`],
  [`suave`, `soft, lit, gentle`],
  [`me reuní`, `I met`],
  [`me probé`, `I tried on`],
  [`vestirse`, `to get dressed`],
  [`la corbata`, `the tie`],
  [`la bufanda`, `the scarf`],
  [`me acosté`, `(I) went to bed, (I) lay down`],
  [`el peine`, `the comb`],
  [`el uniforme`, `the uniform`],
  [`el suéter`, `the sweater, pullover`],
  [`me quedé`, `(I) stayed, (I) remained`],
  [`el champú`, `the shampoo`],
  [`el maquillaje`, `the makeup`],
  [`dormiste`, `(you) slept`],
  [`durmieron`, `(they) slept`],
  [`durmió`, `(he/she/it) slept`],
  [`el yogur`, `the yogurt`],
  [`la cebolla`, `the onion`],
  [`la lata`, `the can`],
  [`el kilogramo`, `the kilogram`],
  [`el litro`, `the liter, liters`],
  [`el jamón`, `the ham`],
  [`en oferta`, `on discount`],
  [`la pimienta`, `the pepper`],
  [`y medio`, `and a half`],
  [`gastar`, `spending, spend, worn`],
  [`la lista`, `the list, ready/smart (fem.)`],
  [`la variedad`, `the variety`],
  [`el champiñón`, `the mushroom`],
  [`la pera`, `the pear`],
  [`la billetera`, `the wallet`],
  [`el limón`, `the lemon`],
  [`el estuche`, `the case, box, pencil case`],
  [`el compañero`, `the roommate, classmate`],
  [`avanzado`, `advanced, made progress (masc.)`],
  [`el detalle`, `the detail`],
  [`la regla`, `the ruler, rule, period`],
  [`los libros de ejercicios`, `the workbooks`],
  [`claramente`, `clearly`],
  [`la diferencia`, `the difference`],
  [`el consejo`, `the advice, tip`],
  [`la instrucción`, `the instruction`],
  [`decirme`, `to tell me`],
  [`darme`, `to give me`],
  [`el calendario`, `the calendar, scheduling`],
  [`la mochila`, `the backpack`],
  [`darte`, `give you`],
  [`explicar`, `to explain`],
  [`decirnos`, `to tell us, to say to us`],
  [`el nivel`, `the level, standards, floor`],
  [`darle`, `giving, to give him, give her`],
  [`expliqué`, `(I) explained`],
  [`decirles`, `to tell them`],
  [`maravilloso`, `marvelous, wonderful`],
  [`tanto`, `so much (masc.)`],
  [`la postal`, `the postcard`],
  [`a lo largo del`, `along, throughout the, along the`],
  [`el rompecabezas`, `the puzzle, jigsaw, jigsaw puzzle`],
  [`el bádminton`, `the badminton`],
  [`la raqueta`, `the racket, snowshoe, rake`],
  [`la cometa`, `the kite`],
  [`coleccionar`, `to collect`],
  [`esquiar`, `ski`],
  [`acampar`, `camping, camp`],
  [`el velero`, `the sailboat, sail`],
  [`la estampilla`, `the stamp`],
  [`navegar`, `surf, sailing, sail`],
  [`el hockey`, `the hockey`],
  [`prestar`, `to lend`],
  [`el dibujo`, `the drawing`],
  [`navegué`, `(I) sailed`],
  [`el pop`, `the pop`],
  [`has`, `you have (auxiliary)`],
  [`bastante`, `quite, enough, fairly`],
  [`estudiado`, `(have) studied`],
  [`estado`, `(have) been, condition`],
  [`trabajado`, `(have) worked`],
  [`he`, `I have (auxiliary)`],
  [`el peligro`, `the danger`],
  [`el obrero`, `the worker, laborer`],
  [`robar`, `to rob, to steal`],
  [`ha`, `has (auxiliary)`],
  [`aprendido`, `(have) learned/learnt`],
  [`comido`, `(have) eaten`],
  [`todavía`, `yet, still`],
  [`la policía`, `the police`],
  [`salvaje`, `brutal, wild, savage`],
  [`han`, `they have (auxiliary)`],
  [`vivido`, `(have) lived`],
  [`hemos`, `we have (auxiliary)`],
  [`ido`, `(have) gone`],
  [`recibido`, `(have) gotten`],
  [`terrible`, `terrible, horrible, desperate`],
  [`extraño`, `(I) miss, weird (masc.)`],
  [`nacional`, `national`],
  [`el fuego`, `the fire`],
  [`robado`, `(have) stolen / robbed`],
  [`llegado`, `(have) arrived`],
  [`la electricidad`, `the electricity`],
];

const spanish_a2_2 = [
  [`el actor`, `the actor (male)`],
  [`el/la recepcionista`, `the receptionist`],
  [`el cliente`, `the client / customer`],
  [`la actriz`, `the actress`],
  [`la ocupación`, `the occupation / profession`],
  [`pienso que deberías`, `I think you should (informal)`],
  [`el conductor`, `the driver (male)`],
  [`el teclado`, `the keyboard (computer or instrument)`],
  [`el departamento`, `the department / apartment`],
  [`la impresora`, `the printer (machine)`],
  [`descargar`, `to download`],
  [`el personal`, `the staff / personnel`],
  [`el limpiador`, `the cleaner (person or product)`],
  [`el pizarrón`, `the chalkboard / whiteboard`],
  [`el fotógrafo`, `the photographer (male)`],
  [`limpiando`, `cleaning (-ing form)`],
  [`copiar`, `to copy`],
  [`descargué`, `I downloaded (past tense)`],
  [`el piloto`, `the pilot (male)`],
  [`el/la cantante`, `the singer`],
  [`la madera`, `the wood (material)`],
  [`el correo`, `the mail / post office`],
  [`la física`, `the physics (science)`],
  [`el concejo municipal`, `the city council`],
  [`cómo quiere pagar`, `how do you want to pay? (formal)`],
  [`el cheque`, `the check (payment method)`],
  [`el perfume`, `the perfume / scent`],
  [`compren`, `buy! (plural command)`],
  [`trabajen`, `work! (plural command)`],
  [`me lo llevo`, `I'll take it (when buying something)`],
  [`el recibo`, `the receipt (proof of purchase)`],
  [`el vendedor`, `the salesman / seller`],
  [`beban`, `drink! (plural command)`],
  [`coman`, `eat! (plural command)`],
  [`el brazalete`, `the bracelet / wristband`],
  [`el arete`, `the earring`],
  [`deciden`, `they decide / you all decide (present tense)`],
  [`abran`, `open! (plural command)`],
  [`decidan`, `decide! (plural command)`],
  [`cuál quiere`, `which one do you want? (formal)`],
  [`el pijama`, `the pajamas`],
  [`hagan`, `do! / make! (plural command)`],
  [`gratis`, `free (of charge)`],
  [`hacen`, `they do / they make (present tense)`],
  [`vayan`, `go! (plural command)`],
];

const spanish_a2 = [...spanish_a2_1, ...spanish_a2_2];
