const spanish_numbers = [
  [`cero`, `0`],
  [`Uno`, `1`],
  [`Dos`, `2`],
  [`Tres`, `3`],
  [`Cuatro`, `4`],
  [`Cinco`, `5`],
  [`Seis`, `6`],
  [`Siete`, `7`],
  [`Ocho`, `8`],
  [`Nueve`, `9`],
  [`Diez`, `10`],
  [`Once`, `11`],
  [`Doce`, `12`],
  [`Trece`, `13`],
  [`Catorce`, `14`],
  [`Quince`, `15`],
  [`Dieciséis`, `16`],
  [`Diecisiete`, `17`],
  [`Dieciocho`, `18`],
  [`Diecinueve`, `19`],
  [`Veinte`, `20`],
  [`Veintiuno`, `21`],
  [`Veintidós`, `22`],
  [`Veintitrés`, `23`],
  [`Veinticuatro`, `24`],
  [`Veinticinco`, `25`],
  [`Veintiséis`, `26`],
  [`Veintisiete`, `27`],
  [`Veintiocho`, `28`],
  [`Veintinueve`, `29`],
  [`Treinta`, `30`],
  [`Treinta y uno`, `31`],
  [`Cuarenta`, `40`],
  [`Cuarenta y uno`, `41`],
  [`Cincuenta`, `50`],
  [`Cincuenta y uno`, `51`],
  [`Sesenta`, `60`],
  [`Sesenta y uno`, `61`],
  [`Setenta`, `70`],
  [`Setenta y uno`, `71`],
  [`Ochenta`, `80`],
  [`Ochenta y uno`, `81`],
  [`Noventa`, `90`],
  [`Noventa y uno`, `91`],
  [`Cien`, `100`],
  [`Ciento uno`, `101`],
  [`Doscientos`, `200`],
  [`Doscientos uno`, `201`],
  [`Trescientos`, `300`],
  [`Cuatrocientos`, `400`],
  [`Quinientos`, `500`],
  [`Seiscientos`, `600`],
  [`Setecientos`, `700`],
  [`Ochocientos`, `800`],
  [`Novecientos`, `900`],
  [`Mil`, `1000`],
  [`Mil novecientos`, `1900`],
  [`Mil novecientos noventa y uno`, `1991`],
  [`Dos mil`, `2000`],
  [`Dos mil uno`, `2001`],
  [`un millón`, `one million`],
  [`Primero`, `1st`],
  [`Segundo`, `2nd`],
  [`Tercero`, `3rd`],
  [`Cuarto`, `4th`],
  [`Quinto`, `5th`],
  [`Sexto`, `6th`],
  [`Séptimo`, `7th`],
  [`Octavo`, `8th`],
  [`Noveno`, `9th`],
  [`Décimo`, `10th`],
  [`la mitad`, `half (noun)`],
  [`medio`, `half (adjective, masc.)`],
  [`un tercio`, `a third`],
  [`un cuarto`, `a quarter`],
  [`un par`, `a pair, a couple`],
  [`el doble`, `double, twice as much`],
  [`por ciento`, `percent`],
];
