const spanish = [
  ["la mujer", "the woman, the wife"],
  ["el", "the (masculine article)"],
  ["un", "a (masculine), one"],
  ["la niña", "the girl (female child)"],
  ["la", "the (feminine article)"],
  ["yo", "I"],
  ["una", "a (feminine), one"],
  ["el hombre", "the man"],
  ["el niño", "the boy (male child)"],
  ["soy", "I am (permanent)"],
  ["la manzana", "the apple"],
  ["come", "he/she eats"],
  ["tú", "you (singular informal)"],
  ["él", "he"],
  ["eres", "you are (permanent, tú)"],
  ["ella", "she"],
  ["es", "he/she/it is"],
  ["comes", "you eat (tú)"],
  ["bebe", "he/she drinks"],
  ["el pan", "the bread"],
  ["la leche", "the milk"],
  ["bebo", "I drink"],
  ["como", "I eat"],
  ["el agua", "the water"],
  ["bebes", "you drink (tú)"],
  ["buenas noches", "good night"],
  ["hola", "hello"],
  ["gracias", "thank you"],
  ["buenos días", "good morning"],
  ["mucho gusto", "nice to meet you"],
  ["adiós", "goodbye"],
  ["lo siento", "I am sorry"],
  ["perdón", "sorry / excuse me"],
  ["de nada", "you are welcome"],
  ["por favor", "please"],
  ["sí", "yes"],
  ["no", "no"],
  ["el inglés", "the English language"],
  ["disculpe", "excuse me (formal)"],
  ["hablas", "you speak (tú)"],
  ["hablo", "I speak"],
  ["el español", "the Spanish language"],
  ["el taxi", "the taxi"],
  ["necesito", "I need"],
  ["el teléfono", "the phone"],
  ["mi", "my"],
  ["el pasaporte", "the passport"],
  ["la maleta", "the suitcase"],
  ["en", "in"],
  ["el hotel", "the hotel"],
  ["aquí", "here"],
  ["está", "it is (location/state)"],
  ["tengo", "I have"],
  ["la reserva", "the reservation"],
  ["dónde", "where"],
  ["el dinero", "the money"],
  ["a", "to"],
  ["el boleto", "the ticket"],
  ["el aeropuerto", "the airport"],
  ["el autobús", "the bus"],
  ["el tren", "the train"],
  ["tu", "your (tú)"],
  ["el museo", "the museum"],
  ["el hospital", "the hospital"],
  ["el baño", "the bathroom"],
  ["la calle", "the street"],
  ["el banco", "the bank"],
  ["cerrado", "closed"],
  ["el supermercado", "the supermarket"],
  ["tres", "three"],
  ["uno", "one"],
  ["el restaurante", "the restaurant"],
  ["la mesa", "the table"],
  ["las personas", "the people"],
  ["para", "for"],
  ["dos", "two"],
  ["la hamburguesa", "the hamburger"],
  ["el sándwich", "the sandwich"],
  ["con", "with"],
  ["de", "of / from"],
  ["el pescado", "the fish"],
  ["el queso", "the cheese"],
  ["la carne", "the meat"],
  ["el azúcar", "the sugar"],
  ["sin", "without"],
  ["el jugo", "the juice"],
  ["el vaso", "the glass"],
  ["el café", "the coffee"],
  ["la naranja", "the orange"],
  ["la taza", "the cup"],
  ["la sal", "the salt"],
  ["la cuenta", "the bill (restaurant)"],
  ["quiero", "I want"],
  ["el tomate", "the tomato"],
  ["la ensalada", "the salad"],
  ["pagar", "to pay"],
  ["o", "or"],
  ["la madre", "the mother"],
  ["inteligente", "intelligent"],
  ["tiene", "he/she has"],
  ["elegante", "elegant"],
  ["el padre", "the father"],
  ["el carro", "the car"],
  ["la casa", "the house"],
  ["grande", "big"],
  ["la hermana", "the sister"],
  ["el gato", "the cat"],
  ["muy", "very"],
  ["bonito", "pretty"],
  ["el hermano", "the brother"],
  ["el perro", "the dog"],
  ["la esposa", "the wife"],
  ["el esposo", "the husband"],
  ["el apartamento", "the apartment"],
  ["el abuelo", "the grandfather"],
  ["perfecto", "perfect"],
  ["la familia", "the family"],
  ["la abuela", "the grandmother"],
  ["vivo", "I live"],
  ["la bicicleta", "the bicycle"],
  ["la hija", "the daughter"],
  ["tienes", "you have (tú)"],
  ["interesante", "interesting"],
  ["el hijo", "the son"],
  ["y", "and"],
  ["verde", "green"],
  ["azul", "blue"],
  ["la chaqueta", "the jacket"],
  ["la tienda", "the store"],
  ["la ropa", "the clothes"],
  ["la camisa", "the shirt"],
  ["marrón", "brown"],
  ["el vestido", "the dress"],
  ["la camiseta", "the T-shirt"],
  ["gris", "gray"],
  ["el sombrero", "the hat"],
  ["comprar", "to buy"],
  ["este", "this (masculine)"],
  ["rojo", "red"],
  ["la falda", "the skirt"],
  ["barato", "cheap"],
  ["ese", "that (masculine)"],
  ["caro", "expensive"],
  ["el abrigo", "the coat"],
  ["diferente", "different"],
  ["la cartera", "the wallet"],
  ["cómoda", "comfortable"],
  ["favorita", "favorite (feminine)"],
  ["el reloj", "the watch"],
  ["el cinturón", "the belt"],
  ["el regalo", "the gift"],
  ["demasiado", "too much"],
  ["el bolígrafo", "the pen"],
  ["la escuela", "the school"],
  ["el libro", "the book"],
  ["el examen", "the exam"],
  ["el maestro", "the teacher"],
  ["fácil", "easy"],
  ["la clase", "the class"],
  ["difícil", "difficult"],
  ["el estudiante", "the student"],
  ["el problema", "the problem"],
  ["estudiar", "to study"],
  ["leer", "to read"],
  ["la pregunta", "the question"],
  ["escribir", "to write"],
  ["leo", "I read"],
  ["comprendo", "I understand"],
  ["mucho", "a lot"],
  ["estudio", "I study"],
  ["importante", "important"],
  ["escribo", "I write"],
  ["el profesor", "the professor"],
  ["escribes", "you write (tú)"],
  ["estudias", "you study (tú)"],
  ["lees", "you read (tú)"],
  ["la computadora", "the computer"],
  ["la universidad", "the university"],
  ["la medicina", "medicine"],
  ["americano", "American (male)"],
  ["me llamo", "my name is"],
  ["España", "Spain"],
  ["americana", "American (female)"],
  ["el nombre", "the name"],
  ["cubana", "Cuban (female)"],
  ["mexicana", "Mexican (female)"],
  ["cubano", "Cuban (male)"],
  ["mexicano", "Mexican (male)"],
  ["estás", "you are (temporary, tú)"],
  ["estoy", "I am (temporary)"],
  ["cansado", "tired (male)"],
  ["cómo", "how"],
  ["bien", "well / fine"],
  ["cansada", "tired (female)"],
  ["hasta luego", "see you later"],
  ["hasta mañana", "see you tomorrow"],
  ["la señora", "the woman (formal)"],
  ["usted", "you (formal)"],
  ["buenas tardes", "good afternoon"],
  ["la señorita", "the miss (young woman)"],
  ["el señor", "the man (Mr.)"],
  ["cómo está", "how are you (formal)"],
  ["ocupado", "busy (male)"],
  ["se llama", "his/her name is"],
  ["te llamas", "your name is (tú)"],
  ["feliz", "happy"],
  ["ocupada", "busy (female)"],
  ["mal", "bad / unwell"],
  ["el té", "the tea"],
  ["más", "more"],
  ["la banana", "the banana"],
  ["quiere", "he/she wants"],
  ["quieres", "you want (tú)"],
  ["necesita", "he/she needs"],
  ["necesitas", "you need (tú)"],
  ["la ayuda", "the help"],
  ["usar", "to use"],
  ["usa", "he/she uses"],
  ["usas", "you use (tú)"],
  ["uso", "I use"],
  ["el fútbol", "soccer"],
  ["el lunes", "Monday"],
  ["hoy", "today"],
  ["el martes", "Tuesday"],
  ["cuándo", "when"],
  ["mañana", "tomorrow"],
  ["el partido", "the game / match"],
  ["qué", "what"],
  ["el día", "the day"],
  ["el cumpleaños", "the birthday"],
  ["el jueves", "Thursday"],
  ["el béisbol", "baseball"],
  ["el miércoles", "Wednesday"],
  ["el viernes", "Friday"],
  ["el sábado", "Saturday"],
  ["el domingo", "Sunday"],
  ["divertido", "fun (male)"],
  ["el concierto", "the concert"],
  ["la fiesta", "the party"],
  ["divertida", "fun (female)"],
  ["favorito", "favorite (male)"],
  ["la semana", "the week"],
  ["el baile", "the dance"],
  ["la película", "the movie"],
  ["disfruta", "he/she enjoys"],
  ["el fin de semana", "the weekend"],
  ["habla", "he/she speaks"],
  ["estudia", "he/she studies"],
  ["hablar", "to speak"],
  ["el francés", "the French language"],
  ["quién", "who"],
  ["la fábrica", "the factory"],
  ["trabajas", "you work (tú)"],
  ["trabaja", "he/she works"],
  ["la oficina", "the office"],
  ["el trabajo", "the job"],
  ["trabajar", "to work"],
  ["comer", "to eat"],
  ["el vino", "the wine"],
  ["beber", "to drink"],
  ["vive", "he/she lives"],
  ["Europa", "Europe"],
  ["vives", "you live (tú)"],
  ["vivir", "to live"],
  ["Inglaterra", "England"],
  ["Francia", "France"],
  ["la camarera", "the waitress"],
  ["el camarero", "the waiter"],
  ["la maestra", "the teacher (female)"],
  ["el portugués", "the Portuguese language"],
  ["el celular", "the cell phone"],
  ["el número", "the number"],
  ["el amigo", "the friend (male)"],
  ["la dirección", "the address"],
  ["ser", "to be"],
  ["la amiga", "the friend (female)"],
  ["joven", "young"],
  ["la médica", "the doctor (female)"],
  ["la ciudad", "the city"],
  ["el médico", "the doctor (male)"],
  ["la novia", "the girlfriend"],
  ["el pueblo", "the town"],
  ["el novio", "the boyfriend"],
  ["cero", "zero"],
  ["los libros", "the books"],
  ["los bolígrafos", "the pens"],
  ["la biblioteca", "the library"],
  ["las computadoras", "the computers"],
  ["cuatro", "four"],
  ["las bibliotecas", "the libraries"],
  ["esta", "this (feminine)"],
  ["aprendo", "I learn"],
  ["aprender", "to learn"],
  ["aprende", "he/she learns"],
  ["aprendes", "you learn (tú)"],
  ["cinco", "five"],
  ["las clases", "the classes"],
  ["ocho", "eight"],
  ["las preguntas", "the questions"],
  ["los estudiantes", "the students"],
  ["siete", "seven"],
  ["seis", "six"],
  ["el italiano", "the Italian language"],
  ["bonita", "pretty (female)"],
  ["su", "his/her (formal)"],
  ["pequeño", "small (male)"],
  ["los hijos", "the children"],
  ["pequeña", "small (female)"],
  ["la mascota", "the pet"],
  ["baja", "short / low (female)"],
  ["alto", "tall (male)"],
  ["simpático", "nice (male)"],
  ["bajo", "short (male)"],
  ["simpática", "nice (female)"],
  ["alta", "tall (female)"],
  ["el año", "the year"],
  ["diez", "ten"],
  ["nueve", "nine"],
  ["española", "Spanish (female)"],
  ["inglesa", "English (female)"],
  ["el jefe", "the boss"],
  ["el secretario", "the secretary"],
  ["el mensaje", "the message"],
  ["las", "the (feminine plural article)"],
  ["los", "the (masculine plural article)"],
  ["el escritorio", "the desk"],
  ["escribe", "he/she writes"],
  ["la carta", "the letter"],
  ["cuál", "which"],
  ["poco", "little"],
  ["el correo electrónico", "the email"],
  ["tener", "to have"],
  ["el negocio", "the business"],
  ["nuevo", "new (male)"],
  ["lee", "he/she reads"],
  ["ahora", "now"],
  ["emocionar", "to excite"],
  ["enfermo", "sick (male)"],
  ["qué tal", "how are you"],
  ["conmigo", "with me"],
  ["contigo", "with you"],
  ["triste", "sad"],
  ["siempre", "always"],
  ["enojado", "angry (male)"],
  ["aburrido", "bored (male)"],
  ["preocupado", "worried (male)"],
  ["por qué", "why"],
  ["también", "also"],
  ["contento", "happy (male)"],
  ["el papá", "the dad"],
  ["la mamá", "the mom"],
  ["dormir", "to sleep"],
  ["disfrutar", "to enjoy"],
  ["a veces", "sometimes"],
  ["nunca", "never"],
  ["sorprendido", "surprised (male)"],
  ["el bebé", "the baby"],
  ["otra vez", "again"],
  ["un poco", "a little"],
  ["te sientes", "you feel (tú)"],
  ["se siente", "he/she feels"],
  ["me siento", "I feel"],
  ["las mujeres", "the women"],
  ["los hombres", "the men"],
  ["somos", "we are"],
  ["nosotros", "we (masculine)"],
  ["estudiamos", "we study"],
  ["nosotras", "we (feminine)"],
  ["hablamos", "we speak"],
  ["ellos", "they (masculine)"],
  ["estudian", "they study"],
  ["las ciudades", "the cities"],
  ["las universidades", "the universities"],
  ["ellas", "they (feminine)"],
  ["hablan", "they speak"],
  ["son", "they are"],
  ["el jugador", "the player"],
  ["muchos", "many (masculine)"],
  ["ustedes", "you all"],
  ["los fines de semana", "the weekends"],
  ["muchas", "many (feminine)"],
  ["cuánto", "how much"],
  ["unos", "some (masculine)"],
  ["las vacaciones", "the vacation"],
  ["unas", "some (feminine)"],
  ["cuántas", "how many (feminine)"],
  ["las señoras", "the ladies"],
  ["los señores", "the gentlemen"],
  ["las carteras", "the wallets"],
  ["verdes", "green (plural)"],
  ["interesantes", "interesting (plural)"],
  ["grandes", "big (plural)"],
  ["el zapato", "the shoe"],
  ["bonitas", "pretty (plural feminine)"],
  ["nuevos", "new (plural masculine)"],
  ["nuevas", "new (plural feminine)"],
  ["usamos", "we use"],
  ["bonitos", "pretty (plural masculine)"],
  ["necesitamos", "we need"],
  ["el pantalón", "the pants"],
  ["estas", "these (feminine)"],
  ["rojas", "red (feminine plural)"],
  ["rojos", "red (masculine plural)"],
  ["estos", "these (masculine)"],
  ["usan", "they use / they wear"],
  ["sus", "his/her/their (plural)"],
  ["tus", "your (plural, tú)"],
  ["necesitan", "they need"],
  ["pequeñas", "small (feminine plural)"],
  ["pequeños", "small (masculine plural)"],
  ["mis", "my (plural)"],
  ["la estación", "the station"],
  ["cerca de", "near to"],
  ["ir", "to go"],
  ["viajar", "to travel"],
  ["cerca", "near"],
  ["el parque", "the park"],
  ["estamos", "we are"],
  ["el café", "the coffee"],
  ["al", "to the"],
  ["del", "of the"],
  ["la parada", "the stop"],
  ["la puerta", "the door"],
  ["lejos", "far"],
  ["están", "they are"],
  ["al lado", "next to"],
  ["el metro", "the subway"],
  ["la derecha", "the right"],
  ["tomar", "to take"],
  ["la izquierda", "the left"],
  ["la playa", "the beach"],
  ["el periódico", "the newspaper"],
  ["queremos", "we want"],
  ["leemos", "we read"],
  ["caminar", "to walk"],
  ["los sándwiches", "the sandwiches"],
  ["comemos", "we eat"],
  ["la tarde", "the afternoon"],
  ["vivimos", "we live"],
  ["los correos electrónicos", "the emails"],
  ["las casas", "the houses"],
  ["escribimos", "we write"],
  ["bueno", "good"],
  ["el pollo", "the chicken"],
  ["la comida", "the food"],
  ["quieren", "they want"],
  ["comen", "they eat"],
  ["el arroz", "the rice"],
  ["los restaurantes", "the restaurants"],
  ["junto", "together"],
  ["el verano", "the summer"],
  ["escriben", "they write"],
  ["abrir", "to open"],
  ["viven", "they live"],
  ["leen", "they read"],
  ["trabajar en", "to work in"],
  ["hablar español", "to speak Spanish"],
  ["trabajan", "they work"],
  ["toma", "he/she takes"],
  ["trabajamos", "we work"],
  ["tomamos", "we take / we drink"],
  ["tomar el", "to take the"],
  ["comer una", "to eat a"],
  ["leer este", "to read this"],
  ["tú bebes", "you drink"],
  ["beben", "they drink"],
  ["vivir en", "to live in"],
  ["abren", "they open"],
  ["abrimos", "we open"],
  ["aprenden", "they learn"],
  ["necesito comprar", "I need to buy"],
  ["compran", "they buy"],
  ["salir", "to go out"],
  ["salimos", "we go out"],
  ["aprendemos", "we learn"],
  ["compramos", "we buy"],
  ["salen", "they go out"],
  ["quiere aprender", "he/she wants to learn"],
  ["el pastel", "the cake"],
  ["el chocolate", "the chocolate"],
  ["porque", "because"],
  ["me gusta", "I like"],
  ["algo", "something"],
  ["creo que", "I think that"],
  ["pero", "but"],
  ["te gusta", "you like"],
  ["la piscina", "the swimming pool"],
  ["te encanta", "you love"],
  ["jugar", "to play"],
  ["correr", "to run"],
  ["me encanta", "I love"],
  ["nadar", "to swim"],
  ["dibujar", "to draw"],
  ["el chico", "the boy"],
  ["el viejo", "the old man"],
  ["la música", "the music"],
  ["los perros", "the dogs"],
  ["la noche", "the night"],
  ["el cine", "the cinema"],
  ["todo", "everything"],
  ["voy", "I go"],
  ["va", "he/she goes"],
  ["a menudo", "often"],
  ["vas", "you go"],
  ["los días", "the days"],
  ["media", "half"],
  ["la televisión", "the television"],
  ["los sábados", "on Saturdays"],
  ["van", "they go"],
  ["mirar", "to watch"],
  ["vamos", "we go"],
  ["la hora", "the hour"],
  ["los domingos", "on Sundays"],
  ["tengo que", "I have to"],
  ["tienes que", "you have to"],
  ["tiene que", "he/she has to"],
  ["me levanto", "I get up"],
  ["me ducho", "I shower"],
  ["se ducha", "he/she showers"],
  ["once", "eleven"],
  ["doce", "twelve"],
  ["te levantas", "you get up"],
  ["te duchas", "you shower"],
  ["a qué hora", "at what time"],
  ["se levanta", "he/she gets up"],
  ["la sala", "the living room"],
  ["la nevera", "the fridge"],
  ["la cama", "the bed"],
  ["el dormitorio", "the bedroom"],
  ["moderno", "modern"],
  ["la cocina", "the kitchen"],
  ["hay", "there is / there are"],
  ["la habitación", "the room"],
  ["la ventana", "the window"],
  ["tienen", "they have"],
  ["tenemos", "we have"],
  ["la silla", "the chair"],
  ["la estantería", "the bookshelf"],
  ["pintar", "to paint"],
  ["sobre", "on"],
  ["limpiar", "to clean"],
  ["la planta", "the plant"],
  ["el jardín", "the garden"],
  ["debajo", "under"],
  ["los celulares", "the cell phones"],
  ["los teléfonos", "the phones"],
  ["la cerveza", "the beer"],
  ["los menús", "the menus"],
  ["el frijol", "the bean"],
  ["quisiera", "I would like"],
  ["la cuchara", "the spoon"],
  ["el cuchillo", "the knife"],
  ["el tenedor", "the fork"],
  ["el plato", "the plate"],
  ["puede traer", "can you bring"],
  ["la bebida", "the drink"],
  ["otro", "another"],
  ["el tinto", "red wine"],
  ["la botella", "the bottle"],
  ["blanco", "white"],
  ["un plato", "a dish"],
  ["la patata", "the potato"],
  ["frito", "fried"],
  ["la sopa", "the soup"],
  ["el postre", "the dessert"],
  ["nuestro", "our"],
  ["las familias", "the families"],
  ["los padres", "the parents"],
  ["se llaman", "their names are"],
  ["el deporte", "the sport"],
  ["le gusta", "he/she likes"],
  ["le encanta", "he/she loves"],
  ["el baloncesto", "basketball"],
  ["el piano", "the piano"],
  ["la guitarra", "the guitar"],
  ["los conciertos", "the concerts"],
  ["nos gusta", "we like"],
  ["tocar", "to play (an instrument)"],
  ["escuchar", "to listen to"],
  ["nos encanta", "we love"],
  ["el marido", "the husband"],
  ["mayor", "older"],
  ["menor", "younger"],
  ["las películas", "the movies"],
  ["mí", "me"],
  ["abre", "it opens"],
  ["de compras", "shopping"],
  ["cierra", "it closes"],
  ["ti", "you (object)"],
  ["buscar", "to look for"],
  ["el probador", "the fitting room"],
  ["la talla", "the size"],
  ["el precio", "the price"],
  ["me puedo probar", "can I try on"],
  ["el peso", "the weight"],
  ["el dólar", "the dollar"],
  ["catorce", "fourteen"],
  ["quince", "fifteen"],
  ["trece", "thirteen"],
  ["cuestan", "they cost"],
  ["cuesta", "it costs"],
  ["la tarjeta de crédito", "the credit card"],
  ["dieciocho", "eighteen"],
  ["diecinueve", "nineteen"],
  ["en efectivo", "in cash"],
  ["veinte", "twenty"],
  ["dieciséis", "sixteen"],
  ["diecisiete", "seventeen"],
  ["emocionados", "excited (plural masculine)"],
  ["nervioso", "nervous (male)"],
  ["tristes", "sad (plural)"],
  ["felices", "happy (plural)"],
  ["limpio", "clean (male)"],
  ["abierto", "open (male)"],
  ["sucio", "dirty (male)"],
  ["negro", "black"],
  ["guapo", "handsome"],
  ["amarillo", "yellow"],
  ["moreno", "dark-haired"],
  ["rubio", "blond"],
  ["es grande", "is big"],
  ["responsable", "responsible"],
  ["perezoso", "lazy (male)"],
  ["estudioso", "studious (male)"],
  ["la persona", "the person"],
  ["inteligentes", "intelligent (plural)"],
  ["es divertido", "is fun"],
  ["es muy simpático", "is very nice"],
  ["aquel", "that (masculine)"],
  ["les encanta", "they love"],
  ["para ella", "for her"],
  ["les gusta", "they like"],
  ["para él", "for him"],
  ["el zoológico", "the zoo"],
  ["a mí", "to me"],
  ["a ti", "to you (informal)"],
  ["a usted", "to you (formal)"],
  ["el tenis", "tennis"],
  ["a él", "to him"],
  ["pasar", "to spend (time)"],
  ["el tiempo", "the time"],
  ["a ustedes", "to you all"],
  ["para nosotros", "for us"],
  ["a nosotros", "to us"],
  ["normalmente", "usually"],
  ["montar", "to ride"],
  ["el caballo", "the horse"],
  ["la pelota", "the ball"],
  ["el río", "the river"],
  ["conoces", "you know (a person/place)"],
  ["el país", "the country"],
  ["conocer", "to know / to meet"],
  ["conozco", "I know"],
  ["visitar", "to visit"],
  ["la parte", "the part"],
  ["el lugar", "the place"],
  ["la gente", "the people"],
  ["los pueblos", "the towns"],
  ["alguno", "some / any (masculine)"],
  ["ayudar", "to help"],
  ["llamar", "to call"],
  ["usualmente", "usually"],
  ["ver", "to see"],
  ["amar", "to love"],
  ["enseñar", "to teach"],
  ["la tele", "the TV"],
  ["el adulto", "the adult"],
  ["cuántos años", "how old"],
  ["veintiún", "twenty-one"],
  ["los jóvenes", "the young people"],
  ["las señoritas", "the young ladies"],
  ["veintidós", "twenty-two"],
  ["veintiuno", "twenty-one"],
  ["la pizza", "the pizza"],
  ["sed", "thirst"],
  ["veinticinco", "twenty-five"],
  ["hambre", "hunger"],
  ["los jugos", "the juices"],
  ["veintitrés", "twenty-three"],
  ["veinticuatro", "twenty-four"],
  ["largo", "long"],
  ["frío", "cold"],
  ["el puesto", "the stand"],
  ["calor", "heat"],
  ["el animal", "the animal"],
  ["bailar", "to dance"],
  ["sueño", "sleepiness"],
  ["miedo", "fear"],
  ["de verdad", "really"],
  ["ganas", "desire"],
  ["la muñeca", "the doll"],
  ["me", "me"],
  ["nos", "us"],
  ["te", "you (object)"],
  ["me compra", "he/she buys me"],
  ["nos compra", "he/she buys us"],
  ["te compra", "he/she buys you"],
  ["me escucha", "he/she listens to me"],
  ["te visitan", "they visit you"],
  ["me conoce", "he/she knows me"],
  ["me necesita", "he/she needs me"],
  ["nos conocen", "they know us"],
  ["te conozco", "I know you"],
  ["nos visita", "he/she visits us"],
  ["te llamamos", "we call you"],
  ["nos escuchan", "they listen to us"],
  ["me llaman", "they call me"],
  ["me ama", "he/she loves me"],
  ["nos llamas", "you call us"],
  ["te amo", "I love you"],
  ["te necesito", "I need you"],
  ["el curso", "the course"],
  ["el alemán", "the German language"],
  ["el idioma", "the language"],
  ["me enseña", "he/she teaches me"],
  ["nos ayudan", "they help us"],
  ["me ayudas", "you help me"],
  ["te ayudo", "I help you"],
  ["el almuerzo", "the lunch"],
  ["haces", "you do / you make"],
  ["el desayuno", "the breakfast"],
  ["la tarea", "the homework"],
  ["la cena", "the dinner"],
  ["hacer", "to do / to make"],
  ["hago", "I do / I make"],
  ["tomo", "I drink / I take"],
  ["el diario", "the newspaper"],
  ["la cosa", "the thing"],
  ["solo", "alone"],
  ["después", "after"],
  ["antes", "before"],
  ["ducharse", "to shower"],
  ["ponerse", "to put on"],
  ["se pone", "he/she puts on"],
  ["cada", "each"],
  ["me pongo", "I put on"],
  ["te pones", "you put on"],
  ["levantarse", "to get up"],
  ["sale", "he/she leaves"],
  ["las semanas", "the weeks"],
  ["temprano", "early"],
  ["salgo", "I leave"],
  ["probar", "to try"],
  ["almuerzan", "they eat lunch"],
  ["almorzar", "to eat lunch"],
  ["la prueba", "the test"],
  ["probamos", "we try"],
  ["pruebo", "I try"],
  ["prueban", "they try"],
  ["almorzamos", "we eat lunch"],
  ["almuerzas", "you eat lunch"],
  ["volvemos", "we return"],
  ["poder", "to be able to"],
  ["puede", "can"],
  ["vuelves", "you return"],
  ["vuelven", "they return"],
  ["podemos", "we can"],
  ["pueden", "they can"],
  ["puedo", "I can"],
  ["volver", "to return"],
  ["cierras", "you close"],
  ["empezamos", "we start"],
  ["cerrar", "to close"],
  ["empiezo", "I start"],
  ["empiezan", "they start"],
  ["empieza", "it starts"],
  ["cierran", "they close"],
  ["cerramos", "we close"],
  ["empezar", "to start"],
  ["entiendo", "I understand"],
  ["perdemos", "we lose"],
  ["entienden", "they understand"],
  ["perder", "to lose"],
  ["entiende", "he/she understands"],
  ["entender", "to understand"],
  ["pierden", "they lose"],
  ["entendemos", "we understand"],
  ["pierdes", "you lose"],
  ["el viento", "the wind"],
  ["qué tiempo hace", "what is the weather like"],
  ["hace frío", "it is cold"],
  ["hace calor", "it is hot"],
  ["el sol", "the sun"],
  ["mal tiempo", "bad weather"],
  ["buen tiempo", "good weather"],
  ["el invierno", "the winter"],
  ["oscuro", "dark"],
  ["nublado", "cloudy"],
  ["enero", "January"],
  ["cómo está el tiempo", "how is the weather"],
  ["febrero", "February"],
  ["marzo", "March"],
  ["la primavera", "the spring"],
  ["mayo", "May"],
  ["julio", "July"],
  ["junio", "June"],
  ["llueve", "it rains"],
  ["abril", "April (the month)"],
  ["nieva", "it snows"],
  ["el otoño", "the autumn / the fall"],
  ["el mes", "the month"],
  ["noviembre", "November"],
  ["octubre", "October"],
  ["diciembre", "December"],
  ["septiembre", "September"],
  ["agosto", "August"],
  ["la foto", "the photo"],
  ["la conversación", "the conversation"],
  ["nos interesa", "we are interested in it"],
  ["te interesa", "you are interested in it"],
  ["les interesa", "they are interested in it"],
  ["le interesa", "he or she is interested in it"],
  ["me interesa", "I am interested in it"],
  ["el europeo", "the European (man)"],
  ["el arte", "the art"],
  ["la pintura", "the painting"],
  ["importantes", "important (plural)"],
  ["preferir", "to prefer"],
  ["el juego", "the game"],
  ["cuáles", "which ones"],
  ["jugamos", "we play"],
  ["el básquetbol", "the basketball"],
  ["practicar", "to practice"],
  ["el grupo", "the group"],
  ["la asignatura", "the subject"],
  ["la radio", "the radio"],
  ["las fiestas", "the parties"],
  ["los partidos", "the matches"],
  ["esto", "this (thing)"],
  ["la respuesta", "the answer"],
  ["la palabra", "the word"],
  ["la edad", "the age"],
  ["sabes", "you know"],
  ["sé cuándo", "I know when"],
  ["sé", "I know"],
  ["saber", "to know (a fact or skill)"],
  ["sabemos dónde", "we know where"],
  ["cómo se dice", "how do you say it"],
  ["sabe usted", "do you know (formal)"],
  ["sabes quién", "do you know who"],
  ["sabes cuándo", "do you know when"],
  ["no lo sé", "I don't know"],
  ["cómo se escribe", "how do you write it"],
  ["manejar", "to drive"],
  ["cocinar", "to cook"],
  ["las carnes", "the meats"],
  ["sabes nadar", "you know how to swim"],
  ["la canción", "the song"],
  ["cantar", "to sing"],
  ["el chino", "the Chinese language"],
  ["el mismo", "the same one"],
  ["la lengua", "the language"],
  ["el japonés", "the Japanese language"],
  ["la gorra", "the cap"],
  ["la blusa", "the blouse"],
  ["cómodo", "comfortable"],
  ["menos", "less"],
  ["que", "than"],
  ["bello", "beautiful"],
  ["mejor", "better"],
  ["peor", "worse"],
  ["famoso", "famous"],
  ["tan", "so"],
  ["delgado", "thin"],
  ["gordo", "fat"],
  ["el mundo", "the world"],
  ["el más", "the most"],
  ["el peor", "the worst one"],
  ["el mejor", "the best one"],
  ["la más", "the most (feminine)"],
  ["popular", "popular"],
  ["qué divertido", "how fun"],
  ["qué elegante", "how elegant"],
  ["es tan", "is so"],
  ["qué interesante", "how interesting"],
  ["tan bonita", "so beautiful (feminine)"],
  ["el próximo", "the next one"],
  ["voy a", "I am going to"],
  ["los pasaportes", "the passports"],
  ["va a", "he or she is going to"],
  ["las maletas", "the suitcases"],
  ["vas a", "you are going to"],
  ["los boletos", "the tickets"],
  ["el avión", "the airplane"],
  ["listo", "ready"],
  ["llegar", "to arrive"],
  ["vamos a", "we are going to"],
  ["van a", "they are going to"],
  ["adónde", "where to"],
  ["los carros", "the cars"],
  ["los taxis", "the taxis"],
  ["estar", "to be (temporary)"],
  ["veintisiete", "twenty-seven"],
  ["veintiséis", "twenty-six"],
  ["pronto", "soon"],
  ["por", "for"],
  ["el minuto", "the minute"],
  ["la cámara", "the camera"],
  ["el cuarto", "the room"],
  ["treinta", "thirty"],
  ["veintiocho", "twenty-eight"],
  ["veintinueve", "twenty-nine"],
  ["dulce", "sweet"],
  ["el chileno", "the Chilean man"],
  ["las ensaladas", "the salads"],
  ["los vinos", "the wines"],
  ["gustan", "they like"],
  ["las bananas", "the bananas"],
  ["encantan", "they love"],
  ["caliente", "hot"],
  ["el ojo", "the eye"],
  ["la francesa", "the French woman"],
  ["la flor", "the flower"],
  ["el tipo", "the type"],
  ["rápido", "fast"],
  ["el sitio", "the place"],
  ["el pájaro", "the bird"],
  ["interesan", "they interest"],
  ["los bailes", "the dances"],
  ["la bota", "the boot"],
  ["el color", "the color"],
  ["el par", "the pair"],
  ["ambos", "both"],
  ["los lentes", "the glasses"],
  ["los vaqueros", "the jeans"],
  ["el kilo", "the kilogram"],
  ["la fruta", "the fruit"],
  ["la bolsa", "the bag"],
  ["el plátano", "the banana"],
  ["tenemos que", "we have to"],
  ["la compra", "the shopping"],
  ["el huevo", "the egg"],
  ["la papa", "the potato"],
  ["el vegetal", "the vegetable"],
  ["cuánta", "how much (feminine)"],
  ["tienen que", "they have to"],
  ["la mantequilla", "the butter"],
  ["picante", "spicy"],
  ["el chorizo", "the chorizo"],
  ["el centavo", "the cent"],
  ["sesenta", "sixty"],
  ["llevar", "to wear"],
  ["cuarenta", "forty"],
  ["cincuenta", "fifty"],
  ["el refrigerador", "the refrigerator"],
  ["lavar", "to wash"],
  ["pones", "you put"],
  ["poner", "to put"],
  ["pongo", "I put"],
  ["despacio", "slowly"],
  ["hablas con", "you talk with"],
  ["pruebe", "try (formal command)"],
  ["trabaje", "work (formal command)"],
  ["hable", "speak (formal command)"],
  ["la página", "the page"],
  ["abres", "you open"],
  ["vuelve", "he or she comes back"],
  ["el lápiz", "the pencil"],
  ["escriba", "write (formal command)"],
  ["vuelva", "come back (formal command)"],
  ["beba", "drink (formal command)"],
  ["la mano", "the hand"],
  ["me lavo", "I wash myself"],
  ["nos levantamos", "we get up"],
  ["nos llamamos", "our names are"],
  ["lavarse", "to wash oneself"],
  ["nos duchamos", "we shower"],
  ["mío", "mine"],
  ["el cabello", "the hair"],
  ["la cara", "the face"],
  ["la llave", "the key"],
  ["se lavan", "they wash themselves"],
  ["se duchan", "they shower"],
  ["se levantan", "they get up"],
  ["suyo", "his or hers"],
  ["tuyo", "yours"],
  ["nos ponemos", "we put on"],
  ["se ponen", "they put on"],
  ["nos sentimos", "we feel"],
  ["se sienten", "they feel"],
  ["me cepillo", "I brush myself"],
  ["el diente", "the tooth"],
  ["el cepillo", "the brush"],
  ["el cepillo de dientes", "the toothbrush"],
  ["cepillarse", "to brush oneself"],
  ["nos cepillamos", "we brush ourselves"],
  ["se cepillan", "they brush themselves"],
  ["el aula", "the classroom"],
  ["la lección", "the lesson"],
  ["hablar con", "to talk with"],
  ["escuchando", "listening"],
  ["estudiando", "studying"],
  ["que estudiar", "to study"],
  ["hablando", "speaking"],
  ["el diccionario", "the dictionary"],
  ["quiero aprender", "I want to learn"],
  ["comiendo", "eating (right now)"],
  ["qué hacer", "what to do"],
  ["haciendo", "doing (right now)"],
  ["aprendiendo", "learning (right now)"],
  ["la nota", "the grade"],
  ["la pizarra", "the board (classroom board)"],
  ["escribiendo", "writing (right now)"],
  ["abriendo", "opening (right now)"],
  ["saliendo", "leaving (right now)"],
  ["qué escribir", "what to write"],
  ["las escuelas", "the schools"],
  ["qué leer", "what to read"],
  ["leyendo", "reading (right now)"],
  ["bebiendo", "drinking (right now)"],
  ["dibujando", "drawing (right now)"],
  ["los comen", "they eat them"],
  ["lo compro", "I buy it"],
  ["los tés", "the teas"],
  ["lo", "it (masculine direct object)"],
  ["bebemos", "we drink"],
  ["lo quiero", "I want it (masculine)"],
  ["la bici", "the bike"],
  ["las pruebas", "the tests"],
  ["las comen", "they eat them (feminine)"],
  ["la quiero", "I want it (feminine)"],
  ["ya", "already"],
  ["el paquete", "the package"],
  ["lento", "slow"],
  ["malo", "bad"],
  ["cierro", "I close"],
  ["abro", "I open"],
  ["los necesita", "he or she needs them"],
  ["todos", "everyone"],
  ["ligero", "light (not heavy)"],
  ["la salsa", "the sauce"],
  ["la imagen", "the image"],
  ["los cafés", "the coffees"],
  ["los gatos", "the cats"],
  ["todo el tiempo", "all the time"],
  ["el plan", "the plan"],
  ["la fecha", "the date"],
  ["quedarse", "to stay"],
  ["primero", "first"],
  ["empiezas", "you start"],
  ["que viene", "next"],
  ["puedes", "you can"],
  ["vuelvo", "I return"],
  ["me quedo", "I stay"],
  ["todo el mundo", "everyone"],
  ["gustaría", "would like"],
  ["vengo", "I come"],
  ["venir", "to come"],
  ["cambiar", "to change"],
  ["se queda", "he or she stays"],
  ["viene", "he or she comes"],
  ["invitar", "to invite"],
  ["gustar", "to like"],
  ["decir", "to say"],
  ["pienso", "I think"],
  ["por supuesto", "of course"],
  ["pensamos", "we think"],
  ["piensa", "he or she thinks"],
  ["pensando", "thinking"],
  ["venimos", "we come"],
  ["pensar", "to think"],
  ["luego", "then"],
  ["cenar", "to eat dinner"],
  ["volar", "to fly"],
  ["ayudo a", "I help"],
  ["empezamos a", "we start to"],
  ["aprendiendo a", "learning to"],
  ["salir a", "to go out to"],
  ["enseña a", "he or she teaches"],
  ["la librería", "the bookstore"],
  ["la entrada", "the entrance ticket"],
  ["el papel", "the paper"],
  ["recordar", "to remember"],
  ["desayunar", "to have breakfast"],
  ["encontrar", "to find"],
  ["la oreja", "the ear"],
  ["el pie", "the foot"],
  ["lavarnos", "to wash ourselves"],
  ["ducharte", "to shower yourself"],
  ["levantarte", "to get up (yourself)"],
  ["probarse", "to try on"],
  ["levantarme", "to get up (myself)"],
  ["la aldea", "the village"],
  ["esperar", "to wait"],
  ["ponerte", "to put on (yourself)"],
  ["probarte", "to try on (yourself)"],
  ["quedarnos", "to stay (ourselves)"],
  ["quedarme", "to stay (myself)"],
  ["ponerme", "to put on (myself)"],
  ["la caja", "the box"],
  ["traes", "you bring"],
  ["eso", "that"],
  ["nos ayudas", "you help us"],
  ["abres la", "you open the"],
  ["coges", "you take"],
  ["seguro", "sure"],
  ["el césped", "the grass"],
  ["la pared", "the wall"],
  ["el piso", "the floor"],
  ["la granja", "the farm"],
  ["traigo", "I bring"],
  ["cierro la", "I close the"],
  ["la ducha", "the shower"],
  ["los cuartos", "the rooms"],
  ["sentarse", "to sit down"],
  ["levántate", "get up (informal command)"],
  ["levántese", "get up (formal command)"],
  ["miro", "I look at"],
  ["acá", "here"],
  ["siéntese", "sit down (formal command)"],
  ["siéntate", "sit down (informal command)"],
  ["lávate", "wash yourself (informal)"],
  ["lávese", "wash yourself (formal)"],
  ["allá", "over there"],
  ["hermoso", "beautiful"],
  ["le", "to him or her"],
  ["ochenta", "eighty"],
  ["dar", "to give"],
  ["doy", "I give"],
  ["le hago", "I do it for him or her"],
  ["setenta", "seventy"],
  ["das", "you give"],
  ["cien", "one hundred"],
  ["noventa", "ninety"],
  ["las oficinas", "the offices"],
  ["mandar", "to send"],
  ["les", "to them"],
  ["digo", "I say"],
  ["el mesero", "the waiter"],
  ["mando", "I send"],
  ["dices", "you say"],
  ["almuerza", "he or she eats lunch"],
  ["mil", "one thousand"],
  ["pregunto", "I ask"],
  ["la portuguesa", "the Portuguese woman"],
  ["millón", "one million"],
  ["nada es", "nothing is"],
  ["preguntar", "to ask"],
  ["decimos", "we say"],
  ["nada", "nothing"],
  ["cercano", "nearby"],
  ["siga", "continue (formal command)"],
  ["tome", "take (formal command)"],
  ["perdone", "excuse me (formal)"],
  ["girar", "to turn"],
  ["gire", "turn (formal command)"],
  ["derecho", "straight"],
  ["perdona", "excuse me (informal)"],
  ["sigue", "continue (informal)"],
  ["gira", "turn (informal)"],
  ["disculpa", "excuse me"],
  ["enfrente", "in front of"],
  ["giro", "I turn"],
  ["la carretera", "the road"],
  ["las direcciones", "the directions"],
  ["seguir", "to follow"],
  ["buscando", "looking for"],
  ["entre", "between"],
  ["detrás", "behind"],
  ["espero", "I wait"],
  ["arriba", "up"],
  ["atrás", "behind"],
  ["abajo", "down"],
  ["el final", "the end"],
  ["fuera", "outside"],
  ["dentro", "inside"],
  ["pasado", "last"],
  ["probé", "I tried"],
  ["probaste", "you tried"],
  ["hablé", "I spoke"],
  ["hablaste", "you spoke"],
  ["viajé", "I traveled"],
  ["viajaste", "you traveled"],
  ["bebí", "I drank"],
  ["ayer", "yesterday"],
  ["bebiste", "you drank"],
  ["comí", "I ate"],
  ["viviste", "you lived"],
  ["comiste", "you ate"],
  ["viví", "I lived"],
  ["el viaje", "the trip"],
  ["fuiste", "you went"],
  ["fui", "I went"],
  ["visitaste", "you visited"],
  ["visité", "I visited"],
  ["estudié", "I studied"],
  ["estudiaste", "you studied"],
  ["hace mucho tiempo", "a long time ago"],
  ["estuve", "I was"],
  ["aprendí", "I learned"],
  ["conociste", "you met"],
  ["estuviste", "you were"],
  ["conocí", "I met"],
  ["aprendiste", "you learned"],
  ["la vaca", "the cow"],
  ["cerró", "he or she closed"],
  ["cerraron", "they closed"],
  ["miró", "he or she looked at"],
  ["limpió", "he or she cleaned"],
  ["miraron", "they looked at"],
  ["limpiaron", "they cleaned"],
  ["el cerdo", "the pig"],
  ["aprendieron", "they learned"],
  ["escribió", "he or she wrote"],
  ["abrió", "he or she opened"],
  ["aprendió", "he or she learned"],
  ["escribieron", "they wrote"],
  ["abrieron", "they opened"],
  ["el búho", "the owl"],
  ["cocinaron", "they cooked"],
  ["fue", "he or she went"],
  ["lavaron", "they washed"],
  ["fueron", "they went"],
  ["lavó", "he or she washed"],
  ["cocinó", "he or she cooked"],
  ["el pez", "the fish"],
  ["estuvo", "he or she was"],
  ["estuvieron", "they were"],
  ["comió", "he or she ate"],
  ["comieron", "they ate"],
  ["salió", "he or she went out"],
  ["salieron", "they went out"],
  ["la nieve", "the snow"],
  ["practicamos", "we practiced"],
  ["viajamos", "we traveled"],
  ["caminamos", "we walked"],
  ["disfrutamos", "we enjoyed"],
  ["pasamos", "we passed"],
  ["nadamos", "we swam"],
  ["bebimos", "we drank"],
  ["dormimos", "we slept"],
  ["vimos", "we saw"],
  ["comimos", "we ate"],
  ["corrimos", "we ran"],
  ["anoche", "last night"],
  ["querido", "dear"],
  ["fuimos", "we went"],
  ["bailamos", "we danced"],
  ["cenamos", "we had dinner"],
  ["montamos", "we rode"],
  ["visitamos", "we visited"],
  ["escuchamos", "we listened"],
  ["el barco", "the boat"],
  ["conocimos", "we met"],
  ["aprendimos", "we learned"],
  ["estuvimos", "we were"],
  ["visitaron", "they visited"],
  ["miramos", "we looked at"],
  ["viajaron", "they traveled"],
  ["caminaste", "you walked"],
  ["viajó", "he or she traveled"],
  ["disfruté", "I enjoyed"],
  ["disfrutó", "he or she enjoyed"],
  ["bebió", "he or she drank"],
  ["conocieron", "they met"],
  ["abrí", "I opened"],
  ["salí", "I left"],
  ["abriste", "you opened"],
  ["saliste", "you went out"],
  ["hiciste", "you did"],
  ["hicimos", "we did"],
  ["visitó", "he or she visited"],
  ["hice", "I did"],
  ["disfrutaste", "you enjoyed"],
  ["caminé", "I walked"],
  ["disfrutaron", "they enjoyed"],
  ["cogimos", "we took"],
  ["hicieron", "they did"],
  ["bebieron", "they drank"],
  ["conoció", "he or she met"],
  ["escribí", "I wrote"],
  ["hizo", "he or she did"],
  ["escribiste", "you wrote"],
  ["ninguno de", "none of"],
  ["compré", "I bought"],
  ["compró", "he or she bought"],
  ["ciento", "one hundred"],
  ["nadie", "nobody"],
  ["elegir", "to choose"],
  ["pobre", "poor"],
  ["ninguno", "none"],
  ["último", "last"],
  ["ay", "ouch"],
  ["completamente", "completely"],
  ["mi nuevo", "my new"],
  ["con nadie", "with nobody"],
  ["segundo", "second"],
  ["tercero", "third"],
  ["primer", "first"],
  ["buen", "good"],
  ["pagó", "he or she paid"],
  ["olvidar", "to forget"],
  ["ningún", "no"],
  ["tercer", "third"],
  ["gran", "great"],
  ["doscientos", "two hundred"],
  ["pagamos", "we paid"],
  ["algún", "some"],
  ["la amarilla", "the yellow one"],
  ["el rojo", "the red one"],
  ["encontré", "I found"],
  ["cojo", "I take"],
  ["el azul", "the blue one"],
  ["coger", "to take"],
  ["la vida", "the life"],
  ["coge", "he or she takes"],
  ["ahí", "there"],
  ["el mío", "mine"],
  ["encontraste", "you found"],
  ["la tuya", "yours"],
  ["el anuncio", "the advertisement"],
  ["eliges", "you choose"],
  ["las nuestras", "ours"],
  ["querer", "to want"],
  ["elijo", "I choose"],
  ["pagaste", "you paid"],
  ["elegimos", "we choose"],
  ["gracioso", "funny"],
  ["duro", "hard"],
  ["la oración", "the sentence"],
  ["emocionante", "exciting"],
  ["encontró", "he or she found"],
  ["usando", "using"],
  ["caluroso", "hot (weather)"],
  ["el clima", "the weather"],
  ["llover", "to rain"],
  ["nevar", "to snow"],
  ["comenzar", "to begin"],
  ["encontrarme", "to meet up"],
  ["lloviendo", "raining"],
  ["comenzamos", "we began"],
  ["nevando", "snowing"],
  ["encantar", "to love"],
  ["me encuentro", "I feel"],
  ["duermo", "I sleep"],
  ["el árbol", "the tree"],
  ["comienzo", "I begin"],
  ["la lluvia", "the rain"],
  ["caminó", "he or she walked"],
  ["haber", "to have"],
  ["corrió", "he or she ran"],
  ["fueron unos", "there were some"],
  ["fue un", "it was a"],
  ["nos encontramos", "we met up"],
  ["nevó", "it snowed"],
  ["montaste", "you rode"],
  ["llovió", "it rained"],
  ["la nacionalidad", "the nationality"],
  ["vine", "I came"],
  ["hay algún", "is there any (masculine)"],
  ["hay alguna", "is there any (feminine)"],
  ["trescientos", "three hundred"],
  ["viniste", "you came"],
  ["espere", "wait (formal command)"],
  ["nos vemos", "see you"],
  ["alguien", "someone"],
  ["cuatrocientos", "four hundred"],
  ["algo de", "some of"],
  ["querría", "I would like"],
  ["fumar", "to smoke"],
  ["siguiente", "next"],
  ["encontramos", "we found"],
  ["vinieron", "they came"],
  ["compraste", "you bought"],
  ["vinimos", "we came"],
  ["entonces", "then"],
  ["quinientos", "five hundred"],
  ["posible", "possible"],
  ["el ruido", "the noise"],
  ["encontraron", "they found"],
  ["compraron", "they bought"],
  ["disfrutando", "enjoying"],
  ["caminaron", "they walked"],
  ["seiscientos", "six hundred"],
  ["estudió", "he or she studied"],
  ["habló", "he or she spoke"],
  ["preocuparse", "to worry"],
  ["enseñando", "teaching"],
  ["sentarnos", "to sit down (ourselves)"],
  ["nos sentamos", "we sat down"],
  ["necesitar", "to need"],
  ["el ejemplo", "the example"],
  ["empezó", "he or she started"],
  ["responder", "to answer"],
  ["empecé", "I started"],
  ["parar", "to stop"],
  ["cogí", "I took"],
  ["comprender", "to understand"],
  ["viste", "you saw"],
  ["vi", "I saw"],
  ["encuentra", "he or she finds"],
  ["me preocupo", "I worry"],
  ["vivió", "he or she lived"],
  ["morir", "to die"],
  ["yo fui", "I went"],
  ["setecientos", "seven hundred"],
  ["ochocientos", "eight hundred"],
  ["practicó", "he or she practiced"],
  ["llegué", "I arrived"],
  ["practiqué", "I practiced"],
  ["recordamos", "we remembered"],
  ["novecientos", "nine hundred"],
  ["miré", "I looked at"],
  ["el recuerdo", "the memory"],
  ["llegaste", "you arrived"],
  ["comencé", "I began"],
  ["comenzó", "he or she began"],
  ["bailé", "I danced"],
  ["sentirse", "to feel"],
  ["la boca", "the mouth"],
  ["el cuerpo", "the body"],
  ["despertarme", "to wake up (myself)"],
  ["encima", "on top of"],
  ["ah", "ah"],
  ["nos despertamos", "we woke up"],
  ["quedar", "to stay"],
  ["la nariz", "the nose"],
  ["la cabeza", "the head"],
  ["me despierto", "I wake up"],
  ["oigo", "I hear"],
  ["oír", "to hear"],
  ["la pierna", "the leg"],
  ["oyes", "you hear"],
  ["acordarse", "to remember"],
  ["el brazo", "the arm"],
  ["me levanté", "I got up"],
  ["acabar", "to finish"],
  ["oímos", "we heard"],
  ["la barba", "the beard"],
  ["me acuerdo", "I remember"],
  ["cerré", "I closed"],
  ["lleva puesto", "he or she is wearing"],
  ["soñar", "to dream"],
  ["gustó", "he or she liked"],
  ["nos acordamos", "we remembered"],
];
