const spanish_a2_1 = [
  [`morado`, `purple (masc.)`],
  [`fantástico`, `meant, great, fantastic (masc.)`],
  [`odiar`, `hate, (to) hate, to loathe`],
  [`acostarse`, `to go to bed, go to bed, lie down`],
  [`allí`, `there`],
  [`me acuesto`, `(I) go to bed`],
  [`nos acostamos`, `(we) went to bed, go`],
  [`gustaron`, `(I) liked, (they) like, (I) like (pl.)`],
  [`cuando`, `when`],
  [`preferimos`, `preferred, (we) preferred, (we) prefer (pl.)`],
  [`el gimnasio`, `gym, gym's`],
  [`de vez en cuando`, `every once in a while, once in a while, now and then`],
  [`generalmente`, `generally, usually`],
  [`el golf`, `golf`],
  [`el ajedrez`, `chess`],
  [`frecuentemente`, `frequently, often`],
  [`dificilísimo`, `really difficult (masc.)`],
  [`facilísimo`, `really easy (masc.)`],
  [`grandísimo`, `really big, very big, really large (masc.)`],
  [`encantó`, `(?) did you love, (I) loved`],
  [`encantaron`, `(?) did you love (pl.)`],
  [`cansadísimo`, `really tired (masc.)`],
  [`el proyecto`, `project's, project, plan's`],
  [`jamás`, `never, ever`],
  [`espera`, `expected, (she) hopes, hold on`],
  [`tampoco`, `neither, either`],
  [`el colega`, `colleague's, pal, colleague`],
  [`disponible`, `available`],
  [`escuche`, `hear, (you) listen up, (he/she) hears`],
  [`ayude`, `help, (you) help, helps`],
  [`use`, `uses, (you) use, wear`],
  [`la reunión`, `party's, meeting, réunion`],
  [`tú pones`, `you put, you place, you set`],
  [`ve`, `(she) sees, hears, (you) go`],
  [`haz`, `(you) make, make, (you) do`],
  [`tú vas`, `go`],
  [`tú haces`, `do`],
  [`pon`, `put, (you) put, place`],
  [`la empresa`, `company's, business's, business`],
  [`ponga`, `(you) put, put`],
  [`usted pone`, `put, place, set`],
  [`haga`, `(you) make, it's, undergo`],
  [`usted va`, `you go, you are going, you do go`],
  [`usted hace`, `you do, you make, you prepare`],
  [`vaya`, `go, (you) go, (I) go`],
  [`de niño`, `as a child (masc.)`],
  [`el vóleibol`, `volleyball`],
  [`jugaba`, `(she) would play, (I) used to play, (?) did she use to play`],
  [`de niña`, `as a child, when I was a girl, as a little girl (fem.)`],
  [`jugabas`, `(?) did you use to play, (you) played, (you) used to play`],
  [`montaba`, `(I) rode, (I) used to ride, (he) was riding`],
  [`montabas`, `(?) did you use to ride, (you) used to ride`],
  [`el cereal`, `cereal, grain`],
  [`los bosques`, `woods, woodland, forests`],
  [`la galleta`, `cracker, biscuit, slap`],
  [`vivías`, `(you) used to live, (?) did you use to live`],
  [`vivía`, `(she) lived, (I) used to live, live`],
  [`comía`, `eaten, (?) did she use to eat, (I) ate`],
  [`comías`, `ate, (?) did you use to eat, (you) were eating`],
  [`amable`, `kind, softer, nice`],
  [`el alumno`, `student, classmate's`],
  [`tranquilo`, `calm, peaceful, quiet (masc.)`],
  [`nadaba`, `(I) used to swim, (I) was swimming, use to swim`],
  [
    `nadabas`,
    `(you) were swimming, (?) did you use to swim, (?) were you swimming`,
  ],
  [`era`, `they were, age, were`],
  [`eras`, `(you) used to be, were, (you) were being`],
  [`la patineta`, `skateboard`],
  [`leías`, `(you) were reading, reading, (?) did you use to read`],
  [`tenías`, `(you) were having, knew, (you) had`],
  [
    `estudiabas`,
    `(?) did you use to study, (you) studied, (you) used to study`,
  ],
  [`leía`, `(I) used to read, (she) was reading, (she) read`],
  [`tenía`, `(he) had, (he) used to have, have`],
  [`estudiaba`, `(I) was studying, trained, (I) used to study`],
  [`el asado`, `baked, grilled, barbecue`],
  [`el champán`, `champagne`],
  [`el chef`, `chef`],
  [`pedir`, `to order, order, to ask for`],
  [`el alcohol`, `alcohol`],
  [`servir`, `serving, (to) serve, serve`],
  [`estupendo`, `wonderful, great, beautiful (masc.)`],
  [`vegetariano`, `vegetarian (masc.)`],
  [`lleno`, `full, crowded, filled (masc.)`],
  [`saludable`, `healthy`],
  [`buen provecho`, `bon appétit, enjoy your meal`],
  [`el extra`, `extra, option`],
  [`el hielo`, `ice`],
  [`algo más`, `something`],
  [`el especial del día`, `special of the day, daily special, dish of the day`],
  [`me puede traer`, `can you bring me, could you bring me, can bring me`],
  [`pedimos`, `(we) order, asked, (we) ask (pl.)`],
  [`servimos`, `(we) are serving, (we) worked, (we) functioned (pl.)`],
  [`excelente`, `excellent, fine, great`],
  [`el aceite`, `oil`],
  [`traer`, `(?) could you bring, (to) bring, (to) fetch`],
  [`los panes`, `bread`],
  [`la excursión`, `hiking, hike, outing`],
  [`qué hacemos`, `do`],
  [`el cómic`, `comic`],
  [`el teatro`, `drama, theater, movie theater`],
  [`el descanso`, `rest, break`],
  [`el hip-hop`, `hip-hop`],
  [`el lago`, `lake, lago`],
  [`el espectáculo`, `entertainment, show, performance`],
  [`la obra de teatro`, `play`],
  [`el jazz`, `jazz`],
  [`a lo mejor`, `maybe`],
  [`qué tal si`, `how about`],
  [`la motocicleta`, `motorcycle`],
  [`el hobby`, `hobby`],
  [`desafortunadamente`, `unfortunately, sadly`],
  [`el ciclismo`, `cycling, biking`],
  [`la tradición`, `tradition`],
  [`visitaba`, `(he) used to visit, (she) used to visit, (he) visited`],
  [`durante`, `during, for`],
  [
    `jugaban`,
    `(they) used to play, (?) did you use to play, (they) played (pl.)`,
  ],
  [
    `visitaban`,
    `(they) used to visit, visited, (?) did you use to visit (pl.)`,
  ],
  [`el día de acción de gracias`, `Thanksgiving Day`],
  [`tenían`, `(they) used to have, have, (?) did you use to have (pl.)`],
  [`la nochevieja`, `New Year's Eve`],
  [`vivían`, `(?) did they use to live, (?) did they live, lived (pl.)`],
  [
    `comían`,
    `(they) used to eat, (they) would eat, (?) did you use to eat (pl.)`,
  ],
  [`la tarjeta`, `card, business card`],
  [`especial`, `special`],
  [`el juguete`, `toy`],
  [`la navidad`, `Christmas, Yule, Xmas`],
  [`eran`, `were, (they) were, (it) was (pl.)`],
  [`la nochebuena`, `Christmas Eve`],
  [`la iglesia`, `church, church's, church’s`],
  [`jugábamos`, `(we) used to play, (we) were playing, (we) played (pl.)`],
  [`éramos`, `were, (we) were, (we) were being (pl.)`],
  [`el año nuevo`, `New Year's`],
  [`teníamos`, `produced, knew, (we) used to have (pl.)`],
  [`comíamos`, `(we) used to eat, (we) ate, (we) were eating (pl.)`],
  [
    `vivíamos`,
    `(we) used to live, (we) was/were alive, (we) were living (pl.)`,
  ],
  [`la invitación`, `invitation, invite`],
  [`qué te parece`, `What do you think, (?) How does it sound`],
  [`mira`, `look, look at, looks at`],
  [`cómo te va`, `how's it going`],
  [`donde`, `where`],
  [`oye`, `hears, (you) hear, hey`],
  [`el centro`, `center's, center, focus`],
  [`la sorpresa`, `surprise, favor`],
  [`el patio`, `backyard, yard, patio`],
  [`genial`, `brilliant, cool, Great!`],
  [`qué le parece`, `(?) what do you think`],
  [`acompañar`, `go with, to go with, accompany`],
  [`cómo le va`, `how are you, how is it going, how do you do`],
  [`el bar`, `bar, bars, bar's`],
  [`quiénes`, `who (pl.)`],
  [`ven`, `(they) are seeing, (they) are watching, (they) watch (pl.)`],
  [`parece`, `(?) does it seem, appears, look`],
  [`la pena`, `shame, pity`],
  [`conversar`, `to converse, chat, converse`],
  [`la parrilla`, `grill, grate, barbecue's`],
  [`llegue`, `(you) arrive, arrives, (I) get`],
  [`la medianoche`, `midnight`],
  [`el mediodía`, `noon, midday`],
  [`baila`, `(he) dances, dancing, dance`],
  [`llega`, `is, (you) arrive, (it) reaches`],
  [`el primo`, `cousin, cousin's`],
  [`el compañero de cuarto`, `roommate`],
  [`hace`, `is, (you) make, makes`],
  [`dije`, `said, (I) said, (I) told`],
  [`tuve`, `(I) had, got, have`],
  [`el traje`, `suit, (I) brought, costume's`],
  [`la aventura`, `adventure, affair`],
  [`el campamento`, `campground, camping, camp`],
  [`cuento`, `I'm telling, rely on, tell`],
  [`el momento`, `moment, time, timing`],
  [`tuviste`, `(you) had, had, (?) did you have`],
  [`dijiste`, `said, (?) did you tell, (?) did you say`],
  [`trajiste`, `get, got, (?) did you bring`],
  [`el compañero de clase`, `classmate`],
  [`el álbum`, `album`],
  [`tuvo`, `(?) did she have, experienced, (he) had`],
  [`el abuelito`, `grandpa, grandfather, granddad`],
  [`trajo`, `(?) did you bring, (he) brought, (she) brought`],
  [`recibir`, `receive, get, to get`],
  [`dijo`, `(he) said, (he) told, said`],
  [`el premio`, `prize, award`],
  [`el diploma`, `diploma, certificate, degree`],
  [`me acordé`, `(I) remembered, (I) didn't remember`],
  [`el juego de mesa`, `board game`],
  [`la luz`, `light's, lights, Luz`],
  [`el portátil`, `laptop, portable`],
  [`la lámpara`, `lit, lamp, lanterns`],
  [`la cafetera`, `coffee maker, coffee machine`],
  [`los muebles`, `furniture`],
  [`apagar`, `to turn off, turn off, switch off`],
  [`el televisor`, `television, setting, TV`],
  [`apagado`, `off, turned off (masc.)`],
  [`pintado`, `painted, drawn (masc.)`],
  [`la alfombra`, `carpet, rug`],
  [`la estufa`, `stove, heater, heater's`],
  [`el sillón`, `armchair, chair`],
  [`la lavadora`, `washing machine`],
  [`el espejo`, `mirror, mirror's`],
  [`encender`, `to turn on, turn on, switch on`],
  [`creo que deberías`, `I think you should`],
  [`el sofá`, `sofa, couch, sofas`],
  [`perdido`, `wasting, waste, gotten lost (masc.)`],
  [`dormido`, `fallen asleep, asleep, slept (masc.)`],
  [`encendido`, `turned on, open, on (masc.)`],
  [`creo que debería`, `I think I should`],
  [`encendemos`, `(we) turn on (pl.)`],
  [`el estómago`, `stomach, stomach's`],
  [`la espalda`, `back, backs`],
  [`la cita`, `appointment, date, dates`],
  [`el cuello`, `neck, collar`],
  [`el dedo`, `finger`],
  [`doler`, `to hurt, hurt, to be in pain`],
  [`mover`, `get around, (to) move, driven`],
  [`el dr.`, `Dr.`],
  [`el enfermero`, `male nurse, nurse, nurse's`],
  [`me cepillé`, `brushed`],
  [`el jabón`, `soap`],
  [`descansar`, `rest, to rest`],
  [`el dolor`, `pain, ache, grief`],
  [`hay que`, `one must, we've got to`],
  [`pálido`, `pale (masc.)`],
  [`el ejercicio`, `exercise`],
  [`la salud`, `health`],
  [`duele`, `(it) is hurting, (it) hurts, (?) does it hurt`],
  [`cuidar`, `(to) care for, (to) watch, (to) take care`],
  [`deberías`, `supposed to, (you) should, you'd`],
  [`el cigarrillo`, `cigarette, cigarettes`],
  [`el accidente`, `accident, crash`],
  [`el dentista`, `dentist, dentist's`],
  [`la actividad`, `activity`],
  [`duelen`, `are aching, sore, ache (pl.)`],
  [`debería`, `there should, (you) should, (I) should`],
  [`semanal`, `week's, weekly, week’s`],
  [`la noticia`, `news`],
  [`el canal`, `channel, canal`],
  [`el internet`, `Internet, online, web`],
  [`la verdad`, `truth`],
  [`la información`, `information, data's`],
  [`el documento`, `document, paper`],
  [`el archivo`, `attachments, file, filing`],
  [`correcto`, `well-mannered, right, correct (masc.)`],
  [`tuvimos`, `(we) had, have, had (pl.)`],
  [`trajimos`, `(we) brought (pl.)`],
  [`dijimos`, `(we) told, said, tell (pl.)`],
  [`la revista`, `magazine, magazines, journal`],
  [`leí`, `(I) read, read`],
  [`dijeron`, `said, (?) did they say, (they) said (pl.)`],
  [`tuvieron`, `(?) did they have, (they) had, have (pl.)`],
  [`trajeron`, `bring, (they) brought, (?) did you bring (pl.)`],
  [`enviar`, `let's, getting, forward`],
  [`entiendes`, `understand, get, (?) do you understand`],
  [`el ingeniero`, `engineer, an engineer`],
  [`la máquina`, `machine`],
  [`las fábricas`, `factories, plants, mills`],
  [`el elefante`, `elephant`],
  [`el conejo`, `rabbit`],
  [`fuerte`, `bad, strong, brighter`],
  [`peligroso`, `dangerous (masc.)`],
  [`los perros`, `dogs`],
  [`los gatos`, `the cats`],
  [`la verdura`, `vegetable, verdure, green`],
  [`útil`, `useful, helpful`],
  [`los lunes`, `mondays`],
  [`las frutas`, `the fruits`],
  [`los padres`, `parent`],
  [`los médicos`, `doctors`],
  [`pesado`, `heavier, heavy, annoying (masc.)`],
  [`el baloncesto`, `basketball`],
  [`la gramática`, `grammar`],
  [`el ciclismo`, `cycling, bike racing, bicycle racing`],
  [`el ajedrez`, `chess`],
  [`el fútbol`, `soccer`],
  [`los deportes`, `sports`],
  [`el dinosaurio`, `dinosaur, dinosaur's`],
  [`el oso`, `bear, bear's`],
  [`el agricultor`, `farmer`],
  [`el insecto`, `insect`],
  [`los maestros`, `teachers`],
  [`el español`, `Spanish`],
  [`el inglés`, `English, the English language, Englishman`],
  [`la copa`, `drink, glass, cup`],
  [`el tazón`, `bowl, mug`],
  [`aprobar`, `(to) pass, approve, pass`],
  [`varios`, `many, several, some (masc. pl.)`],
  [`leíste`, `read, (you) read, (?) did you read`],
  [`leyeron`, `(you) read, (?) did you read, read (pl.)`],
  [`leímos`, `(we) read, read (pl.)`],
  [`leyó`, `(he) read, (they) read, read`],
  [`el cuaderno`, `notebook, binder`],
  [`el libro de texto`, `text, textbook`],
  [`la química`, `chemistry`],
  [`la historia`, `history, story, story's`],
  [`ganar`, `to win, (to) beat, (to) gain`],
  [`tomé`, `caught, (I) had, made`],
  [`el corredor`, `runner, hall, aisles`],
  [`el kilómetro`, `kilometer`],
  [`la carrera`, `degree, career, race`],
  [`el equipo`, `gear, team, outfit`],
  [`el balonmano`, `handball`],
  [`la geografía`, `geography`],
  [`el mecánico`, `mechanic`],
  [`ibas`, `(you) were going to, were, (?) did you use to go`],
  [`el refresco`, `soda, pop`],
  [`el dibujo animado`, `cartoon`],
  [`los dulces`, `candies, sweet, sweets`],
  [`íbamos`, `(we) were going, (we) went out, we'd go (pl.)`],
  [`iban`, `(they) went, (they) used to go, going (pl.)`],
  [`el patio de juego`, `playground`],
  [`el rey`, `king, rey`],
  [`el salón`, `hall, classrooms', classroom's`],
  [`el castillo`, `castle's, castle, castle’s`],
  [`había una vez`, `once upon a time`],
  [`el violín`, `violin`],
  [`el mar`, `sea, mar`],
  [`la montaña`, `mountain, mountains, ranges`],
  [`la oveja`, `sheep`],
  [`intentar`, `to try`],
  [`rezar`, `(to) pray, says`],
  [`la sortija`, `ring`],
  [`el artista`, `actor, artist, actress`],
  [`el campo`, `field, country, countryside`],
  [`lentamente`, `slowly`],
  [`llorar`, `crying, (to) cry, cry`],
  [`la guerra`, `wartime, war, war's`],
  [`el bailarín`, `dancer`],
  [`hasta`, `until, to, up until`],
  [`el turista`, `tourist`],
  [`la isla`, `island, isla`],
  [`la idea`, `idea, thought, clue`],
  [`bienvenido`, `welcome (masc.)`],
  [`la catedral`, `cathedral`],
  [`planear`, `setting, planning, planned`],
  [`reservar`, `reserving, setting, (to) book`],
  [`el pasajero`, `passenger, temporary, passenger's`],
  [`el estadio`, `stadium, parked`],
  [`el equipaje`, `luggage, baggage, bag's`],
  [`la ópera`, `opera house, opera, opera's`],
  [`la identificación`, `ID, identification, id.`],
  [`el coche`, `car, automobile, coche`],
  [`el vuelo`, `flight, (I) fly, flight's`],
  [`confortable`, `comfortable`],
  [`el tranvía`, `tram`],
  [`el asiento`, `chair, seat, seats`],
  [`internacional`, `international, internationally`],
  [`regresar`, `to return, (to) give back, (to) go/come back`],
  [`agradable`, `pleasant, nice, likable`],
  [`el helicóptero`, `helicopter`],
  [`la capital`, `capital city, capital, capital's`],
  [`los servicios`, `services, restrooms, restroom`],
  [`en todas partes`, `everywhere, all over the place`],
  [`el nieto`, `grandson, grandchild, grandson's`],
  [`enfadado`, `maddest, annoyed, mad (masc.)`],
  [`loco`, `crazy, maddest (masc.)`],
  [`interesado`, `interested, concerned (masc.)`],
  [`estábamos`, `(we) were, lay, were (pl.)`],
  [`sin duda`, `surely, certainly, definitely`],
  [`el invitado`, `invited, guest, invite`],
  [`el vecino`, `neighbor, neighboring, neighbor's`],
  [`satisfecho`, `satisfied, pleased (masc.)`],
  [`casar`, `marrying, (to) get married, married`],
  [`excepto`, `except`],
  [`probablemente`, `probably, likely`],
  [`seco`, `dry, (I) dry, smarter (masc.)`],
  [`el traje de baño`, `swimsuit, swimsuits, bathing suit`],
  [`soleado`, `sunny, bright (masc.)`],
  [`mojado`, `wet (masc.)`],
  [`el paraguas`, `umbrella, umbrellas, brolly`],
  [`romper`, `to break`],
  [`las gafas de sol`, `sunglasses`],
  [`el cajón`, `case, drawer, box`],
  [`el mango`, `mango`],
  [`vacío`, `empty, vacuum (masc.)`],
  [`el motor`, `motor, engine, engine's`],
  [`fresco`, `newer, cool, fresh (masc.)`],
  [`el tambor`, `drum`],
  [`el océano`, `ocean`],
  [`el mercado`, `markets, market, market's`],
  [`entrar`, `to go in, (to) come in, (to) enter`],
  [`pescar`, `to fish, (to) fish, (to) go fish`],
  [`el video`, `video`],
  [`la limonada`, `lemonade`],
  [`reparar`, `to fix, (to) repair, (to) fix`],
  [`la rata`, `rat`],
  [`la cafetería`, `cafeteria, coffee shop, cafe`],
  [`el tío`, `stick, uncle, stuck`],
  [`las ciencias`, `sciences`],
  [`el mono`, `monkey, cute, mona`],
  [`la tía`, `aunt, aunt's`],
  [`asar`, `barbecuing, barbecue, grill`],
  [`el rugby`, `rugby`],
  [`el gerente`, `manager, manager's`],
  [`el horario`, `schedule, timetable, hour`],
  [`la carpeta`, `folder, binder`],
  [`adentro`, `inside, in, indoors`],
  [`diciendo`, `thinking, calling, telling`],
  [`pidiendo`, `wanting, asking, asking for`],
  [`el pintor`, `painter, artist`],
  [`el trabajador`, `worker, hardworking`],
  [`trayendo`, `getting, bringing`],
  [`oyendo`, `listening to, getting, hearing`],
  [`muriendo`, `dying`],
  [`yendo`, `going, leaving`],
  [`durmiendo`, `falling asleep, sleeping`],
  [`increíble`, `amazing, incredible, unbelievable`],
  [`el empresario`, `businessman, entrepreneur`],
  [`el presidente`, `president`],
  [`la compañía`, `company's, company, company’s`],
  [`el programa`, `show, curriculum, program`],
  [`completar`, `(to) complete, complete, (to) finish`],
  [`repetir`, `to repeat`],
  [`el cocinero`, `cook`],
  [`el edificio`, `building, building's`],
  [`el director`, `manager, supervisor, principal`],
  [`la llamada`, `call, called, phone call`],
  [`afuera`, `outside, out, outdoors`],
  [`repitiendo`, `repeating`],
  [`la serpiente`, `serpent, snake, serpiente`],
  [`interesarse`, `to be interested, to take an interest, to concern oneself`],
  [
    `me llamaba`,
    `(he/she/it/you) called (me), (he/she/it/you) used to call (me), (he/she/it/you) was/were calling (me)`,
  ],
  [`la naturaleza`, `nature`],
  [`creer`, `thought, believing, thoughts`],
  [`el corazón`, `heart`],
  [`el desierto`, `deserted, loneliest, desert`],
  [`el león`, `lion, león`],
  [`el visitante`, `visiting, visitor, visit`],
  [`la miel`, `honey, mel`],
  [`propio`, `messenger, own, one's (masc.)`],
  [`el collar`, `necklace, collars`],
  [`la vista`, `view, sight, to dress`],
  [`el oro`, `gold`],
  [`simple`, `simple, simpleton, simple-minded`],
  [`el pato`, `duck`],
  [`silvestre`, `wild`],
  [`la magia`, `magic`],
  [`el puente`, `long weekend, bridge`],
  [`estar de acuerdo`, `agree, agreed, agreeing`],
  [`el siglo`, `century, century's`],
  [`la razón`, `right, reason, cause`],
  [`la vez`, `time`],
  [`ocurrir`, `comes, (to) occur, come`],
  [`supe`, `know, knew, found out`],
  [`pude`, `(I) was able, (I) could, could`],
  [`puse`, `stood, gave, (I) put`],
  [`la charla`, `chat`],
  [`pudiste`, `able, (you) were able to, could`],
  [`supiste`, `(you) knew, know, knew`],
  [`pusiste`, `(you) put, make, get`],
  [`el área`, `area's, area, region's`],
  [`supo`, `know, (she) knew`],
  [`por fin`, `finally`],
  [`preparar`, `to prepare, (to) make`],
  [`pudo`, `(he) could, (she) was able to, could`],
  [`decidir`, `decides, agrees, decide`],
  [`puso`, `stood, gave, (she) turned`],
  [`prepararse`, `(to) get ready, (to) have a, (to) prepare`],
  [`la colina`, `hill`],
  [`el nacimiento`, `birth`],
  [`el principio`, `(I) begin, beginning, (I) commence`],
  [`miles`, `thousands (pl.)`],
  [`de acuerdo`, `agree, agreed`],
  [`me duché`, `(I) showered, (I) took a shower`],
  [`la mermelada`, `jam, jelly`],
  [`la tostada`, `toast, toasted`],
  [`me desperté`, `(I) waked/woke (up), (I) whetted/whet, (I) aroused`],
  [`me lavé`, `washed, wash`],
  [`la pasta`, `pasta's, pasta, pulp`],
  [`almorcé`, `(I) ate lunch, (I) had lunch, eat lunch`],
  [`me preocupé`, `I worried, I became worried, I got worried`],
  [`el calcetín`, `sock`],
  [`suave`, `soft, lit, gentle`],
  [`me reuní`, `met`],
  [`me probé`, `tried`],
  [`vestirse`, `dressed, dress, to get dressed`],
  [`la corbata`, `tie`],
  [`la bufanda`, `scarf`],
  [`me acosté`, `lay`],
  [`el peine`, `comb`],
  [`el uniforme`, `even, uniform`],
  [`el suéter`, `sweater, pullover, jersey's`],
  [`me quedé`, `(I) stayed, (I) fell, fall`],
  [`el champú`, `shampoo`],
  [`el maquillaje`, `makeup`],
  [`dormiste`, `(you) slept, (?) did you fall asleep, (you) fell asleep`],
  [`durmieron`, `sleep, (they) slept, (?) did they sleep (pl.)`],
  [`durmió`, `sleep, (he) slept, (?) did she sleep`],
  [`el yogur`, `yogurt, yogurt's`],
  [`la cebolla`, `onion`],
  [`la lata`, `can`],
  [`el kilogramo`, `kilogram`],
  [`el litro`, `liter, liters`],
  [`el jamón`, `ham`],
  [`en oferta`, `on sale`],
  [`la pimienta`, `pepper`],
  [`y medio`, `and a half`],
  [`gastar`, `spending, spend, worn`],
  [`la lista`, `list, smart, ready`],
  [`la variedad`, `variety`],
  [`el champiñón`, `mushroom`],
  [`la pera`, `pear`],
  [`la billetera`, `wallet`],
  [`el limón`, `lemon`],
  [`el estuche`, `case, box, pencil case`],
  [`el compañero`, `colleague's, roommate's, classmate's`],
  [`avanzado`, `advanced, made progress (masc.)`],
  [`el detalle`, `touch, gift, go into detail!`],
  [`la regla`, `ruler, rule, period`],
  [`los libros de ejercicios`, `workbooks`],
  [`claramente`, `clearly`],
  [
    `la diferencia`,
    `(you-formal) differentiate between, (he/she/it) differentiates between, difference`,
  ],
  [`el consejo`, `advice, counsel, tip`],
  [`la instrucción`, `instruction, charge`],
  [`decirme`, `(to) tell me, telling me`],
  [`darme`, `(to) give me, giving me, give`],
  [`el calendario`, `calendar, scheduling`],
  [`la mochila`, `backpack, bag's`],
  [`darte`, `give you`],
  [`explicar`, `to explain, (to) understand`],
  [`decirnos`, `(to) say (us), (to) think (us), (to) say to oneself (us)`],
  [`el nivel`, `level, standards, floor`],
  [`darle`, `giving, (to) give him, give her`],
  [`expliqué`, `(I) explained, explain, (I) understood`],
  [`decirles`, `(to) tell them, tell (pl.)`],
  [`maravilloso`, `wonderful, marvelous, magical (masc.)`],
  [`tanto`, `so much, both, so (masc.)`],
  [`la postal`, `postcard, postal`],
  [`a lo largo del`, `along, throughout the, along the`],
  [`el rompecabezas`, `puzzle, jigsaw, jigsaw puzzle`],
  [`el bádminton`, `badminton`],
  [`la raqueta`, `racket, snowshoe, rake`],
  [`la cometa`, `kite`],
  [`coleccionar`, `(to) collect, collect, collecting`],
  [`esquiar`, `ski`],
  [`acampar`, `camping, camp`],
  [`el velero`, `sailboat, sail`],
  [`la estampilla`, `stamp`],
  [`navegar`, `surf, sailing, sail`],
  [`el hockey`, `hockey`],
  [`prestar`, `gave, pay, pays`],
  [`el dibujo`, `(I) draw, designed, drawing`],
  [`navegué`, `(I) sailed`],
  [`el pop`, `pop`],
  [`has`, `you're, you've, (you) have`],
  [`bastante`, `quite, enough, fairly`],
  [`estudiado`, `studied, trained (masc.)`],
  [`el estado`, `condition, you've, marital`],
  [`trabajado`, `worked, acted (masc.)`],
  [`he`, `I've, have, I have`],
  [`el peligro`, `(I) am at risk, peril, danger`],
  [`el obrero`, `worker, laborer`],
  [`robar`, `robs, drawn, robbing`],
  [`ha`, `has, it's, she's`],
  [`aprendido`, `learns, learned/learnt, learn (masc.)`],
  [`comido`, `eaten, had, ate (masc.)`],
  [`todavía`, `yet, still`],
  [`la policía`, `policewoman, policeman, police`],
  [`salvaje`, `brutal, wild, savage`],
  [`han`, `you've, they, (you) have (pl.)`],
  [`vivido`, `lived, existed (masc.)`],
  [`hemos`, `ve, we've, we're (pl.)`],
  [`ido`, `left, been, been to (masc.)`],
  [`recibido`, `got, gotten, received (masc.)`],
  [`terrible`, `terrible, horrible, desperate`],
  [`extraño`, `(I) miss, peculiar, weird (masc.)`],
  [`nacional`, `internal, country's, national`],
  [`el fuego`, `fire`],
  [`robado`, `stolen, robbed, stealing (masc.)`],
  [`llegado`, `gotten, come, arrived (masc.)`],
  [`la electricidad`, `electricity`],
];
