const spanish = [
  [`mujer`, `woman, wife, lady`],
  [`el`, `the, your, her`],
  [`un`, `a, an, one`],
  [`niña`, `girl, child, daughter`],
  [`la`, `the, your, her`],
  [`yo`, `I, me`],
  [`una`, `a, an, one`],
  [`hombre`, `man, bloke, guy`],
  [`niño`, `boy, child, kid`],
  [`soy`, `I am, am`],
  [`manzana`, `apple, block`],
  [`come`, `(it) eats, (?) do you eat, (she) eats`],
  [`tú`, `you, you'll`],
  [`él`, `he, him, it`],
  [`eres`, `you're, aren't being, are`],
  [`ella`, `she, her, she'll`],
  [`es`, `is, are you, it's`],
  [`comes`, `ate, (you) are eating, (?) do you eat`],
  [`bebe`, `(he) is drinking, (you) are drinking, (he) drinks`],
  [`pan`, `bread, bar, cake`],
  [`leche`, `milk`],
  [`bebo`, `(I) drink, (I) am drinking, drink`],
  [`como`, `(I) eat, (I) am eating, like`],
  [`agua`, `water`],
  [`bebes`, `(?) do you drink, (you) drink, drink`],
  [`buenas noches`, `good night, good evening`],
  [`hola`, `hello, hi`],
  [`gracias`, `thanks, thank you, party piece`],
  [`buenos días`, `good morning`],
  [`mucho gusto`, `nice to meet you, so nice to meet you`],
  [`adiós`, `goodbye`],
  [`lo siento`, `sorry, I am sorry`],
  [`perdón`, `sorry, excuse me, pardon`],
  [`de nada`, `you're welcome, you are welcome`],
  [`por favor`, `please`],
  [`sí`, `yes, yourself`],
  [`no`, `do not, wasn't, n't`],
  [`inglés`, `English, British, Englishman`],
  [`disculpe`, `excuse me, excuse!, (I/he/she/it/you) excuse`],
  [`hablas`, `(?) do you speak, speak, talking`],
  [`hablo`, `(I) am talking, speak, talking`],
  [`español`, `Spanish, Spaniard, Spanish man`],
  [`taxi`, `taxi, cab`],
  [`necesito`, `need, (I) need, (?) do I need`],
  [`teléfono`, `phone`],
  [`mi`, `my`],
  [`pasaporte`, `passport`],
  [`maleta`, `suitcase`],
  [`en`, `in`],
  [`hotel`, `hotel, hotels`],
  [`aquí`, `here`],
  [`está`, `it is`],
  [`tengo`, `I've got, is there, I'm having`],
  [`reserva`, `reservation`],
  [`dónde`, `where`],
  [`dinero`, `money`],
  [`a`, `to, with, away`],
  [`boleto`, `ticket`],
  [`aeropuerto`, `airport`],
  [`autobús`, `bus`],
  [`tren`, `train`],
  [`tu`, `your`],
  [`museo`, `museum, museums`],
  [`hospital`, `hospital, hospitals`],
  [`baño`, `bathroom`],
  [`calle`, `street`],
  [`banco`, `bank, banks`],
  [`cerrado`, `closed`],
  [`supermercado`, `supermarket`],
  [`tres`, `three`],
  [`uno`, `one`],
  [`restaurante`, `restaurant`],
  [`mesa`, `table`],
  [`personas`, `people`],
  [`para`, `for`],
  [`dos`, `two`],
  [`hamburguesa`, `burger, hamburger`],
  [`sándwich`, `sandwich, sandwiches`],
  [`con`, `with`],
  [`de`, `with, made of, off`],
  [`pescado`, `fish`],
  [`queso`, `cheese`],
  [`carne`, `meat, pork, beef`],
  [`azúcar`, `sugar`],
  [`sin`, `absent, without, with no`],
  [`jugo`, `juice`],
  [`vaso`, `glass`],
  [`café`, `coffee`],
  [`naranja`, `orange`],
  [`taza`, `cup, mug`],
  [`sal`, `salt`],
  [`cuenta`, `check`],
  [`quiero`, `(I) love, (I) want, want`],
  [`tomate`, `tomato`],
  [`ensalada`, `salad`],
  [`pagar`, `to pay`],
  [`o`, `or`],
  [`madre`, `mother`],
  [`inteligente`, `intelligent`],
  [`tiene`, `is, makes, (?) does it have`],
  [`elegante`, `elegant`],
  [`padre`, `father, dad`],
  [`carro`, `car, automobile`],
  [`casa`, `house`],
  [`grande`, `big`],
  [`hermana`, `sister`],
  [`gato`, `cat`],
  [`muy`, `very`],
  [`bonito`, `pretty`],
  [`hermano`, `brother`],
  [`perro`, `dog`],
  [`esposa`, `wife`],
  [`esposo`, `husband`],
  [`apartamento`, `apartment`],
  [`abuelo`, `grandfather`],
  [`perfecto`, `perfect`],
  [`familia`, `family`],
  [`abuela`, `grandmother`],
  [`vivo`, `alive, brighter, live`],
  [`bicicleta`, `bicycle`],
  [`hija`, `daughter`],
  [`tienes`, `have, are, there's`],
  [`interesante`, `interesting`],
  [`hijo`, `son`],
  [`y`, `and`],
  [`verde`, `green`],
  [`azul`, `blue`],
  [`chaqueta`, `jacket`],
  [`tienda`, `store`],
  [`ropa`, `clothes`],
  [`camisa`, `shirt, blouse, top`],
  [`marrón`, `brown`],
  [`vestido`, `dress`],
  [`camiseta`, `T-shirt`],
  [`gris`, `gray, grey`],
  [`sombrero`, `hat`],
  [`comprar`, `to buy`],
  [`este`, `this`],
  [`rojo`, `red`],
  [`falda`, `skirt`],
  [`barato`, `cheap`],
  [`ese`, `that`],
  [`caro`, `expensive`],
  [`abrigo`, `coat`],
  [`diferente`, `different`],
  [`cartera`, `purse, bag, wallet`],
  [`cómoda`, `dresser, comfortable, convenient`],
  [`favorita`, `favorite`],
  [`reloj`, `watch, clock`],
  [`cinturón`, `belt`],
  [`regalo`, `gift`],
  [`demasiado`, `too`],
  [`bolígrafo`, `pen`],
  [`escuela`, `school`],
  [`libro`, `book`],
  [`examen`, `exam`],
  [`maestro`, `teacher`],
  [`fácil`, `easy`],
  [`clase`, `class`],
  [`difícil`, `difficult`],
  [`estudiante`, `student`],
  [`problema`, `problems, matter, trouble`],
  [`estudiar`, `to study`],
  [`leer`, `to read`],
  [`pregunta`, `question`],
  [`escribir`, `to write`],
  [`leo`, `I read, read, Leo`],
  [`comprendo`, `understand`],
  [`mucho`, `a lot`],
  [`estudio`, `(I) am studying, study, (I) study`],
  [`importante`, `important`],
  [`escribo`, `contribute, (I) write, (I) am writing`],
  [`profesor`, `professor`],
  [`escribes`, `writing, (you) write, (?) are you writing`],
  [`estudias`, `(you) study, (?) have you been studyin, (?) do you study`],
  [`lees`, `read, (you) are reading, (you) read`],
  [`computadora`, `computer`],
  [`universidad`, `university, college`],
  [`medicina`, `medicine`],
  [`americano`, `American`],
  [`me llamo`, `my name is`],
  [`España`, `Spain`],
  [`americana`, `American`],
  [`nombre`, `name`],
  [`cubana`, `Cuban`],
  [`mexicana`, `mexican`],
  [`cubano`, `Cuban`],
  [`mexicano`, `Mexican`],
  [`estás`, `you are, are, you're`],
  [`estoy`, `I'm, am, I am`],
  [`cansado`, `tired, made … tired, tired oneself out`],
  [`cómo`, `how's, what, how`],
  [`bien`, `ok, fine, well-to-do`],
  [`cansada`, `tired, made … tired, tired oneself out`],
  [`hasta luego`, `see you later, I'll see you later`],
  [`hasta mañana`, `see you tomorrow`],
  [`señora`, `ma'am, woman, lady`],
  [`usted`, `you, you'll`],
  [`buenas tardes`, `good afternoon, good evening`],
  [`señorita`, `lady, miss, Ms.`],
  [`señor`, `Mr., sir, gentleman`],
  [`cómo está`, `how's`],
  [`ocupado`, `busy, been on the game, concerned`],
  [`se llama`, `(her) name is, (his) name is, (it) is called`],
  [`te llamas`, `your name is, (?) is your name`],
  [`feliz`, `happy, apt, felicitous`],
  [`ocupada`, `busy`],
  [`mal`, `unwell, bad, ill`],
  [`té`, `tea, tea party`],
  [`más`, `more, any more, most`],
  [`banana`, `banana`],
  [`quiere`, `mean, wants, (?) do you want`],
  [`quieres`, `(?) do you want, want, (you) want`],
  [`necesita`, `(?) does she need, (you) need, (?) does he need`],
  [`necesitas`, `(you) need, (?) do you need, need`],
  [`ayuda`, `help, (you-formal) help, (he/she/it) helps`],
  [`usar`, `to use, to wear`],
  [`usa`, `(she) is using, (he) is using, (?) does he wear`],
  [`usas`, `(?) do you use, (?) are you using, (?) do you wear`],
  [`uso`, `(I) am wearing, (I) am using, (I) use`],
  [`fútbol`, `soccer, football`],
  [`lunes`, `Monday, Mondays`],
  [`hoy`, `today, nowadays`],
  [`martes`, `Tuesday, Tuesdays`],
  [`cuándo`, `when`],
  [`mañana`, `tomorrow, morning, future`],
  [`partido`, `game, match, departed`],
  [`qué`, `what, how`],
  [`día`, `day`],
  [`cumpleaños`, `birthday, birthday party, birthdays`],
  [`jueves`, `Thursday, Thursdays`],
  [`béisbol`, `baseball`],
  [`miércoles`, `Wednesday, Wednesdays`],
  [`viernes`, `Friday, Fridays`],
  [`sábado`, `Saturday, Sabbath`],
  [`domingo`, `Sunday, Sabbath, allowance`],
  [`divertido`, `fun`],
  [`concierto`, `concert, (I) arrange, (I) agree`],
  [`fiesta`, `party, holiday, don't`],
  [`divertida`, `funny, fun`],
  [`favorito`, `favorite`],
  [`semana`, `week, allowance, pocket money`],
  [`baile`, `dance, dance!, dance hall`],
  [`película`, `movie, film`],
  [`disfruta`, `(you) enjoy, (he) enjoys, (he) is enjoying`],
  [`fin de semana`, `weekend`],
  [`habla`, `(he) is speaking, (?) does he speak, speaks`],
  [`estudia`, `(you) study, (she) studies, (?) does he study`],
  [`hablar`, `to speak, to talk, (to) talk about`],
  [`francés`, `French`],
  [`quién`, `who, who (singular), whom`],
  [`fábrica`, `factory, stonework`],
  [`trabajas`, `(?) have you been working, (?) do you work, you've worked`],
  [`trabaja`, `work, (you) are working, (she) is working`],
  [`oficina`, `office`],
  [`trabajo`, `work, (I) work, jobs`],
  [`trabajar`, `to work`],
  [`comer`, `to eat, eat, eating`],
  [`vino`, `wine, (he/she/it/you) came, (he/she/it/you) arrived`],
  [`beber`, `to drink, drink, drinking`],
  [`vive`, `(he) lives, live, (?) do you live`],
  [`Europa`, `Europe`],
  [`vives`, `live, (?) do you live, (you) live`],
  [`vivir`, `to live, live, (to) be alive`],
  [`Inglaterra`, `England`],
  [`Francia`, `France`],
  [`camarera`, `waitress, barmaid, maid`],
  [`camarero`, `waiter, barman, bellboy`],
  [`maestra`, `teacher`],
  [`portugués`, `Portuguese`],
  [`celular`, `cell phone, cellphone, cell`],
  [`número`, `number, act, constable`],
  [`amigo`, `friend, buddy, bud`],
  [`dirección`, `direction, address, setting`],
  [`ser`, `(to) be, be, made`],
  [`amiga`, `friend`],
  [`joven`, `young, young man, young woman`],
  [`médica`, `doctor, medical`],
  [`ciudad`, `city, town`],
  [`médico`, `doctor`],
  [`novia`, `girlfriend, bride, fiancée`],
  [`pueblo`, `town, people, small town`],
  [`novio`, `boyfriend, fiancé, groom`],
  [`cero`, `zero, nought, love`],
  [`libros`, `books`],
  [`bolígrafos`, `pens, ballpoint pens`],
  [`biblioteca`, `library, bookcase, bookshelves`],
  [`computadoras`, `computers`],
  [`cuatro`, `four, number four, four-stringed guitar`],
  [`bibliotecas`, `libraries, bookshelves, bookcase`],
  [`esta`, `this`],
  [`aprendo`, `(I) am learning, learning, (I) learn`],
  [`aprender`, `to learn, learning, learn`],
  [`aprende`, `(she) is learning, (he) learns, (she) learns`],
  [`aprendes`, `(?) are you learning, (you) learn, learn`],
  [`cinco`, `five, moment`],
  [`clases`, `classes, to have classes, classrooms`],
  [`ocho`, `eight, number eight`],
  [`preguntas`, `questions`],
  [`estudiantes`, `students, university students, college students`],
  [`siete`, `seven, number seven, tear`],
  [`seis`, `six`],
  [`italiano`, `Italian`],
  [`bonita`, `nice, pretty, beautiful`],
  [`su`, `his, her, your formal`],
  [`pequeño`, `small, little ones, shorts`],
  [`hijos`, `children, sons`],
  [`pequeña`, `little, tiny, small`],
  [`mascota`, `pets, pet, mascot`],
  [`baja`, `turns down, goes down, low`],
  [`alto`, `tall, high, high ground`],
  [`simpático`, `nice, sympathetic, pleasant`],
  [`bajo`, `short`],
  [`simpática`, `nice`],
  [`alta`, `tall, high`],
  [`año`, `year`],
  [`diez`, `ten`],
  [`nueve`, `nine`],
  [`española`, `Spanish`],
  [`inglesa`, `English`],
  [`jefe`, `boss, manager`],
  [`secretario`, `secretary, minister`],
  [`mensaje`, `message, text`],
  [`las`, `your, the, their`],
  [`los`, `the, their, your`],
  [`escritorio`, `desk`],
  [`escribe`, `(?) does she write, (he) is writing, (you) write`],
  [`carta`, `letter, card`],
  [`cuál`, `what, which, which one`],
  [`poco`, `little, bit, a while`],
  [`correo electrónico`, `email`],
  [`tener`, `to have, have`],
  [`negocio`, `business, store, deal`],
  [`nuevo`, `new, newer, newest`],
  [`lee`, `lees, (she) is reading, read`],
  [`ahora`, `now, a moment ago`],
  [`emocionar`, `move, moves`],
  [`enfermo`, `sick, ill`],
  [`qué tal`, `how's, (?) how are you, how`],
  [`conmigo`, `with me`],
  [`contigo`, `with you`],
  [`triste`, `sad, dismal, gloomy`],
  [`siempre`, `always, providing (that), provided (that)`],
  [`enojado`, `annoyed, mad, angry`],
  [`aburrido`, `boring, bored, uninteresting`],
  [`preocupado`, `anxious, worried, concerned`],
  [`por qué`, `why, reason`],
  [`también`, `also, too, as well`],
  [`contento`, `happier, happy, glad`],
  [`papá`, `dad, father`],
  [`mamá`, `mom, mother`],
  [`dormir`, `to sleep, sleep, (to) fall asleep`],
  [`disfrutar`, `to enjoy, enjoy`],
  [`a veces`, `sometimes`],
  [`nunca`, `never`],
  [`sorprendido`, `surprised, shocked`],
  [`bebé`, `baby`],
  [`otra vez`, `again`],
  [`un poco`, `slightly, any, kind of`],
  [`te sientes`, `(?) do you feel, (?) are you feeling, (you) feel`],
  [`se siente`, `(he) feels, (she) feels, (she) is feeling`],
  [`me siento`, `I've been feeling (since), I feel, I'm feeling`],
  [`mujeres`, `women, wives`],
  [`hombres`, `men`],
  [`somos`, `we are, are, be`],
  [`nosotros`, `we, us`],
  [`estudiamos`, `study, (we) study, (we) studied`],
  [`nosotras`, `we, we (feminine), us`],
  [`hablamos`, `(we) speak, (we) are talking, speak`],
  [`ellos`, `they, them`],
  [`estudian`, `(they) are studying, (they) study, investigate`],
  [`ciudades`, `cities, towns`],
  [`universidades`, `universities, colleges`],
  [`ellas`, `they, them`],
  [`hablan`, `spoken, speaks, speak`],
  [`son`, `(?) are they, are, (they) are`],
  [`jugador`, `player`],
  [`muchos`, `lots of, a lot of, many`],
  [`ustedes`, `you guys, you, you all`],
  [`fines de semana`, `weekends`],
  [`muchas`, `many, a lot of, lots of`],
  [`cuánto`, `how much, what, how long`],
  [`unos`, `some, an, ones`],
  [`vacaciones`, `vacation, vacations`],
  [`unas`, `some, a few, a`],
  [`cuántas`, `how many`],
  [`señoras`, `ladies, Mrs.`],
  [`señores`, `men, gentlemen, sirs`],
  [`carteras`, `purses, wallets, satchels`],
  [`verdes`, `green, green (plural), 000 peseta note`],
  [`interesantes`, `interesting`],
  [`grandes`, `big, too big, large`],
  [`zapato`, `shoe`],
  [`bonitas`, `nice, pretty, beautiful`],
  [`nuevos`, `new, newer, newest`],
  [`nuevas`, `new, newer, newest`],
  [`usamos`, `(we) used, (we) wear, (we) use`],
  [`bonitos`, `beautiful, nice, pretty`],
  [`necesitamos`, `(?) do we need, (we) need, need`],
  [`pantalón`, `trousers, pants`],
  [`estas`, `these`],
  [`rojas`, `red`],
  [`rojos`, `red`],
  [`estos`, `these`],
  [`usan`, `(they) use, (they) are wearing, wear`],
  [`sus`, `your, his plural, her plural`],
  [`tus`, `your, your (plural)`],
  [`necesitan`, `(you) need, (they) need, need`],
  [`pequeñas`, `little, small, tiny`],
  [`pequeños`, `little, small, young`],
  [`mis`, `my`],
  [`estación`, `station, stations, season`],
  [`cerca de`, `close to`],
  [`ir`, `to go, (to) go, (to) go out`],
  [`viajar`, `to travel, travel`],
  [`cerca`, `close, near, nearby`],
  [`parque`, `park, parks, parked`],
  [`estamos`, `have been (since), (?) are we, (we) are`],
  [`al`, `to the, with, your`],
  [`del`, `of the, to the`],
  [`parada`, `stops, stop, caught`],
  [`puerta`, `door, gate`],
  [`lejos`, `far, far away, by far`],
  [`están`, `you are, are, (they/you-plural) are`],
  [`al lado`, `next to`],
  [`metro`, `meters, meter, subway`],
  [`derecha`, `right, right hand, right-hand`],
  [`tomar`, `to take, (to) take in, (to) have`],
  [`izquierda`, `left`],
  [`playa`, `beach, beaches`],
  [`periódico`, `newspaper, daily newspaper`],
  [`queremos`, `want, (we) want, love`],
  [`leemos`, `(we) are reading, (we) read, read`],
  [`caminar`, `to walk, walk`],
  [`sándwiches`, `sandwiches`],
  [`comemos`, `(we) eat, (we) are eating, (?) do you eat`],
  [`tarde`, `late, afternoon, evening`],
  [`vivimos`, `live, (we) lived, (we) have lived`],
  [`correos electrónicos`, `emails`],
  [`casas`, `houses, homes, you quash`],
  [`escribimos`, `(we) wrote, write, (we) write`],
  [`bueno`, `well, all right, anyway`],
  [`pollo`, `chicken`],
  [`comida`, `eaten, food, meal`],
  [`quieren`, `(they) want, (?) do you want, want`],
  [`comen`, `(?) do you eat, (?) are you eating, (they) eat`],
  [`arroz`, `rice`],
  [`restaurantes`, `restaurants`],
  [`junto`, `next, along, together`],
  [`verano`, `summer, summertime`],
  [`escriben`, `(they) are writing, (?) do you write, (they) write`],
  [`abrir`, `to open, (to) open out, (to) open up`],
  [`viven`, `(?) do you live, (they) live, are living`],
  [`leen`, `(they) read, (you) are reading, (?) do you read`],
  [`trabajan`, `(?) do they work, work, they've worked`],
  [`toma`, `(she) takes, takes, (he) takes`],
  [`trabajamos`, `work, (we) worked, (we) work`],
  [`tomamos`, `(?) should we have, made, we're drinking`],
  [`beben`, `(?) are they drinking, (they) drink, drinks`],
  [`abren`, `drive, get, (they) are opening`],
  [`abrimos`, `(we) open, we, (we) opened`],
  [`aprenden`, `(they) learn, (they) are learning, (?) are you learning`],
  [`compran`, `(they) buy, get, (they) are buying`],
  [`salir`, `to leave, to go out, to come out`],
  [`salimos`, `(we) went out, (we) go out, leave`],
  [`aprendemos`, `(we) learn, learn, (we) are learning`],
  [`compramos`, `(?) are we buying, (we) bought, (we) buy`],
  [`salen`, `(they) go out, (they) leave, (?) do they leave`],
  [`pastel`, `cake`],
  [`chocolate`, `chocolate`],
  [`porque`, `because`],
  [`me gusta`, `(I) like, like`],
  [`algo`, `something, anything, a little`],
  [`pero`, `but, only`],
  [`te gusta`, `(you) like, (?) do you like, you`],
  [`piscina`, `pool, swimming pool`],
  [`te encanta`, `(?) do you love, love`],
  [`jugar`, `to play, (to) play with, (to) game`],
  [`correr`, `to run, run, to race`],
  [`me encanta`, `love`],
  [`nadar`, `to swim, swimming, swim`],
  [`dibujar`, `to draw, draw, to sketch`],
  [`chico`, `boy, small`],
  [`viejo`, `old, old man`],
  [`música`, `music, composer, harmonica`],
  [`perros`, `dogs`],
  [`noche`, `night, evening`],
  [`cine`, `theater, movie theater, cinema`],
  [`todo`, `all, whole, everybody`],
  [`voy`, `go, I will leave, going`],
  [`va`, `is, there is going to, (she) goes`],
  [`a menudo`, `often`],
  [`vas`, `(you) go, go, (you) are going`],
  [`días`, `days`],
  [`media`, `meant, average, thirty`],
  [`televisión`, `television, TV`],
  [`sábados`, `Saturdays, Saturday, Sabbath`],
  [`van`, `(you) go, go, (they) will`],
  [`mirar`, `to look, (to) look at, (to) watch`],
  [`vamos`, `let's, we're going, (we) are going`],
  [`hora`, `hour, time`],
  [`domingos`, `Sundays, Sunday, Sabbath`],
  [`tengo que`, `(I) need to, (I) have to, have`],
  [`tienes que`, `(you) need, (you) have to, (you) must`],
  [`tiene que`, `(you) have to, (he) needs to, (she) must`],
  [`me levanto`, `(I) get up`],
  [`me ducho`, `(I) shower, shower`],
  [`se ducha`, `(she) showers, (he) showers, showers`],
  [`once`, `eleven, number eleven`],
  [`doce`, `twelve, number twelve`],
  [`te levantas`, `(you) get up, (you) are getting up, (?) do you get up`],
  [`te duchas`, `(?) do you shower, (you) shower, (?) are you showering`],
  [`a qué hora`, `when, (?) what time`],
  [`se levanta`, `(he) gets up, (?) does he get up, (?) are you getting up`],
  [`sala`, `lounge, living room, room`],
  [`nevera`, `fridge, refrigerator`],
  [`cama`, `bed`],
  [`dormitorio`, `room, bedroom, dormitory`],
  [`moderno`, `modern, fashionable`],
  [`cocina`, `(he) is cooking, (you) cook, kitchen`],
  [`hay`, `there is, there are, there's`],
  [`habitación`, `room, bedroom`],
  [`ventana`, `window`],
  [`tienen`, `(they) are, (?) is there, make`],
  [`tenemos`, `we're having, (we) are, (?) do we have`],
  [`silla`, `chair`],
  [`estantería`, `bookcase, bookshelf, shelf`],
  [`pintar`, `to paint, to draw, paint`],
  [`sobre`, `on, about, on top of`],
  [`limpiar`, `to clean, (to) ice, (to) clear`],
  [`planta`, `plants, plant, floor`],
  [`jardín`, `garden, yard`],
  [`debajo`, `under`],
  [`celulares`, `cell phones`],
  [`teléfonos`, `phones, telephones`],
  [`cerveza`, `beer`],
  [`menús`, `menus`],
  [`frijol`, `food, bean`],
  [`quisiera`, `(I) would like, (I) wish, wanted`],
  [`cuchara`, `spoon`],
  [`cuchillo`, `knife`],
  [`tenedor`, `fork`],
  [`plato`, `dish, course, plate`],
  [`puede traer`, `(?) can you bring`],
  [`bebida`, `drink`],
  [`otro`, `other, another one, another`],
  [`tinto`, `red`],
  [`botella`, `bottle`],
  [`blanco`, `white`],
  [`patata`, `potato`],
  [`frito`, `fried, fry`],
  [`sopa`, `soup`],
  [`postre`, `dessert`],
  [`nuestro`, `our, ours`],
  [`familias`, `families`],
  [`padres`, `parents, fathers`],
  [`se llaman`, `(?) are the names of, their names are, (they) are called`],
  [`deporte`, `sport, sports`],
  [`le gusta`, `(he) likes, likes, (?) do you like`],
  [`le encanta`, `loves, (he) loves, (?) do you love`],
  [`baloncesto`, `basketball`],
  [`piano`, `piano`],
  [`guitarra`, `guitar`],
  [`conciertos`, `concerts, concert`],
  [`nos gusta`, `(we) like, like`],
  [`tocar`, `to play, to touch, (to) touch`],
  [`escuchar`, `hear, (to) listen, (to) listen to`],
  [`nos encanta`, `we love, love`],
  [`marido`, `husband`],
  [`mayor`, `elderly, old, biggest`],
  [`menor`, `little, younger, youngest`],
  [`películas`, `movies, films`],
  [`mí`, `me`],
  [`abre`, `(it) opens, (?) does it open, open`],
  [`de compras`, `shopping`],
  [`cierra`, `(you) close, (?) does it close, lock`],
  [`ti`, `you, yourself`],
  [`buscar`, `to look for, (to) look for, (to) look up`],
  [`probador`, `fitting room`],
  [`talla`, `size, carve`],
  [`precio`, `price, charge, deal`],
  [`me puedo probar`, `(?) can I try on`],
  [`peso`, `(I) weigh out, shot, weight`],
  [`dólar`, `dollar`],
  [`catorce`, `fourteen`],
  [`quince`, `fifteen, (number) fifteen`],
  [`trece`, `thirteen, (number) thirteen`],
  [`cuestan`, `(they) cost, (?) do they cost, cost`],
  [`cuesta`, `is, it's hard, (it) is`],
  [`tarjeta de crédito`, `credit card, credit`],
  [`dieciocho`, `eighteen, number eighteen`],
  [`diecinueve`, `nineteen, number nineteen`],
  [`en efectivo`, `with cash`],
  [`veinte`, `twenty, (number) twenty`],
  [`dieciséis`, `sixteen`],
  [`diecisiete`, `seventeen, number seventeen`],
  [`emocionados`, `excited`],
  [`nervioso`, `nervous, tense`],
  [`tristes`, `sad`],
  [`felices`, `happy`],
  [`limpio`, `wash, clearer, I am cleaning`],
  [`abierto`, `made, open, raised`],
  [`sucio`, `dirty`],
  [`negro`, `black`],
  [`guapo`, `good-looking, handsome, dressed-up`],
  [`amarillo`, `yellow`],
  [`moreno`, `darker, dark-haired, brunette`],
  [`rubio`, `blond`],
  [`responsable`, `responsible, reliable`],
  [`perezoso`, `lazy`],
  [`estudioso`, `studious`],
  [`persona`, `person`],
  [`inteligentes`, `intelligent, smart`],
  [`aquel`, `that`],
  [`les encanta`, `(?) do they love, (they) love, loves`],
  [`para ella`, `in her opinion`],
  [`les gusta`, `(?) do they like, (they) like, like`],
  [`para él`, `in his opinion`],
  [`zoológico`, `zoo`],
  [`a mí`, `i, me`],
  [`a ti`, `you`],
  [`tenis`, `tennis, plimsoll, running shoe`],
  [`a él`, `he`],
  [`pasar`, `passing, go, spending`],
  [`tiempo`, `time, to play for time, weather`],
  [`a nosotros`, `us`],
  [`normalmente`, `normally, usually`],
  [`montar`, `riding, (to) ride, ride`],
  [`caballo`, `horse, horses`],
  [`pelota`, `ball`],
  [`río`, `Rio, (I) am laughing, river`],
  [`conoces`, `(you) know, (?) are you familiar with, (?) have you known`],
  [`país`, `country, land`],
  [`conocer`, `to meet, know, (to) know`],
  [`conozco`, `know, I'm familiar with, (I) know`],
  [`visitar`, `(to) visit, visiting, visit`],
  [`parte`, `part, leaves, some`],
  [`lugar`, `location, place, stood`],
  [`gente`, `people, good, kind`],
  [`pueblos`, `towns, peoples, small town`],
  [`alguno`, `any, some (people), one`],
  [`ayudar`, `help, assist, helping`],
  [`llamar`, `calling, hails, telephone`],
  [`usualmente`, `usually, normally`],
  [`ver`, `saw, (to) look, watching`],
  [`amar`, `(to) love, love`],
  [`enseñar`, `(to) teach, teach, taught`],
  [`tele`, `TV, television, telly`],
  [`adulto`, `adult`],
  [`cuántos años`, `how old`],
  [`veintiún`, `twenty-one`],
  [`jóvenes`, `young, young people, young women`],
  [`señoritas`, `ladies, girls, young ladies`],
  [`veintidós`, `twenty-two`],
  [`veintiuno`, `twenty-one, twenty first`],
  [`pizza`, `pizza`],
  [`sed`, `thirsty, thirst`],
  [`veinticinco`, `twenty-five`],
  [`hambre`, `hunger, hungry`],
  [`jugos`, `juices`],
  [`veintitrés`, `twenty-three`],
  [`veinticuatro`, `twenty-four`],
  [`largo`, `long`],
  [`frío`, `cold, (I) fry, (I) waste`],
  [`puesto`, `(I) have on, put, on`],
  [`calor`, `hot, warm, heat`],
  [`animal`, `animal`],
  [`bailar`, `(to) dance, how to dance, dancing`],
  [`sueño`, `tired, dream, sleepy`],
  [`miedo`, `scared, fear, afraid`],
  [`de verdad`, `real, for real, really`],
  [`ganas`, `(you) win, (you) earn, make`],
  [`muñeca`, `doll, wrist`],
  [`me`, `myself, I, me`],
  [`nos`, `we, for us, ourselves`],
  [`te`, `your, you'll, you`],
  [`me compra`, `(she) buys me, (he) is buying me, (he) buys me`],
  [`nos compra`, `(he) buys us, (she) buys us`],
  [`te compra`, `(she) buys you, (he) buys you`],
  [`me escucha`, `(he) listens to me, (she) listens to me, (you) listen to me`],
  [`te visitan`, `(they) visit you`],
  [`me conoce`, `(he) knows me, (you) know me, (she) knows me`],
  [`me necesita`, `(she) needs me, (he) needs me`],
  [`nos conocen`, `(they) know us, they've known us`],
  [`te conozco`, `(I) know you`],
  [`nos visita`, `(she) is visiting us, (he) visits us, (he) is visiting us`],
  [`te llamamos`, `(we) call you`],
  [`nos escuchan`, `(they) listen to us`],
  [`me llaman`, `(they) call me`],
  [`me ama`, `(she) loves me`],
  [`nos llamas`, `call us`],
  [`te necesito`, `(I) need you`],
  [`curso`, `course, class, grade`],
  [`alemán`, `German`],
  [`idioma`, `language`],
  [`me enseña`, `(she) is teaching me, (he) teaches me, (he) is teaching me`],
  [`nos ayudan`, `(they) help us`],
  [`me ayudas`, `(you) help me, (?) can you help me, (?) will you help me`],
  [`almuerzo`, `lunch, (I) eat lunch`],
  [`haces`, `(you) make, (?) are you doing, made`],
  [`desayuno`, `breakfast, (I) eat breakfast`],
  [`tarea`, `homework, assignment, task`],
  [`cena`, `dinner, supper`],
  [`hacer`, `to do, (to) do, (to) make`],
  [`hago`, `made, (I) make, make`],
  [`tomo`, `(I) drink, drink, (I) am taking`],
  [`diario`, `paper, daily, newspaper`],
  [`cosa`, `thing`],
  [`solo`, `by itself, by myself, by yourself`],
  [`después`, `after, next, afterward`],
  [`antes`, `before, previously, first`],
  [`ducharse`, `(to) shower, (to) take a shower, shower`],
  [`ponerse`, `to put on, (to) take (oneself), (to) fit (oneself)`],
  [`se pone`, `(he) puts on, (she) puts on, (?) is she putting on`],
  [`cada`, `every, each`],
  [`me pongo`, `(I) am putting on, I'm putting on, (I) put on`],
  [`te pones`, `(you) put on, (you) wear, (?) are you putting on`],
  [`levantarse`, `to get up, (to) take (oneself), (to) pinch (oneself)`],
  [`sale`, `departs, issues, (he) is leaving`],
  [`semanas`, `weeks, allowances, pocket money`],
  [`temprano`, `early`],
  [`salgo`, `(I) leave, I'm leaving, leaving`],
  [`probar`, `to try, (to) try on, (to) prove`],
  [`almuerzan`, `(they) eat lunch, (they) are having lunch, (you) have lunch`],
  [`almorzar`, `to have lunch, (to) have elevenses, (to) have a mid-morning snack`],
  [`prueba`, `try, touch, quiz`],
  [`probamos`, `(we) try, (we) are trying, try`],
  [`pruebo`, `try, touch, essay`],
  [`prueban`, `try, touch, (they) try`],
  [`almorzamos`, `(we) eat lunch, (we) have lunch, (we) are having lunch`],
  [`almuerzas`, `(?) are you having lunch, (?) do you have lunch, lunch`],
  [`volvemos`, `(we) are going back, (we) return, (we) go`],
  [`poder`, `to be able to`],
  [`puede`, `(I) may, (?) could you, (?) can you`],
  [`vuelves`, `(you) come back, (you) are going back, (you) return`],
  [`vuelven`, `again, (they) are going back, (you) go back`],
  [`podemos`, `can, (?) can we, (we) can`],
  [`pueden`, `(they) can, (you) could, may`],
  [`puedo`, `(I) can, can, may I`],
  [`volver`, `to go back, to return, come back`],
  [`cierras`, `(?) do you close, (?) can you close, (you) are closing`],
  [`empezamos`, `(we) started, begin, (we) start`],
  [`cerrar`, `to close, (to) close up, (to) close down`],
  [`empiezo`, `(I) am starting, (I) start, start`],
  [`empiezan`, `(they) are starting, (they) start, start`],
  [`empieza`, `begin, (?) does it start, (it) begins`],
  [`cierran`, `(they) close, (you) are closing, close`],
  [`cerramos`, `(we) closed, (we) close, (we) lock`],
  [`empezar`, `to start, (to) begin, (to) open`],
  [`entiendo`, `(I) can understand, understand, get`],
  [`perdemos`, `lose, (we) lose, (we) miss`],
  [`entienden`, `(?) do you understand, understand, (they) understand`],
  [`perder`, `to lose, (to) miss, (to) lose one's way`],
  [`entiende`, `understand, (?) do you understand, (he) understands`],
  [`entender`, `to understand`],
  [`pierden`, `(they) lose, (they) are losing, lose`],
  [`entendemos`, `(we) understand, understand`],
  [`pierdes`, `(you) miss, lose, (you) are wasting`],
  [`viento`, `wind, windy`],
  [`qué tiempo hace`, `what's the weather like`],
  [`sol`, `sun, G, so`],
  [`invierno`, `winter`],
  [`oscuro`, `dark, darker`],
  [`nublado`, `cloudy`],
  [`enero`, `January`],
  [`cómo está el tiempo`, `how's the weather`],
  [`febrero`, `February`],
  [`marzo`, `March`],
  [`primavera`, `spring, springtime`],
  [`mayo`, `May`],
  [`julio`, `July, joule`],
  [`junio`, `June`],
  [`llueve`, `(?) does it rain, (it) rains, raining`],
  [`abril`, `April`],
  [`nieva`, `snow, (it) snows, (?) is it snowing`],
  [`otoño`, `autumn, fall`],
  [`mes`, `month`],
  [`noviembre`, `November`],
  [`octubre`, `October`],
  [`diciembre`, `December`],
  [`septiembre`, `September`],
  [`agosto`, `August, (I) wither, (I) parch`],
  [`foto`, `picture, photo, photos`],
  [`conversación`, `conversation`],
  [`nos interesa`, `(we) are interested in`],
  [`te interesa`, `(?) does it interest you, (?) are you interested in`],
  [`les interesa`, `(?) are you interested in, (they) are interested in`],
  [`le interesa`, `(he) is interested in, (she) is interested in, is into`],
  [`me interesa`, `I'm interested in, (it) interests me, I am interested in`],
  [`europeo`, `European`],
  [`arte`, `art`],
  [`pintura`, `painting, paint`],
  [`importantes`, `important, considerable (plural), serious (plural)`],
  [`preferir`, `preferring, preferred, (to) prefer`],
  [`juego`, `playing, games, play`],
  [`cuáles`, `which, what, which ones`],
  [`jugamos`, `(we) are playing, (we) play, played`],
  [`básquetbol`, `basketball`],
  [`practicar`, `to practice`],
  [`grupo`, `band, group, stood`],
  [`asignatura`, `subject`],
  [`radio`, `radio`],
  [`fiestas`, `parties, festival, festivals`],
  [`partidos`, `games, matches, administrative area`],
  [`esto`, `this`],
  [`respuesta`, `answer, response, reply`],
  [`palabra`, `word`],
  [`edad`, `age`],
  [`sabes`, `(you) know, know, (?) do you know`],
  [`sé`, `know, can, (I) know how to`],
  [`saber`, `to know, (to) know, (to) know how to swim`],
  [`cómo se dice`, `(?) how do you say`],
  [`sabe usted`, `(?) do you know`],
  [`sabes quién`, `(?) do you know who`],
  [`sabes cuándo`, `(?) do you know when`],
  [`no lo sé`, `I do not know, I don't know`],
  [`cómo se escribe`, `(?) how do you write`],
  [`manejar`, `drive, driving, handles`],
  [`cocinar`, `(to) cook, how to cook, cooking`],
  [`carnes`, `meats`],
  [`sabes nadar`, `(you) know how to swim`],
  [`canción`, `song`],
  [`cantar`, `(to) sing, singing, sing`],
  [`chino`, `Chinese, curly`],
  [`mismo`, `same, himself`],
  [`lengua`, `language, tongues, tongue`],
  [`japonés`, `Japanese`],
  [`gorra`, `cap`],
  [`blusa`, `blouse`],
  [`cómodo`, `idle, comfy, convenient`],
  [`menos`, `minus, fewer, but`],
  [`que`, `than, that, to`],
  [`bello`, `beautiful, pretty`],
  [`mejor`, `the better, better, best`],
  [`peor`, `worse, worst`],
  [`famoso`, `celebrated, famous, celebrity`],
  [`tan`, `that, so, as`],
  [`delgado`, `thin, slim, slight`],
  [`gordo`, `fat`],
  [`mundo`, `world`],
  [`el más`, `the most`],
  [`el peor`, `the worst one`],
  [`la más`, `the most`],
  [`popular`, `popular, folk`],
  [`próximo`, `next, nearest, ahead`],
  [`voy a`, `will, i'm`],
  [`pasaportes`, `passports`],
  [`va a`, `is, she's, will`],
  [`maletas`, `suitcases, Luggage, bags`],
  [`vas a`, `you're, attend, will`],
  [`boletos`, `tickets, coupons`],
  [`avión`, `plane, airplane, aircraft`],
  [`listo`, `smart, ready, cute`],
  [`llegar`, `to arrive, (to) reach, (to) come`],
  [`vamos a`, `will`],
  [`van a`, `will`],
  [`adónde`, `where`],
  [`carros`, `cars, automobiles, carriages`],
  [`taxis`, `taxis`],
  [`estar`, `being, (to) be, were`],
  [`veintisiete`, `twenty-seven`],
  [`veintiséis`, `twenty-six`],
  [`pronto`, `soon, early, prompt`],
  [`por`, `to, because, through`],
  [`minuto`, `minute`],
  [`cámara`, `camera`],
  [`cuarto`, `quarter, room, bedroom`],
  [`treinta`, `thirty, (number) thirty`],
  [`veintiocho`, `twenty-eight`],
  [`veintinueve`, `twenty-nine`],
  [`dulce`, `mild, softer, milder`],
  [`chileno`, `Chilean`],
  [`ensaladas`, `salads`],
  [`vinos`, `wines, receptions`],
  [`gustan`, `(?) do they like, (we) like, (I) like`],
  [`bananas`, `bananas`],
  [`encantan`, `(we) love, (I) love`],
  [`caliente`, `hot, warm`],
  [`ojo`, `eye, look out`],
  [`francesa`, `French`],
  [`flor`, `flower`],
  [`tipo`, `types, kinds, stick`],
  [`rápido`, `quick, quickly, smarter`],
  [`sitio`, `site, location, place`],
  [`pájaro`, `bird`],
  [`interesan`, `interest, (we) are interested`],
  [`bailes`, `dances`],
  [`bota`, `boot, jump`],
  [`color`, `color, colors, dye`],
  [`par`, `pair, couple`],
  [`ambos`, `both`],
  [`lentes`, `glasses, spectacles, lenses`],
  [`vaqueros`, `jeans`],
  [`kilo`, `kilo, kilogram`],
  [`fruta`, `fruit`],
  [`bolsa`, `bag`],
  [`plátano`, `banana`],
  [`tenemos que`, `(?) do we need to, (we) have to, need`],
  [`compra`, `(he) is buying, groceries, buy`],
  [`huevo`, `egg, ball, lump`],
  [`papa`, `potato`],
  [`vegetal`, `vegetable, plant`],
  [`cuánta`, `how much`],
  [`tienen que`, `has to, need, (they) have to`],
  [`mantequilla`, `butter`],
  [`picante`, `hot, spicy, salty`],
  [`chorizo`, `sausage, chorizo`],
  [`centavo`, `cent, penny`],
  [`sesenta`, `sixty`],
  [`llevar`, `to carry, (to) wear, (to) ride`],
  [`cuarenta`, `forty, number forty`],
  [`cincuenta`, `fifty, number fifty`],
  [`refrigerador`, `fridge, refrigerator, refrigerators`],
  [`lavar`, `(to) wash, washed, wash`],
  [`pones`, `(you) play, (you) put, play`],
  [`poner`, `to put, (to) put on, (to) put in`],
  [`pongo`, `(?) should I put, (I) get, (I) put`],
  [`despacio`, `slowly, gently, quietly`],
  [`pruebe`, `tries, (you) try, try`],
  [`trabaje`, `(you) work, work, works`],
  [`hable`, `speaks, (you) speak, talk`],
  [`página`, `page`],
  [`abres`, `unlocking, open, (?) can you open`],
  [`vuelve`, `(you) come back, (you) return, (?) are you coming back`],
  [`lápiz`, `pencil`],
  [`escriba`, `(you) write, writes, write`],
  [`vuelva`, `get back, (you) come back, (he/she) returns`],
  [`beba`, `drink, (you) drink, have`],
  [`mano`, `hand`],
  [`me lavo`, `(I) wash`],
  [`nos levantamos`, `(we) get up, (?) are we getting up, (we) got up`],
  [`nos llamamos`, `our names are`],
  [`lavarse`, `to wash, to wash up, to wash yourself up`],
  [`nos duchamos`, `we shower, (we) are showering, (we) showered`],
  [`mío`, `mine`],
  [`cabello`, `hair`],
  [`cara`, `face, expensive, faces`],
  [`llave`, `key, lock`],
  [`se lavan`, `(you) wash, (they) wash themselves`],
  [`se duchan`, `(?) are they showering, (they) shower, (?) do you shower`],
  [`se levantan`, `(they) get up, (?) do you get up, stands up`],
  [`suyo`, `hers, yours, theirs`],
  [`tuyo`, `yours`],
  [`nos ponemos`, `makes us, (we) put on, put`],
  [`se ponen`, `(you) put on, put, (you) are putting on`],
  [`nos sentimos`, `feel`],
  [`se sienten`, `(?) do you feel, (they) feel, feel`],
  [`me cepillo`, `(I) brush`],
  [`diente`, `tooth, teeth`],
  [`cepillo`, `brush, hair, hairbrush`],
  [`cepillo de dientes`, `toothbrush`],
  [`cepillarse`, `to brush`],
  [`nos cepillamos`, `(we) are brushing, (we) brush`],
  [`se cepillan`, `(they) brush, (you) brush`],
  [`aula`, `classroom`],
  [`lección`, `lesson, lecture`],
  [`escuchando`, `listening to, hearing, listening`],
  [`estudiando`, `studying`],
  [`hablando`, `talking, speaking, ringing`],
  [`diccionario`, `dictionary`],
  [`comiendo`, `eating, having, taking`],
  [`haciendo`, `doing, acting, getting`],
  [`aprendiendo`, `learning`],
  [`nota`, `note, grade, (he) notices`],
  [`pizarra`, `chalkboard, blackboard, whiteboard`],
  [`escribiendo`, `writing`],
  [`abriendo`, `opening`],
  [`saliendo`, `coming out, leading, leave`],
  [`escuelas`, `schools, coaching, colleges`],
  [`leyendo`, `reading`],
  [`bebiendo`, `drinking, he's having, having`],
  [`dibujando`, `drawing`],
];