const spanish_numbers = [
  [`Uno`, `1`],
  [`Dos`, `2`],
  [`Tres`, `3`],
  [`Cuatro`, `4`],
  [`Cinco`, `5`],
  [`Seis`, `6`],
  [`Siete`, `7`],
  [`Ocho`, `8`],
  [`Nueve`, `9`],
  [`Diez`, `10`],
  [`Once`, `11`],
  [`Doce`, `12`],
  [`Trece`, `13`],
  [`Catorce`, `14`],
  [`Quince`, `15`],
  [`Dieciséis`, `16`],
  [`Diecisiete`, `17`],
  [`Dieciocho`, `18`],
  [`Diecinueve`, `19`],
  [`Veinte`, `20`],
  [`Veintiuno`, `21`],
  [`Veintidós`, `22`],
  [`Veintitrés`, `23`],
  [`Veinticuatro`, `24`],
  [`Veinticinco`, `25`],
  [`Veintiséis`, `26`],
  [`Veintisiete`, `27`],
  [`Veintiocho`, `28`],
  [`Veintinueve`, `29`],
  [`Treinta`, `30`],
  [`Treinta y uno`, `31`],
  [`Treinta y dos`, `32`],
  [`Treinta y tres`, `33`],
  [`Treinta y cuatro`, `34`],
  [`Treinta y cinco`, `35`],
  [`Treinta y seis`, `36`],
  [`Treinta y siete`, `37`],
  [`Treinta y ocho`, `38`],
  [`Treinta y nueve`, `39`],
  [`Cuarenta`, `40`],
  [`Cuarenta y uno`, `41`],
  [`Cuarenta y dos`, `42`],
  [`Cuarenta y tres`, `43`],
  [`Cuarenta y cuatro`, `44`],
  [`Cuarenta y cinco`, `45`],
  [`Cuarenta y seis`, `46`],
  [`Cuarenta y siete`, `47`],
  [`Cuarenta y ocho`, `48`],
  [`Cuarenta y nueve`, `49`],
  [`Cincuenta`, `50`],
  [`Cincuenta y uno`, `51`],
  [`Cincuenta y dos`, `52`],
  [`Cincuenta y tres`, `53`],
  [`Cincuenta y cuatro`, `54`],
  [`Cincuenta y cinco`, `55`],
  [`Cincuenta y seis`, `56`],
  [`Cincuenta y siete`, `57`],
  [`Cincuenta y ocho`, `58`],
  [`Cincuenta y nueve`, `59`],
  [`Sesenta`, `60`],
  [`Sesenta y uno`, `61`],
  [`Sesenta y dos`, `62`],
  [`Sesenta y tres`, `63`],
  [`Sesenta y cuatro`, `64`],
  [`Sesenta y cinco`, `65`],
  [`Sesenta y seis`, `66`],
  [`Sesenta y siete`, `67`],
  [`Sesenta y ocho`, `68`],
  [`Sesenta y nueve`, `69`],
  [`Setenta`, `70`],
  [`Setenta y uno`, `71`],
  [`Setenta y dos`, `72`],
  [`Setenta y tres`, `73`],
  [`Setenta y cuatro`, `74`],
  [`Setenta y cinco`, `75`],
  [`Setenta y seis`, `76`],
  [`Setenta y siete`, `77`],
  [`Setenta y ocho`, `78`],
  [`Setenta y nueve`, `79`],
  [`Ochenta`, `80`],
  [`Ochenta y uno`, `81`],
  [`Ochenta y dos`, `82`],
  [`Ochenta y tres`, `83`],
  [`Ochenta y cuatro`, `84`],
  [`Ochenta y cinco`, `85`],
  [`Ochenta y seis`, `86`],
  [`Ochenta y siete`, `87`],
  [`Ochenta y ocho`, `88`],
  [`Ochenta y nueve`, `89`],
  [`Noventa`, `90`],
  [`Noventa y uno`, `91`],
  [`Noventa y dos`, `92`],
  [`Noventa y tres`, `93`],
  [`Noventa y cuatro`, `94`],
  [`Noventa y cinco`, `95`],
  [`Noventa y seis`, `96`],
  [`Noventa y siete`, `97`],
  [`Noventa y ocho`, `98`],
  [`Noventa y nueve`, `99`],
  [`Cien`, `100`],
  [`Primero`, `1st`],
  [`Segundo`, `2nd`],
  [`Tercero`, `3rd`],
  [`Cuarto`, `4th`],
  [`Quinto`, `5th`],
  [`Sexto`, `6th`],
  [`Séptimo`, `7th`],
  [`Octavo`, `8th`],
  [`Noveno`, `9th`],
  [`Décimo`, `10th`],
  [`Undécimo`, `11th`],
  [`Duodécimo`, `12th`],
  [`Décimotercero`, `13th`],
  [`Décimocuarto`, `14th`],
  [`Décimoquinto`, `15th`],
  [`Décimosexto`, `16th`],
  [`Décimoséptimo`, `17th`],
  [`Décimoctavo`, `18th`],
  [`Décimonoveno`, `19th`],
  [`Vigésimo`, `20th`],
  [`Vigésimo primero`, `21st`],
  [`Vigésimo segundo`, `22nd`],
  [`Vigésimo tercero`, `23rd`],
  [`Vigésimo cuarto`, `24th`],
  [`Vigésimo quinto`, `25th`],
  [`Vigésimo sexto`, `26th`],
  [`Vigésimo séptimo`, `27th`],
  [`Vigésimo octavo`, `28th`],
  [`Vigésimo noveno`, `29th`],
  [`Trigésimo`, `30th`],
  [`Trigésimo primero`, `31st`],
  [`Trigésimo segundo`, `32nd`],
  [`Trigésimo tercero`, `33rd`],
  [`Trigésimo cuarto`, `34th`],
  [`Trigésimo quinto`, `35th`],
  [`Trigésimo sexto`, `36th`],
  [`Trigésimo séptimo`, `37th`],
  [`Trigésimo octavo`, `38th`],
  [`Trigésimo noveno`, `39th`],
  [`Cuadragésimo`, `40th`],
  [`Cuadragésimo primero`, `41st`],
  [`Cuadragésimo segundo`, `42nd`],
  [`Cuadragésimo tercero`, `43rd`],
  [`Cuadragésimo cuarto`, `44th`],
  [`Cuadragésimo quinto`, `45th`],
  [`Cuadragésimo sexto`, `46th`],
  [`Cuadragésimo séptimo`, `47th`],
  [`Cuadragésimo octavo`, `48th`],
  [`Cuadragésimo noveno`, `49th`],
  [`Quincuagésimo`, `50th`],
  [`Quincuagésimo primero`, `51st`],
  [`Quincuagésimo segundo`, `52nd`],
  [`Quincuagésimo tercero`, `53rd`],
  [`Quincuagésimo cuarto`, `54th`],
  [`Quincuagésimo quinto`, `55th`],
  [`Quincuagésimo sexto`, `56th`],
  [`Quincuagésimo séptimo`, `57th`],
  [`Quincuagésimo octavo`, `58th`],
  [`Quincuagésimo noveno`, `59th`],
  [`Sexagésimo`, `60th`],
  [`Sexagésimo primero`, `61st`],
  [`Sexagésimo segundo`, `62nd`],
  [`Sexagésimo tercero`, `63rd`],
  [`Sexagésimo cuarto`, `64th`],
  [`Sexagésimo quinto`, `65th`],
  [`Sexagésimo sexto`, `66th`],
  [`Sexagésimo séptimo`, `67th`],
  [`Sexagésimo octavo`, `68th`],
  [`Sexagésimo noveno`, `69th`],
  [`Septuagésimo`, `70th`],
  [`Septuagésimo primero`, `71st`],
  [`Septuagésimo segundo`, `72nd`],
  [`Septuagésimo tercero`, `73rd`],
  [`Septuagésimo cuarto`, `74th`],
  [`Septuagésimo quinto`, `75th`],
  [`Septuagésimo sexto`, `76th`],
  [`Septuagésimo séptimo`, `77th`],
  [`Septuagésimo octavo`, `78th`],
  [`Septuagésimo noveno`, `79th`],
  [`Octogésimo`, `80th`],
  [`Octogésimo primero`, `81st`],
  [`Octogésimo segundo`, `82nd`],
  [`Octogésimo tercero`, `83rd`],
  [`Octogésimo cuarto`, `84th`],
  [`Octogésimo quinto`, `85th`],
  [`Octogésimo sexto`, `86th`],
  [`Octogésimo séptimo`, `87th`],
  [`Octogésimo octavo`, `88th`],
  [`Octogésimo noveno`, `89th`],
  [`Nonagésimo`, `90th`],
  [`Nonagésimo primero`, `91st`],
  [`Nonagésimo segundo`, `92nd`],
  [`Nonagésimo tercero`, `93rd`],
  [`Nonagésimo cuarto`, `94th`],
  [`Nonagésimo quinto`, `95th`],
  [`Nonagésimo sexto`, `96th`],
  [`Nonagésimo séptimo`, `97th`],
  [`Nonagésimo octavo`, `98th`],
  [`Nonagésimo noveno`, `99th`],
  [`Centésimo`, `100th`],
]